package net.forbric.kernel.boot;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.parallel.ResourceLock;
import org.objectweb.asm.*;import org.objectweb.asm.tree.*;
@ResourceLock("DefinedMethodContracts")
class NativeDefaultDispatchPathsTest {
 static String active;static boolean accepted;static int terminalCalls;static List<StackWalker.StackFrame>lastFrames;
 public interface Actor{boolean question(Kind kind);boolean sensitive();}
 public interface Base extends Actor{private Actor self(){return (Actor)this;}default boolean question(Kind kind){return kind.answer(self());}}
 public static final class Constants{static final Kind SPECIAL=new Kind(),OTHER=new Kind();}
 public interface Conditional extends Base{@Override default boolean question(Kind kind){if(kind==Constants.SPECIAL)return !sensitive();return Base.super.question(kind);}}
 public interface Sibling extends Base{@Override default boolean question(Kind kind){return Base.super.question(kind);}}
 public static class Forwarder implements Conditional{public boolean question(Kind kind){return Conditional.super.question(kind);}public boolean sensitive(){return false;}}
 public static final class Child extends Forwarder{}
 public static final class Opaque extends Forwarder{@Override public boolean question(Kind kind){boolean value=super.question(kind);return !value;}}
 public interface WrongKind extends Base{@Override default boolean question(Kind kind){if(kind==Constants.SPECIAL)return !sensitive();return Base.super.question(Constants.OTHER);}}
 public static final class WrongForwarder implements WrongKind{public boolean question(Kind kind){return WrongKind.super.question(kind);}public boolean sensitive(){return false;}}
 public static class Kind{public boolean answer(Actor actor){terminalCalls++;lastFrames=StackWalker.getInstance(StackWalker.Option.RETAIN_CLASS_REFERENCE).walk(frames->frames.toList());accepted=NativeDefaultDispatchPaths.permits(actor,this,active,lastFrames);return true;}}
 @BeforeEach @AfterEach void reset(){DefinedMethodContracts.resetForTests();NativeDefaultDispatchPaths.resetForTests();accepted=false;terminalCalls=0;lastFrames=null;}
 @Test void onlyAnActuallyReachedNativeFallbackOwnsTheTerminal()throws Exception{Fixture fixture=fixture();active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,fixture.nodes::get);assertTrue(new Child().question(new Kind()));assertTrue(accepted);assertEquals(1,terminalCalls);accepted=false;terminalCalls=0;assertTrue(new Child().question(Constants.SPECIAL));assertFalse(accepted);assertEquals(0,terminalCalls);}
 @Test void opaqueOverridesAndChangedArgumentsRemainNative()throws Exception{Fixture fixture=fixture();active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,fixture.nodes::get);assertFalse(new Opaque().question(new Kind()));assertFalse(accepted);assertEquals(1,terminalCalls);accepted=false;terminalCalls=0;assertTrue(new WrongForwarder().question(new Kind()));assertFalse(accepted);assertEquals(1,terminalCalls);}
 @Test void missingNativeProvenanceAndChangedFinalDefaultsFailClosed()throws Exception{Fixture fixture=fixture();String conditional=Type.getInternalName(Conditional.class);active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,name->name.equals(conditional)?null:fixture.nodes.get(name));new Child().question(new Kind());assertFalse(accepted);
  active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,fixture.nodes::get);ClassNode changed=read(bytes(Conditional.class));MethodNode method=find(changed,"question");method.instructions.insert(new InsnNode(Opcodes.NOP));DefinedMethodContracts.observe(Conditional.class.getClassLoader(),Conditional.class.getName(),write(changed));new Child().question(new Kind());assertFalse(accepted);
 }
 @Test void aPrivateIdentityMustHaveItsOwnFinalBodyAndFlags()throws Exception{Fixture fixture=fixture();active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,fixture.nodes::get);ClassNode changed=read(bytes(Base.class));MethodNode identity=find(changed,"self");identity.instructions.insert(new InsnNode(Opcodes.NOP));DefinedMethodContracts.observe(Base.class.getClassLoader(),Base.class.getName(),write(changed));new Child().question(new Kind());assertFalse(accepted);}
 @Test void aForgedCallSiteDoesNotWitnessAConditionalFallback()throws Exception{Fixture fixture=fixture();active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,fixture.nodes::get);Child actor=new Child();Kind kind=new Kind();actor.question(kind);assertTrue(accepted);List<StackWalker.StackFrame>wrong=new ArrayList<>(lastFrames);for(int i=0;i<wrong.size();i++)if(wrong.get(i).getDeclaringClass()==Conditional.class){StackWalker.StackFrame original=wrong.get(i);wrong.set(i,new AlteredFrame(original,0));break;}assertFalse(NativeDefaultDispatchPaths.permits(actor,kind,active,wrong));}
 @Test void aGraftMayOnlyMaterializeTheUniqueOriginallyInheritedDefault()throws Exception{Fixture fixture=fixture();Map<String,ClassNode>nativeNodes=new HashMap<>(fixture.nodes);ClassNode before=read(bytes(Forwarder.class));before.methods.removeIf(m->m.name.equals("question"));nativeNodes.put(before.name,before);active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,nativeNodes::get);new Child().question(new Kind());assertTrue(accepted);
  ClassNode wrong=read(write(before));wrong.interfaces.clear();wrong.interfaces.add(Type.getInternalName(Base.class));nativeNodes.put(wrong.name,wrong);accepted=false;active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,nativeNodes::get);new Child().question(new Kind());assertFalse(accepted);
  ClassNode ambiguous=read(write(before));ambiguous.interfaces.add(Type.getInternalName(Sibling.class));nativeNodes.put(ambiguous.name,ambiguous);accepted=false;active=NativeDefaultDispatchPaths.register(fixture.base,fixture.nodes::get,nativeNodes::get);new Child().question(new Kind());assertFalse(accepted);
 }
 @Test void reregisteringTheSameClassCannotReuseAnOlderReadersEdge()throws Exception{Fixture fixture=fixture();Map<String,ClassNode>nativeNodes=new HashMap<>(fixture.nodes);java.util.function.Function<String,ClassNode>current=fixture.nodes::get,nativeReader=nativeNodes::get;String first=NativeDefaultDispatchPaths.register(fixture.base,current,nativeReader);active=first;new Child().question(new Kind());assertTrue(accepted);
  nativeNodes.remove(Type.getInternalName(Conditional.class));String second=NativeDefaultDispatchPaths.register(fixture.base,current,nativeReader);assertNotEquals(first,second);active=second;accepted=false;new Child().question(new Kind());assertFalse(accepted,"same class and the same reader function objects must rederive new provenance");
 }
 private record Fixture(DefinedMethodContracts.MethodContract base,Map<String,ClassNode>nodes){}
 private Fixture fixture()throws Exception{Map<String,ClassNode>nodes=new HashMap<>();for(Class<?>type:List.of(Base.class,Conditional.class,Forwarder.class,Child.class,Opaque.class,Sibling.class,WrongKind.class,WrongForwarder.class,Actor.class,Kind.class,Constants.class)){byte[] bytes=bytes(type);nodes.put(Type.getInternalName(type),read(bytes));DefinedMethodContracts.observe(type.getClassLoader(),type.getName(),bytes);}MethodNode method=find(nodes.get(Type.getInternalName(Base.class)),"question");return new Fixture(new DefinedMethodContracts.MethodContract(Base.class.getName(),method.name,method.desc,DefinedMethodContracts.fingerprint(method)),nodes);}
 private static byte[]bytes(Class<?>type)throws Exception{try(var input=type.getResourceAsStream("/"+Type.getInternalName(type)+".class")){return input.readAllBytes();}}
 private static ClassNode read(byte[]bytes){ClassNode node=new ClassNode();new ClassReader(bytes).accept(node,0);return node;}
 private static MethodNode find(ClassNode node,String name){return node.methods.stream().filter(m->m.name.equals(name)).findFirst().orElseThrow();}
 private static byte[]write(ClassNode node){ClassWriter writer=new ClassWriter(ClassWriter.COMPUTE_MAXS);node.accept(writer);return writer.toByteArray();}
 private record AlteredFrame(StackWalker.StackFrame original,int bytecode)implements StackWalker.StackFrame{public String getClassName(){return original.getClassName();}public String getMethodName(){return original.getMethodName();}public Class<?>getDeclaringClass(){return original.getDeclaringClass();}public java.lang.invoke.MethodType getMethodType(){return original.getMethodType();}public String getDescriptor(){return original.getDescriptor();}public int getByteCodeIndex(){return bytecode;}public String getFileName(){return original.getFileName();}public int getLineNumber(){return original.getLineNumber();}public boolean isNativeMethod(){return original.isNativeMethod();}public StackTraceElement toStackTraceElement(){return original.toStackTraceElement();}}
}
