/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin.weave;

import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.util.*;
import java.util.zip.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.objectweb.asm.*;
import org.objectweb.asm.tree.*;
import net.fabricmc.api.EnvType;
import net.forbric.api.Ecosystem;
import net.forbric.kernel.boot.*;
import net.forbric.kernel.mixin.NativeGameReferences;
import net.forbric.kernel.transform.LootTableEventBridgeInjector;

/** The original upstream helper bytecode executes, including mutable listeners, throw regions and holder iteration. */
class LootSourceCallbacksWeaveTest implements Opcodes {
    @TempDir Path work;
    private static final String SOURCE="net/fabricmc/fabric/mixin/loot/ReloadableServerRegistriesMixin.class";
    private ClassNode source()throws Exception{
        Path api=Path.of(System.getProperty("forbric.fabricApi",net.forbric.kernel.TestFixtures.fabricApi().toString()));net.forbric.kernel.TestFixtures.requireFiles(net.forbric.kernel.TestFixtures.Fixture.STAGED,"raw loot callback group",api);
        try(ZipFile outer=new ZipFile(api.toFile())){var module=outer.stream().filter(e->e.getName().startsWith("META-INF/jars/fabric-loot-api-v3-")).findFirst().orElseThrow();try(ZipInputStream inner=new ZipInputStream(outer.getInputStream(module))){for(var e=inner.getNextEntry();e!=null;e=inner.getNextEntry())if(e.getName().equals(SOURCE))return node(inner.readAllBytes());}}
        throw new AssertionError("missing original loot source");
    }
    @Test void thePrivateMemoIsClosedAndNoSourceNamesAdmitTheProjection()throws Exception{
        ClassNode source=source();var plan=LootSourceCallbacks.plan(source);assertNotNull(plan);
        ClassNode renamed=new ClassNode();source.accept(new org.objectweb.asm.commons.ClassRemapper(renamed,new org.objectweb.asm.commons.Remapper(){@Override public String map(String name){return name.equals(source.name)?"arbitrary/ClosedCallbacks":name;}}));
        assertNotNull(LootSourceCallbacks.plan(renamed));
        ClassNode helper=node(plan.helperBytes());assertTrue(helper.fields.isEmpty());
        assertTrue(helper.methods.stream().flatMap(m->Arrays.stream(m.instructions.toArray())).noneMatch(i->i instanceof FieldInsnNode f&&f.owner.equals(source.name)));
        assertTrue(helper.methods.stream().flatMap(m->Arrays.stream(m.instructions.toArray())).noneMatch(i->i instanceof MethodInsnNode c&&c.owner.equals("java/util/WeakHashMap")));
        assertTrue(helper.methods.stream().anyMatch(m->m.desc.contains("HolderLookup$Provider")&&m.instructions.size()>60));
    }
    @Test void anAdditionalOpsReadOrMemoEscapeKeepsTheSourceUnproved()throws Exception{
        ClassNode extraRead=source();MethodNode value=extraRead.methods.stream().filter(m->m.desc.startsWith("(Ljava/lang/Object;")).findFirst().orElseThrow();value.instructions.insert(new InsnNode(POP));value.instructions.insert(new VarInsnNode(ALOAD,2));assertNull(LootSourceCallbacks.plan(extraRead));
        ClassNode escaped=source();FieldNode memo=escaped.fields.getFirst();MethodNode escape=new MethodNode(ACC_PUBLIC|ACC_STATIC,"different","()Ljava/lang/Object;",null,null);escape.instructions.add(new FieldInsnNode(GETSTATIC,escaped.name,memo.name,memo.desc));escape.instructions.add(new InsnNode(ARETURN));escaped.methods.add(escape);assertNull(LootSourceCallbacks.plan(escaped));
    }
    @Test void anAlteredMemoProducerCleanupOrAdditionalInjectorCannotBeDeclaredEquivalent()throws Exception{
        ClassNode producer=source();MethodNode store=producer.methods.stream().filter(m->Arrays.stream(m.instructions.toArray()).anyMatch(i->i instanceof MethodInsnNode c&&c.owner.equals("java/util/WeakHashMap")&&c.name.equals("put"))).findFirst().orElseThrow();store.instructions.insert(new MethodInsnNode(INVOKESTATIC,"java/lang/System","nanoTime","()J",false));store.instructions.insert(new InsnNode(POP2));assertNull(LootSourceCallbacks.plan(producer));
        ClassNode cleanup=source();for(MethodNode m:cleanup.methods)for(AbstractInsnNode i:m.instructions)if(i instanceof MethodInsnNode c&&c.owner.equals("java/util/WeakHashMap")&&c.name.equals("remove"))c.name="get";assertNull(LootSourceCallbacks.plan(cleanup));
        ClassNode extra=source();MethodNode injector=extra.methods.stream().filter(m->m.visibleAnnotations!=null&&m.visibleAnnotations.stream().anyMatch(a->a.desc.endsWith("/Inject;"))).findFirst().orElseThrow();MethodNode added=new MethodNode(ACC_STATIC,"extra",injector.desc,null,null);added.visibleAnnotations=injector.visibleAnnotations;added.instructions.add(new InsnNode(RETURN));extra.methods.add(added);assertNull(LootSourceCallbacks.plan(extra));
    }
    @Test void onlyTheActuallyDefinedHelperTypedBridgeAndHostClosureProveTheReplacement()throws Exception{
        var plan=LootSourceCallbacks.plan(source());assertNotNull(plan);
        Path base=Path.of(System.getProperty("forbric.predicateBase",net.forbric.kernel.TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar").toString()));net.forbric.kernel.TestFixtures.requireFiles(net.forbric.kernel.TestFixtures.Fixture.STAGED,"verified native loot target",base);
        try(ZipFile jar=new ZipFile(base.toFile())){
            byte[] raw=bytes(jar,plan.targetName().replace('.','/')+".class"),host=new LootTableEventBridgeInjector().transform(plan.targetName(),raw,null);
            Path bridgePath=Path.of(System.getProperty("forbric.test.runtimeClasses","build/classes/java/runtime")).resolve("net/forbric/kernel/runtime/KernelLootBridge.class");
            net.forbric.kernel.TestFixtures.requireFiles(net.forbric.kernel.TestFixtures.Fixture.STAGED,"actual compiled typed loot seam",bridgePath);byte[] bridge=Files.readAllBytes(bridgePath);
            var nativeNode=new NativeGameReferences(path->bytes(jar,path)).get(Ecosystem.FABRIC,plan.targetName().replace('.','/'));assertNotNull(nativeNode);
            LootSourceContracts.reset();try{
                assertTrue(LootSourceContracts.offer(plan,path->path.equals("net/forbric/kernel/runtime/KernelLootBridge.class")?bridge:path.equals(plan.targetName().replace('.','/')+".class")?host:bytes(jar,path),nativeNode));assertFalse(LootSourceContracts.proved());
                LootSourceContracts.observeDefinition(plan.targetName(),host);assertFalse(LootSourceContracts.proved());LootSourceContracts.observeDefinition("net.forbric.kernel.runtime.KernelLootBridge",bridge);assertFalse(LootSourceContracts.proved());LootSourceContracts.observeDefinition(plan.helperName(),plan.helperBytes());assertFalse(LootSourceContracts.proved(),"the TABLE/registry key domain also needs its actual definitions");LootSourceContracts.observeDefinition("net.minecraft.world.level.storage.loot.LootDataType",bytes(jar,"net/minecraft/world/level/storage/loot/LootDataType.class"));LootSourceContracts.observeDefinition("net.minecraft.core.registries.Registries",bytes(jar,"net/minecraft/core/registries/Registries.class"));assertTrue(LootSourceContracts.proved());
                ClassNode altered=node(plan.helperBytes());MethodNode complete=altered.methods.stream().filter(m->m.name.equals("allLoaded")).findFirst().orElseThrow();complete.instructions.insert(new InsnNode(NOP));LootSourceContracts.observeDefinition(plan.helperName(),write(altered));assertFalse(LootSourceContracts.proved());
                LootSourceContracts.observeDefinition(plan.helperName(),plan.helperBytes());ClassNode extraInit=node(plan.helperBytes());MethodNode init=new MethodNode(ACC_STATIC,"<clinit>","()V",null,null);init.instructions.add(new InsnNode(RETURN));extraInit.methods.add(init);LootSourceContracts.observeDefinition(plan.helperName(),write(extraInit));assertFalse(LootSourceContracts.proved());
                assertFalse(LootSourceContracts.offer(plan,path->path.equals("net/forbric/kernel/runtime/KernelLootBridge.class")?bridge:path.equals(plan.targetName().replace('.','/')+".class")?raw:bytes(jar,path),nativeNode));
            }finally{LootSourceContracts.reset();}
        }
    }
    @Test void aliasesUnknownValuesAndChangedDomainDefinitionsKeepTheSourceUnproved()throws Exception{
        var plan=LootSourceCallbacks.plan(source());Path base=Path.of(System.getProperty("forbric.predicateBase",net.forbric.kernel.TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar").toString()));net.forbric.kernel.TestFixtures.requireFiles(net.forbric.kernel.TestFixtures.Fixture.STAGED,"native-indexed domain guard",base);
        try(ZipFile jar=new ZipFile(base.toFile())){
            byte[] host=new LootTableEventBridgeInjector().transform(plan.targetName(),bytes(jar,plan.targetName().replace('.','/')+".class"),null);Path bridgePath=Path.of(System.getProperty("forbric.test.runtimeClasses","build/classes/java/runtime")).resolve("net/forbric/kernel/runtime/KernelLootBridge.class");byte[] bridge=Files.readAllBytes(bridgePath);var nativeNode=new NativeGameReferences(path->bytes(jar,path)).get(Ecosystem.FABRIC,plan.targetName().replace('.','/'));
            String dataPath="net/minecraft/world/level/storage/loot/LootDataType.class";ClassNode aliases=node(bytes(jar,dataPath));MethodNode init=aliases.methods.stream().filter(m->m.name.equals("<clinit>")).findFirst().orElseThrow();for(AbstractInsnNode instruction:init.instructions)if(instruction instanceof FieldInsnNode f&&f.getOpcode()==GETSTATIC&&f.owner.equals("net/minecraft/core/registries/Registries")&&f.name.equals("PREDICATE"))f.name="LOOT_TABLE";byte[] aliased=write(aliases);
            java.util.function.Function<String,byte[]> normal=path->path.equals("net/forbric/kernel/runtime/KernelLootBridge.class")?bridge:path.equals(plan.targetName().replace('.','/')+".class")?host:bytes(jar,path);
            LootSourceContracts.reset();try{
                assertFalse(LootSourceContracts.offer(plan,path->path.equals(dataPath)?aliased:normal.apply(path),nativeNode),"another values member with the same registry key invalidates TABLE projection");
                ClassNode unknown=node(host);for(MethodNode method:unknown.methods)for(AbstractInsnNode instruction:method.instructions)if(instruction instanceof MethodInsnNode call&&call.owner.equals("net/minecraft/world/level/storage/loot/LootDataType")&&call.name.equals("values"))call.owner="different/ExtensibleTypes";byte[] extended=write(unknown);assertFalse(LootSourceContracts.offer(plan,path->path.equals(plan.targetName().replace('.','/')+".class")?extended:normal.apply(path),nativeNode),"the async graph must originate in the closed values method");
                assertTrue(LootSourceContracts.offer(plan,normal,nativeNode));LootSourceContracts.observeDefinition(plan.targetName(),host);LootSourceContracts.observeDefinition("net.forbric.kernel.runtime.KernelLootBridge",bridge);LootSourceContracts.observeDefinition(plan.helperName(),plan.helperBytes());LootSourceContracts.observeDefinition("net.minecraft.world.level.storage.loot.LootDataType",bytes(jar,dataPath));LootSourceContracts.observeDefinition("net.minecraft.core.registries.Registries",bytes(jar,"net/minecraft/core/registries/Registries.class"));assertTrue(LootSourceContracts.proved());
                LootSourceContracts.observeDefinition("net.minecraft.world.level.storage.loot.LootDataType",aliased);assertFalse(LootSourceContracts.proved(),"raw admission is not a final definition witness");
            }finally{LootSourceContracts.reset();}
        }
    }
    @Test void finalEvidenceCannotBeBorrowedFromAnotherLoaderWithTheSameClassNames()throws Exception{
        var plan=LootSourceCallbacks.plan(source());Path base=Path.of(System.getProperty("forbric.predicateBase",net.forbric.kernel.TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar").toString()));net.forbric.kernel.TestFixtures.requireFiles(net.forbric.kernel.TestFixtures.Fixture.STAGED,"same-loader evidence",base);
        class EqualLoader extends ClassLoader{EqualLoader(){super(null);}@Override public boolean equals(Object other){return other instanceof EqualLoader;}@Override public int hashCode(){return 1;}}
        ClassLoader actual=new EqualLoader(),foreign=new EqualLoader();
        try(ZipFile jar=new ZipFile(base.toFile())){
            byte[] host=new LootTableEventBridgeInjector().transform(plan.targetName(),bytes(jar,plan.targetName().replace('.','/')+".class"),null);Path bridgePath=Path.of(System.getProperty("forbric.test.runtimeClasses","build/classes/java/runtime")).resolve("net/forbric/kernel/runtime/KernelLootBridge.class");byte[] bridge=Files.readAllBytes(bridgePath);var original=new NativeGameReferences(path->bytes(jar,path)).get(Ecosystem.FABRIC,plan.targetName().replace('.','/'));
            java.util.function.Function<String,byte[]> reader=path->path.equals("net/forbric/kernel/runtime/KernelLootBridge.class")?bridge:path.equals(plan.targetName().replace('.','/')+".class")?host:bytes(jar,path);
            LootSourceContracts.reset();try{
                assertTrue(LootSourceContracts.offer(plan,reader,original,actual));
                Map<String,byte[]> witnesses=new LinkedHashMap<>();witnesses.put(plan.targetName(),host);witnesses.put("net.forbric.kernel.runtime.KernelLootBridge",bridge);witnesses.put("net.minecraft.world.level.storage.loot.LootDataType",bytes(jar,"net/minecraft/world/level/storage/loot/LootDataType.class"));witnesses.put("net.minecraft.core.registries.Registries",bytes(jar,"net/minecraft/core/registries/Registries.class"));
                witnesses.forEach((name,data)->LootSourceContracts.observeDefinition(actual,name,data));
                ClassNode changed=node(plan.helperBytes());changed.methods.stream().filter(m->m.name.equals("afterLoad")).findFirst().orElseThrow().instructions.insert(new InsnNode(NOP));LootSourceContracts.observeDefinition(actual,plan.helperName(),write(changed));assertFalse(LootSourceContracts.proved(actual));
                witnesses.forEach((name,data)->LootSourceContracts.observeDefinition(foreign,name,data));LootSourceContracts.observeDefinition(foreign,plan.helperName(),plan.helperBytes());assertFalse(LootSourceContracts.proved(actual),"foreign unchanged bytes cannot overwrite the actual loader's changed helper");assertFalse(LootSourceContracts.proved(foreign),"the source group is bound to its own loader");
                LootSourceContracts.observeDefinition(actual,plan.helperName(),plan.helperBytes());assertTrue(LootSourceContracts.proved(actual));
            }finally{LootSourceContracts.reset();}
        }
    }
    @Test void unrelatedDirectoryWeavesDoNotChangeTheRegistryKeyDomainButAKeyFactoryChangeDoes()throws Exception{
        var plan=LootSourceCallbacks.plan(source());Path base=Path.of(System.getProperty("forbric.predicateBase",net.forbric.kernel.TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar").toString()));net.forbric.kernel.TestFixtures.requireFiles(net.forbric.kernel.TestFixtures.Fixture.STAGED,"domain dependency closure",base);
        try(ZipFile jar=new ZipFile(base.toFile())){
            byte[] host=new LootTableEventBridgeInjector().transform(plan.targetName(),bytes(jar,plan.targetName().replace('.','/')+".class"),null);Path bridgePath=Path.of(System.getProperty("forbric.test.runtimeClasses","build/classes/java/runtime")).resolve("net/forbric/kernel/runtime/KernelLootBridge.class");byte[] bridge=Files.readAllBytes(bridgePath);var original=new NativeGameReferences(path->bytes(jar,path)).get(Ecosystem.FABRIC,plan.targetName().replace('.','/'));
            java.util.function.Function<String,byte[]> reader=path->path.equals("net/forbric/kernel/runtime/KernelLootBridge.class")?bridge:path.equals(plan.targetName().replace('.','/')+".class")?host:bytes(jar,path);
            LootSourceContracts.reset();try{
                assertTrue(LootSourceContracts.offer(plan,reader,original));LootSourceContracts.observeDefinition(plan.targetName(),host);LootSourceContracts.observeDefinition("net.forbric.kernel.runtime.KernelLootBridge",bridge);LootSourceContracts.observeDefinition(plan.helperName(),plan.helperBytes());LootSourceContracts.observeDefinition("net.minecraft.world.level.storage.loot.LootDataType",bytes(jar,"net/minecraft/world/level/storage/loot/LootDataType.class"));
                ClassNode directories=node(bytes(jar,"net/minecraft/core/registries/Registries.class"));for(MethodNode method:directories.methods)if(method.name.equals("tagsDirPath")||method.name.equals("elementsDirPath"))method.instructions.insert(new InsnNode(NOP));LootSourceContracts.observeDefinition(directories.name,write(directories));assertTrue(LootSourceContracts.proved(),"directory paths are not in the key construction or values domain closure");
                MethodNode factory=directories.methods.stream().filter(m->m.desc.equals("(Ljava/lang/String;)Lnet/minecraft/resources/ResourceKey;")).findFirst().orElseThrow();factory.instructions.insert(new InsnNode(NOP));LootSourceContracts.observeDefinition(directories.name,write(directories));assertFalse(LootSourceContracts.proved(),"a changed key factory remains unproved");
            }finally{LootSourceContracts.reset();}
        }
    }
    @Test void originalCallbacksRunOnceThroughTheRealTypedBridgeAndKeepExceptionsAndNativePriority()throws Exception{
        var plan=LootSourceCallbacks.plan(source());assertNotNull(plan);
        Map<String,String> sources=new LinkedHashMap<>();
        sources.put("net.minecraft.resources.Identifier","package net.minecraft.resources;public record Identifier(String value){}");
        sources.put("net.minecraft.resources.ResourceKey","package net.minecraft.resources;public record ResourceKey(Object registry,Object id){public static ResourceKey create(ResourceKey registry,Identifier id){return new ResourceKey(registry,id);}}");
        sources.put("net.minecraft.core.registries.Registries","package net.minecraft.core.registries;public class Registries{public static final net.minecraft.resources.ResourceKey LOOT_TABLE=new net.minecraft.resources.ResourceKey(null,\"loot\");}");
        sources.put("net.minecraft.core.HolderLookup","package net.minecraft.core;public interface HolderLookup{interface Provider{}}");
        sources.put("net.minecraft.resources.RegistryOps","package net.minecraft.resources;public class RegistryOps{}");
        sources.put("net.minecraft.core.Holder","package net.minecraft.core;public interface Holder<T>{class Reference<T>implements Holder<T>{final T value;public Reference(T v){value=v;}public T value(){return value;}}}");
        sources.put("net.minecraft.core.Registry","package net.minecraft.core;public interface Registry<T>{java.util.stream.Stream<Holder.Reference<T>>listElements();net.minecraft.resources.ResourceKey key();}");
        sources.put("net.minecraft.core.WritableRegistry","package net.minecraft.core;public interface WritableRegistry<T>extends Registry<T>{}");
        sources.put("net.minecraft.server.packs.resources.ResourceManager","package net.minecraft.server.packs.resources;public interface ResourceManager{}");
        sources.put("net.minecraft.world.level.storage.loot.LootDataType","package net.minecraft.world.level.storage.loot;public class LootDataType{public static final LootDataType TABLE=new LootDataType();}");
        sources.put("net.fabricmc.fabric.impl.loot.FabricLootTable","package net.fabricmc.fabric.impl.loot;public interface FabricLootTable{void fabric$setHolder(net.minecraft.core.Holder holder);}");
        sources.put("net.minecraft.world.level.storage.loot.LootTable","package net.minecraft.world.level.storage.loot;public class LootTable implements net.fabricmc.fabric.impl.loot.FabricLootTable{public String value;public net.minecraft.core.Holder holder;public LootTable(String v){value=v;}public void fabric$setHolder(net.minecraft.core.Holder h){if(!net.fabricmc.fabric.impl.loot.LootUtil.SOURCES.get().isEmpty())throw new AssertionError(\"binding before source clear\");audit.LootProbe.calls.add(\"holder\");if(audit.LootProbe.mode.equals(\"holderThrow\"))throw new IllegalStateException(\"holder failed\");holder=h;}public static class Builder{public static int woven;String value;public Builder(String v){value=v;}public LootTable build(){audit.LootProbe.calls.add(\"build\");return new LootTable(value);}}}");
        sources.put("net.fabricmc.fabric.api.loot.v3.FabricLootTableBuilder","package net.fabricmc.fabric.api.loot.v3;public interface FabricLootTableBuilder{static net.minecraft.world.level.storage.loot.LootTable.Builder copyOf(net.minecraft.world.level.storage.loot.LootTable table){audit.LootProbe.calls.add(\"copy\");return new net.minecraft.world.level.storage.loot.LootTable.Builder(table.value);}}");
        sources.put("net.fabricmc.fabric.api.loot.v3.LootTableSource","package net.fabricmc.fabric.api.loot.v3;public enum LootTableSource{DATA_PACK,REPLACED,VANILLA}");
        sources.put("net.fabricmc.fabric.impl.loot.LootUtil","package net.fabricmc.fabric.impl.loot;public class LootUtil{public static final ThreadLocal<java.util.Map<net.minecraft.resources.Identifier,net.fabricmc.fabric.api.loot.v3.LootTableSource>>SOURCES=ThreadLocal.withInitial(java.util.HashMap::new);}");
        sources.put("net.fabricmc.fabric.api.event.Event","package net.fabricmc.fabric.api.event;public class Event<T>{public T current;public T invoker(){return current;}}");
        sources.put("net.fabricmc.fabric.api.loot.v3.LootTableEvents","""
            package net.fabricmc.fabric.api.loot.v3;import net.minecraft.world.level.storage.loot.*;import net.minecraft.resources.*;import net.minecraft.core.*;import net.minecraft.server.packs.resources.*;import net.fabricmc.fabric.api.event.Event;
            public class LootTableEvents{public interface Replace{LootTable replaceLootTable(ResourceKey key,LootTable table,LootTableSource source,HolderLookup.Provider provider);}public interface Modify{void modifyLootTable(ResourceKey key,LootTable.Builder builder,LootTableSource source,HolderLookup.Provider provider);}public interface Loaded{void onLootTablesLoaded(ResourceManager resources,Registry registry);}public static final Event<Replace>REPLACE=new Event<>();public static final Event<Modify>MODIFY=new Event<>();public static final Event<Loaded>ALL_LOADED=new Event<>();}
            """);
        sources.put("net.neoforged.neoforge.event.EventHooks","package net.neoforged.neoforge.event;public class EventHooks{public static net.minecraft.world.level.storage.loot.LootTable loadLootTable(net.minecraft.core.HolderLookup.Provider p,net.minecraft.resources.Identifier id,net.minecraft.world.level.storage.loot.LootTable t){audit.LootProbe.calls.add(\"neo\");return audit.LootProbe.mode.equals(\"neoCancel\")?null:t;}}");
        sources.put("net.minecraftforge.event.ForgeEventFactory","package net.minecraftforge.event;public class ForgeEventFactory{public static net.minecraft.world.level.storage.loot.LootTable onLoadLootTable(net.minecraft.resources.Identifier id,net.minecraft.world.level.storage.loot.LootTable t){audit.LootProbe.calls.add(\"forge\");return audit.LootProbe.mode.equals(\"forgeCancel\")?null:t;}}");
        sources.put("net.minecraft.tags.TagLoader","package net.minecraft.tags;public class TagLoader{public static void loadTagsForRegistry(net.minecraft.server.packs.resources.ResourceManager r,net.minecraft.core.WritableRegistry registry){audit.LootProbe.calls.add(\"tags\");}}");
        sources.put("audit.LootProbe","""
            package audit;import java.util.*;import java.lang.invoke.*;import net.minecraft.resources.*;import net.minecraft.core.*;import net.minecraft.world.level.storage.loot.*;import net.fabricmc.fabric.api.loot.v3.*;import net.fabricmc.fabric.impl.loot.LootUtil;import net.forbric.kernel.boot.*;import net.forbric.kernel.runtime.KernelLootBridge;
            public class LootProbe{public static List<String>calls=new ArrayList<>();public static String mode;static HolderLookup.Provider provider=new HolderLookup.Provider(){};static Identifier id=new Identifier("table");
            public void run()throws Throwable{Class<?>helper=Class.forName("HELPER");var l=MethodHandles.publicLookup();var callbacks=new LootSourceCallbacks.Callbacks(l.findStatic(helper,"afterLoad",MethodType.methodType(Object.class,Object.class,Object.class,Object.class)),l.findStatic(helper,"allLoaded",MethodType.methodType(void.class,Object.class,Object.class)));LootTableEventDispatch.bind(getClass().getClassLoader());var field=LootTableEventDispatch.class.getDeclaredField("sourceCallbacks");field.setAccessible(true);field.set(null,callbacks);var state=LootTableEventDispatch.class.getDeclaredField("state");state.setAccessible(true);for(Object constant:state.getType().getEnumConstants())if(constant.toString().equals("PRESENT"))state.set(null,constant);KernelLootBridge.install();
             LootTableEvents.REPLACE.current=(key,table,source,p)->{calls.add("replace:"+source);if(p!=provider||!key.id().equals(id))throw new AssertionError("provider/id projection");if(mode.equals("replaceThrow"))throw new IllegalStateException("replace failed");return mode.equals("replaced")?new LootTable("replacement"):null;};
             LootTableEvents.MODIFY.current=(key,builder,source,p)->{calls.add("modify:"+source);if(p!=provider)throw new AssertionError("provider changed");if(mode.equals("modifyThrow"))throw new IllegalStateException("modify failed");};
             for(String test:new String[]{"plain","replaced","recorded","neoCancel","forgeCancel","replaceThrow","modifyThrow","mutable"}){mode=test;calls.clear();LootTable.Builder.woven=0;LootUtil.SOURCES.remove();if(test.equals("recorded"))LootUtil.SOURCES.get().put(id,LootTableSource.VANILLA);if(test.equals("mutable"))LootTableEvents.REPLACE.current=(key,table,source,p)->{calls.add("newReplace");return null;};try{LootTable out=KernelLootBridge.loadLootTable(provider,id,new LootTable("original"));System.out.println("[LootOriginal] mode="+test+" out="+(out==null?"null":out.value)+" calls="+calls+" woven="+LootTable.Builder.woven);}catch(IllegalStateException fail){System.out.println("[LootOriginal] mode="+test+" throw="+fail.getMessage()+" calls="+calls);}}
             LootTableEvents.ALL_LOADED.current=(resources,registry)->{calls.add("all");if(mode.equals("allThrow"))throw new IllegalStateException("all failed");};
             for(String test:new String[]{"all","allThrow","holderThrow"}){mode=test;calls.clear();LootUtil.SOURCES.get().put(id,LootTableSource.VANILLA);LootTable table=new LootTable("holder");Holder.Reference<LootTable>holder=new Holder.Reference<>(table);WritableRegistry<LootTable>registry=new WritableRegistry<>(){public java.util.stream.Stream<Holder.Reference<LootTable>>listElements(){return java.util.stream.Stream.of(holder);}public ResourceKey key(){return net.minecraft.core.registries.Registries.LOOT_TABLE;}};try{KernelLootBridge.loadTagsForRegistry(new net.minecraft.server.packs.resources.ResourceManager(){},registry);System.out.println("[LootOriginal] mode="+test+" calls="+calls+" holder="+(table.holder==holder)+" source="+LootUtil.SOURCES.get().size());}catch(IllegalStateException fail){System.out.println("[LootOriginal] mode="+test+" throw="+fail.getMessage()+" calls="+calls+" source="+LootUtil.SOURCES.get().size());}}
            }}
            """.replace("HELPER",plan.helperName().replace('/','.')));
        sources.put("audit.mixin.BuildObserver","package audit.mixin;import org.spongepowered.asm.mixin.Mixin;import org.spongepowered.asm.mixin.injection.*;import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;@Mixin(net.minecraft.world.level.storage.loot.LootTable.Builder.class)public class BuildObserver{@Inject(method=\"build\",at=@At(\"RETURN\"))private void observed(CallbackInfoReturnable<net.minecraft.world.level.storage.loot.LootTable>ci){net.minecraft.world.level.storage.loot.LootTable.Builder.woven++;}}");
        List<Path> files=new ArrayList<>();for(var e:sources.entrySet()){Path file=work.resolve("src").resolve(e.getKey().replace('.','/')+".java");Files.createDirectories(file.getParent());Files.writeString(file,e.getValue());files.add(file);}
        Path realBridge=Path.of("src/runtime/java/net/forbric/kernel/runtime/KernelLootBridge.java");if(!Files.exists(realBridge))realBridge=Path.of("forbric-kernel").resolve(realBridge);files.add(realBridge.toAbsolutePath());
        String config="loot-source.mixins.json";Path json=work.resolve(config);Files.writeString(json,"{\"required\":true,\"package\":\"audit.mixin\",\"mixins\":[\"BuildObserver\"]}");Path helper=work.resolve("helper.class");Files.write(helper,plan.helperBytes());
        Path fixture=WeaveHarness.fixture(work,"loot-source",files,Map.of(config,json,plan.helperName()+".class",helper),List.of("-g"));
        var on=WeaveHarness.run(work,"on",fixture,List.of(new WeaveHarness.Config(config,"lootcallbacks",Ecosystem.FABRIC)),List.of(),EnvType.SERVER,"audit.LootProbe","run",Map.of());
        for(String expected:List.of("mode=plain out=original calls=[neo, forge, replace:DATA_PACK, copy, modify:DATA_PACK, build] woven=1","mode=replaced out=replacement calls=[neo, forge, replace:DATA_PACK, copy, modify:REPLACED, build] woven=1","mode=recorded out=original calls=[neo, forge, replace:VANILLA, copy, modify:VANILLA, build] woven=1","mode=neoCancel out=null calls=[neo] woven=0","mode=forgeCancel out=null calls=[neo, forge] woven=0","mode=replaceThrow throw=replace failed calls=[neo, forge, replace:DATA_PACK]","mode=modifyThrow throw=modify failed calls=[neo, forge, replace:DATA_PACK, copy, modify:DATA_PACK]","mode=mutable out=original calls=[neo, forge, newReplace, copy, modify:DATA_PACK, build] woven=1","mode=all calls=[tags, all, holder] holder=true source=0","mode=allThrow throw=all failed calls=[tags, all] source=1","mode=holderThrow throw=holder failed calls=[tags, all, holder] source=0"))assertTrue(on.printed(expected),on.describe());
        WeaveHarness.assertWovenAndVerified(on,"net/minecraft/world/level/storage/loot/LootTable$Builder",fixture);
        var off=WeaveHarness.run(work,"off",fixture,List.of(new WeaveHarness.Config(config,"lootcallbacks",Ecosystem.FABRIC)),List.of(),EnvType.SERVER,"audit.LootProbe","run",Map.of(LootTableEventBridgeInjector.PROPERTY,"off"));assertTrue(off.printed("mode=plain out=original calls=[neo, forge] woven=0"),off.describe());assertTrue(off.printed("mode=all calls=[tags] holder=false source=1"),off.describe());
    }
    private static ClassNode node(byte[] bytes){ClassNode n=new ClassNode();new ClassReader(bytes).accept(n,ClassReader.EXPAND_FRAMES);return n;}
    private static byte[] write(ClassNode n){ClassWriter w=new ClassWriter(0);n.accept(w);return w.toByteArray();}
    private static byte[] bytes(ZipFile jar,String path){try{var e=jar.getEntry(path);return e==null?null:jar.getInputStream(e).readAllBytes();}catch(Exception e){throw new IllegalStateException(e);}}
}
