/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin.weave;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;import java.util.*;import java.util.zip.*;import java.security.*;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import org.objectweb.asm.*;import org.objectweb.asm.tree.*;
import net.fabricmc.api.EnvType;import net.forbric.api.Ecosystem;import net.forbric.kernel.TestFixtures;import net.forbric.kernel.mixin.*;
@net.forbric.kernel.transform.ExecutesInjector(CrossHostPredicateIslandInjector.class)
class MixinCrossHostPredicateIslandWeaveTest implements Opcodes{
 @TempDir Path work;
 static ClassNode node(byte[]b){ClassNode n=new ClassNode();new ClassReader(b).accept(n,0);return n;}
 static byte[]bytes(ClassNode n){ClassWriter w=new ClassWriter(0);n.accept(w);return w.toByteArray();}
 @Test void theWholeAdapterRunsTheOriginalModifierBeforeOneNativeEventAndKeepsItsOffControl()throws Exception{
 Path api=Path.of(System.getProperty("forbric.fabricApi",TestFixtures.fabricApi().toString())),base=Path.of(System.getProperty("forbric.predicateBase",TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar").toString()));TestFixtures.requireFiles(TestFixtures.Fixture.STAGED,"upstream drowning whole adapter",api,base);
 ClassNode source=null,nativeActor;try(ZipFile jar=new ZipFile(api.toFile())){var entry=jar.stream().filter(e->e.getName().startsWith("META-INF/jars/fabric-content-registries-v0-")).findFirst().orElseThrow();try(ZipInputStream in=new ZipInputStream(jar.getInputStream(entry))){for(var e=in.getNextEntry();e!=null;e=in.getNextEntry())if(e.getName().equals("net/fabricmc/fabric/mixin/content/registry/fluid/LivingEntityMixin.class"))source=node(in.readAllBytes());}}
 try(ZipFile jar=new ZipFile(base.toFile())){nativeActor=new NativeGameReferences(p->{try{var e=jar.getEntry(p);return e==null?null:jar.getInputStream(e).readAllBytes();}catch(Exception fail){throw new RuntimeException(fail);}}).get(Ecosystem.FABRIC,"net/minecraft/world/entity/LivingEntity");}assertNotNull(source);assertNotNull(nativeActor);
 source.methods.removeIf(m->!Set.of("<init>","customFluidDrowning","isEyeInFluid").contains(m.name));
        Map<String,String> code=new LinkedHashMap<>();
        code.put("net.minecraft.tags.TagKey","package net.minecraft.tags;public record TagKey(String id){}");
        code.put("net.minecraft.tags.FluidTags","package net.minecraft.tags;public class FluidTags{public static final TagKey WATER=new TagKey(\"water\");}");
        code.put("net.minecraft.world.level.material.Fluid","package net.minecraft.world.level.material;public class Fluid{}");
        code.put("net.minecraft.world.phys.Vec3","package net.minecraft.world.phys;public class Vec3{}");
        code.put("net.minecraft.core.BlockPos","package net.minecraft.core;public class BlockPos{public static BlockPos containing(double x,double y,double z){return new BlockPos();}}");
        code.put("net.minecraft.world.level.block.Block","package net.minecraft.world.level.block;public class Block{}");
        code.put("net.minecraft.world.level.block.Blocks","package net.minecraft.world.level.block;public class Blocks{public static final Block BUBBLE_COLUMN=new Block();}");
        code.put("net.minecraft.world.level.block.state.BlockState","package net.minecraft.world.level.block.state;public class BlockState{public boolean is(Object block){audit.DrownProbe.calls.add(\"bubble\");if(audit.DrownProbe.mode.equals(\"bubbleThrow\"))throw new IllegalStateException(\"bubble failed\");return audit.DrownProbe.mode.equals(\"bubble\");}}");
        code.put("net.minecraft.world.level.Level","package net.minecraft.world.level;public class Level{public net.minecraft.world.level.block.state.BlockState getBlockState(net.minecraft.core.BlockPos pos){return new net.minecraft.world.level.block.state.BlockState();}}");
        code.put("net.minecraft.server.level.ServerLevel","package net.minecraft.server.level;public class ServerLevel extends net.minecraft.world.level.Level{}");
        code.put("net.minecraft.world.effect.MobEffectUtil","package net.minecraft.world.effect;public class MobEffectUtil{public static boolean hasWaterBreathing(net.minecraft.world.entity.LivingEntity actor){audit.DrownProbe.calls.add(\"effect\");return audit.DrownProbe.mode.equals(\"effect\");}}");
        code.put("net.minecraft.world.entity.Entity","package net.minecraft.world.entity;public class Entity{}");
        code.put("net.fabricmc.fabric.impl.content.registry.fluid.InternalEntityFluidExtension","package net.fabricmc.fabric.impl.content.registry.fluid;public interface InternalEntityFluidExtension{java.util.Set<net.minecraft.tags.TagKey>fabric_api$getTouchedCustomFluids();}");
        code.put("net.fabricmc.fabric.api.registry.fluid.FluidBehavior","package net.fabricmc.fabric.api.registry.fluid;public interface FluidBehavior{boolean canDrownInFluid(net.minecraft.tags.TagKey tag,net.minecraft.world.entity.LivingEntity actor);}");
        code.put("net.fabricmc.fabric.impl.content.registry.fluid.EntityFluidInteractionRegistryImpl","package net.fabricmc.fabric.impl.content.registry.fluid;public class EntityFluidInteractionRegistryImpl{public static net.fabricmc.fabric.api.registry.fluid.FluidBehavior getFluidBehavior(net.minecraft.tags.TagKey tag){return(t,actor)->{audit.DrownProbe.calls.add(\"behavior:\"+tag.id());if(audit.DrownProbe.mode.equals(\"behaviorThrow\"))throw new IllegalStateException(\"behavior failed\");return !audit.DrownProbe.mode.equals(\"declined\");};}}");
        code.put("net.minecraft.world.entity.player.Abilities","package net.minecraft.world.entity.player;public class Abilities{public boolean invulnerable;}");
        code.put("net.minecraft.world.entity.player.Player","package net.minecraft.world.entity.player;public class Player extends net.minecraft.world.entity.LivingEntity{public Abilities getAbilities(){audit.DrownProbe.calls.add(\"abilities\");Abilities value=new Abilities();value.invulnerable=audit.DrownProbe.mode.equals(\"invulnerable\");return value;}}");
        code.put("net.minecraft.world.entity.LivingEntity","""
            package net.minecraft.world.entity;public class LivingEntity extends Entity implements net.fabricmc.fabric.impl.content.registry.fluid.InternalEntityFluidExtension{
             public net.minecraft.world.level.Level level(){return new net.minecraft.server.level.ServerLevel();}public double getX(){return 0;}public double getEyeY(){return 1;}public double getZ(){return 0;}
             public boolean isEyeInFluid(net.minecraft.tags.TagKey tag){audit.DrownProbe.calls.add("eye:"+tag.id());return tag.id().equals("water")?audit.DrownProbe.mode.equals("water"):!audit.DrownProbe.mode.equals("noEye");}
             public boolean canBreatheUnderwater(){audit.DrownProbe.calls.add("breathe");return audit.DrownProbe.mode.equals("breathe");}public java.util.Set<net.minecraft.tags.TagKey>fabric_api$getTouchedCustomFluids(){audit.DrownProbe.calls.add("touched");return new java.util.LinkedHashSet<>(java.util.List.of(new net.minecraft.tags.TagKey("custom")));}}
            """);

 code.put("net.neoforged.neoforge.fluids.FluidType","package net.neoforged.neoforge.fluids;public class FluidType{public boolean isAir(){audit.DrownProbe.calls.add(\"nativeAny\");return false;}public boolean canDrownIn(net.minecraft.world.entity.LivingEntity actor){audit.DrownProbe.calls.add(\"nativeDrown\");return false;}}");
 code.put("net.neoforged.neoforge.fluids.OwnedType","package net.neoforged.neoforge.fluids;public class OwnedType extends FluidType{public boolean canDrownIn(net.minecraft.world.entity.LivingEntity actor){audit.DrownProbe.calls.add(\"nativeDrown\");return false;}}");

 code.put("net.minecraft.core.Holder","package net.minecraft.core;public interface Holder{Object value();public static class Reference implements Holder{public Object value;public Reference(Object value){this.value=value;}public Object value(){if(value==null)throw new IllegalStateException(\"unbound holder\");return value;}}}");
 code.put("net.neoforged.neoforge.registries.DeferredHolder","package net.neoforged.neoforge.registries;public class DeferredHolder implements net.minecraft.core.Holder{private net.minecraft.core.Holder holder;public DeferredHolder(net.minecraft.core.Holder holder){this.holder=holder;}protected final void bind(boolean needed){if(holder!=null)return;audit.DrownProbe.calls.add(\"bind\");throw new IllegalStateException(\"unbound memo\");}public void unbind(){holder=null;}public Object value(){bind(true);if(holder==null)throw new IllegalStateException(\"missing memo\");return holder.value();}} ");
 code.put("net.neoforged.neoforge.common.NeoForgeMod","package net.neoforged.neoforge.common;public class NeoForgeMod{public static final net.minecraft.core.Holder.Reference REFERENCE=new net.minecraft.core.Holder.Reference(new net.neoforged.neoforge.fluids.FluidType());public static final net.minecraft.core.Holder WATER_TYPE=new net.neoforged.neoforge.registries.DeferredHolder(REFERENCE);}");
 code.put("net.neoforged.neoforge.fluids.InFluidPredicate","package net.neoforged.neoforge.fluids;public interface InFluidPredicate{boolean test(net.minecraft.world.entity.LivingEntity actor,FluidType type,double height);}");
 code.put("net.forbric.kernel.runtime.KernelFabricFluidBehaviors","package net.forbric.kernel.runtime;public class KernelFabricFluidBehaviors{public static boolean enabled(){return true;}public static boolean ownsNeoType(net.neoforged.neoforge.fluids.FluidType type){return type instanceof net.neoforged.neoforge.fluids.OwnedType;}}");
 code.put("net.forbric.kernel.runtime.KernelFabricTagViews","package net.forbric.kernel.runtime;public class KernelFabricTagViews{public static void begin(net.minecraft.world.entity.EntityFluidInteraction interaction,String key){}}");
 code.put("net.minecraft.world.entity.EntityFluidInteraction", """
 package net.minecraft.world.entity;public class EntityFluidInteraction{
 public static class Tracker{public boolean eyes=true;} public final java.util.Map<net.neoforged.neoforge.fluids.FluidType,Tracker>nativeMap=new java.util.LinkedHashMap<>();public final java.util.Map<Object,Object>sourceMap=new java.util.LinkedHashMap<>();public boolean ready=true;
 public EntityFluidInteraction(){nativeMap.put(new net.neoforged.neoforge.fluids.OwnedType(),new Tracker());}public void update(){}public void collect(){net.forbric.kernel.runtime.KernelFabricTagViews.begin(this,"test-physical");}
 public boolean query(LivingEntity actor,net.neoforged.neoforge.fluids.InFluidPredicate predicate){for(var entry:nativeMap.entrySet())if(entry.getValue().eyes&&predicate.test(actor,entry.getKey(),0))return true;return false;}}
 """);
 code.put("net.neoforged.neoforge.common.extensions.ILivingEntityExtension","package net.neoforged.neoforge.common.extensions;public interface ILivingEntityExtension{default net.minecraft.world.entity.LivingEntity self(){return (net.minecraft.world.entity.LivingEntity)this;}default boolean canDrownInFluidType(net.neoforged.neoforge.fluids.FluidType type){if(type==net.neoforged.neoforge.common.NeoForgeMod.WATER_TYPE.value())return !self().canBreatheUnderwater();return type.canDrownIn(self());}} ");
 code.put("net.minecraft.world.entity.LivingEntity", """
 package net.minecraft.world.entity;public class LivingEntity extends Entity implements net.fabricmc.fabric.impl.content.registry.fluid.InternalEntityFluidExtension,net.neoforged.neoforge.common.extensions.ILivingEntityExtension{
 public final net.minecraft.world.level.Level world=new net.minecraft.server.level.ServerLevel();public final EntityFluidInteraction interaction=new EntityFluidInteraction();
 public net.minecraft.world.level.Level level(){return world;}public EntityFluidInteraction getFluidInteraction(){return interaction;}public double getX(){return 0;}public double getEyeY(){return 1;}public double getZ(){return 0;}
 public boolean isEyeInFluid(net.minecraft.tags.TagKey tag){audit.DrownProbe.calls.add("eye:"+tag.id());return tag.id().equals("water")?audit.DrownProbe.mode.equals("water"):!audit.DrownProbe.mode.equals("noEye");}
 public boolean canBreatheUnderwater(){audit.DrownProbe.calls.add("breathe");return audit.DrownProbe.mode.equals("breathe");}public java.util.Set<net.minecraft.tags.TagKey>fabric_api$getTouchedCustomFluids(){audit.DrownProbe.calls.add("touched");return new java.util.LinkedHashSet<>(java.util.List.of(new net.minecraft.tags.TagKey("custom")));}
 public LivingEntity self(){return this;}public void baseTick(){net.neoforged.neoforge.common.CommonHooks.onLivingBreathe(this,(net.minecraft.server.level.ServerLevel)level(),4,1);}}
 """);
 code.put("net.neoforged.neoforge.event.entity.living.LivingBreatheEvent","package net.neoforged.neoforge.event.entity.living;public class LivingBreatheEvent{public final boolean can;public final int consume;public LivingBreatheEvent(net.minecraft.world.entity.LivingEntity actor,boolean can,int refill,int consume){this.can=can;this.consume=consume;audit.DrownProbe.calls.add(\"event:\"+can+\":\"+consume);}}");
 code.put("net.neoforged.neoforge.common.CommonHooks", """
 package net.neoforged.neoforge.common;public class CommonHooks{public static void onLivingBreathe(net.minecraft.world.entity.LivingEntity actor,net.minecraft.server.level.ServerLevel world,int refill,int consume){
 var interaction=actor.getFluidInteraction();boolean primary=!interaction.query(actor,(entity,type,height)->!type.isAir())||actor.level().getBlockState(net.minecraft.core.BlockPos.containing(actor.getX(),actor.getEyeY(),actor.getZ())).is(net.minecraft.world.level.block.Blocks.BUBBLE_COLUMN);boolean can=primary;
 if(!primary){if(!net.minecraft.world.effect.MobEffectUtil.hasWaterBreathing(actor)&&interaction.query(actor,(entity,type,height)->entity.canDrownInFluidType(type))&&!(actor instanceof net.minecraft.world.entity.player.Player player&&player.getAbilities().invulnerable)){}else{can=true;consume=0;}}
 var event=new net.neoforged.neoforge.event.entity.living.LivingBreatheEvent(actor,can,refill,consume);audit.DrownProbe.calls.add("air:"+event.can+":"+event.consume);}}
 """);
 code.put("audit.DrownProbe", """
 package audit;import java.util.*;import net.forbric.kernel.boot.*;public class DrownProbe{public static String mode;public static List<String>calls=new ArrayList<>();public void run()throws Throwable{
 net.neoforged.neoforge.common.NeoForgeMod.WATER_TYPE.value();var interactionClass=net.minecraft.world.entity.EntityFluidInteraction.class;try(var in=interactionClass.getResourceAsStream("/net/minecraft/world/entity/EntityFluidInteraction.class")){org.objectweb.asm.tree.ClassNode node=new org.objectweb.asm.tree.ClassNode();new org.objectweb.asm.ClassReader(in.readAllBytes()).accept(node,0);var update=node.methods.stream().filter(m->m.name.equals("update")).findFirst().orElseThrow();var witness=new DefinedMethodContracts.MethodContract(node.name,"update","()V",DefinedMethodContracts.fingerprint(update));KernelTagSourceContracts.register("test-physical",new KernelTagSourceContracts.Schema(node.name,"sourceMap","ready","net/minecraft/world/entity/EntityFluidInteraction$Tracker","net/minecraft/tags/TagKey",witness,List.of(witness),List.of(),Map.of(),List.of(),null,null));}
 for(String test:new String[]{"custom","noEye","declined","water","bubble","breathe","effect","invulnerable","behaviorThrow","bubbleThrow","notReady","nativeType","unboundHolder","unboundMemo"}){mode=test;calls.clear();if(test.equals("unboundHolder"))net.neoforged.neoforge.common.NeoForgeMod.REFERENCE.value=null;if(test.equals("unboundMemo")){net.neoforged.neoforge.common.NeoForgeMod.REFERENCE.value=new net.neoforged.neoforge.fluids.FluidType();((net.neoforged.neoforge.registries.DeferredHolder)net.neoforged.neoforge.common.NeoForgeMod.WATER_TYPE).unbind();}var actor=test.equals("invulnerable")?new net.minecraft.world.entity.player.Player():new net.minecraft.world.entity.LivingEntity();if(test.equals("notReady"))actor.interaction.ready=false;if(test.equals("nativeType")){actor.interaction.nativeMap.clear();actor.interaction.nativeMap.put(new net.neoforged.neoforge.fluids.FluidType(),new net.minecraft.world.entity.EntityFluidInteraction.Tracker());}try{actor.baseTick();System.out.println("[WholeDrown] mode="+test+" calls="+calls);}catch(IllegalStateException failure){System.out.println("[WholeDrown] mode="+test+" throw="+failure.getMessage()+" calls="+calls);}}}}
 """);
 List<Path>files=new ArrayList<>();for(var entry:code.entrySet()){Path file=work.resolve("src").resolve(entry.getKey().replace('.','/')+".java");Files.createDirectories(file.getParent());Files.writeString(file,entry.getValue());files.add(file);}Path runtime=Path.of("src/runtime/java/net/forbric/kernel/runtime/KernelFluidPredicateIslands.java");if(!Files.exists(runtime))runtime=Path.of("forbric-kernel").resolve(runtime);files.add(runtime);
 Path raw=work.resolve("upstream.class"),binary=work.resolve("native.bin"),index=work.resolve("index.tsv"),config=work.resolve("source.mixins.json");Files.write(raw,bytes(source));byte[]original=bytes(nativeActor);Files.write(binary,original);Files.writeString(index,"# forbric-native-reference-v1\n"+nativeActor.name+"\t"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(original))+"\n");Files.writeString(config,"{\"required\":true,\"compatibilityLevel\":\"JAVA_25\",\"package\":\"net.fabricmc.fabric.mixin.content.registry.fluid\",\"mixins\":[\"LivingEntityMixin\"],\"injectors\":{\"defaultRequire\":1}}");
 Path fixture=WeaveHarness.fixture(work,"whole",files,Map.of("source.mixins.json",config,source.name+".class",raw,"META-INF/forbric/native-reference/FABRIC/index.tsv",index,"META-INF/forbric/native-reference/FABRIC/"+nativeActor.name+".class.bin",binary),List.of("-g"));
 var configs=List.of(new WeaveHarness.Config("source.mixins.json","drowning-whole",Ecosystem.FABRIC));var chain=List.<Class<?extends net.forbric.kernel.transform.ClassTransformer>>of(CrossHostPredicateIslandInjector.class);
 var on=WeaveHarness.run(work,"on",fixture,configs,chain,EnvType.SERVER,"audit.DrownProbe","run",Map.of());
 for(String expected:List.of("mode=noEye calls=[eye:water, touched, eye:custom, event:true:1, air:true:1]","mode=declined calls=[eye:water, touched, eye:custom, behavior:custom, event:true:1, air:true:1]","mode=water calls=[eye:water, bubble, breathe, effect, event:false:1, air:false:1]","mode=bubble calls=[eye:water, touched, eye:custom, behavior:custom, bubble, event:true:1, air:true:1]","mode=breathe calls=[eye:water, touched, eye:custom, behavior:custom, bubble, breathe, event:true:0, air:true:0]","mode=invulnerable calls=[eye:water, touched, eye:custom, behavior:custom, bubble, breathe, effect, abilities, event:true:0, air:true:0]","mode=bubbleThrow throw=bubble failed calls=[eye:water, touched, eye:custom, behavior:custom, bubble]"))assertTrue(on.printed(expected),on.describe());
 assertTrue(on.printed("mode=custom calls=[eye:water, touched, eye:custom, behavior:custom, bubble, breathe, effect, event:false:1, air:false:1]"),on.describe());
 assertTrue(on.printed("mode=effect calls=[eye:water, touched, eye:custom, behavior:custom, bubble, breathe, effect, event:true:0, air:true:0]"),on.describe());
 assertTrue(on.printed("mode=behaviorThrow throw=behavior failed calls=[eye:water, touched, eye:custom, behavior:custom]"),on.describe());
 assertTrue(on.printed("mode=notReady calls=[nativeAny, bubble, effect, nativeDrown, event:true:0, air:true:0]"),on.describe());
 assertTrue(on.printed("mode=nativeType calls=[nativeAny, bubble, effect, nativeDrown, event:true:0, air:true:0]"),on.describe());
 assertTrue(on.printed("mode=unboundHolder throw=unbound holder calls=[nativeAny, bubble, effect]"),on.describe());assertTrue(on.printed("mode=unboundMemo throw=unbound memo calls=[nativeAny, bubble, effect, bind]"),on.describe());
 WeaveHarness.assertWovenAndVerified(on,"net/minecraft/world/entity/LivingEntity",fixture);WeaveHarness.assertWovenAndVerified(on,"net/neoforged/neoforge/common/CommonHooks",fixture);
 var off=WeaveHarness.run(work,"off",fixture,configs,chain,EnvType.SERVER,"audit.DrownProbe","run",Map.of(MixinCrossHostPredicateIsland.PROPERTY,"off"));assertTrue(off.printed("mode=custom calls=[nativeAny, bubble, effect, nativeDrown, event:true:0, air:true:0]"),off.describe());assertFalse(off.printed("behavior:custom"),off.describe());
 Path deferred=work.resolve("src/net/neoforged/neoforge/registries/DeferredHolder.java");String originalDeferred=Files.readString(deferred);
 Files.writeString(deferred,originalDeferred.replace("if(holder!=null)return;","audit.DrownProbe.calls.add(\"bind-effect\");if(holder!=null)return;"));Path effectFixture=WeaveHarness.fixture(work,"bound-effect",files,Map.of("source.mixins.json",config,source.name+".class",raw,"META-INF/forbric/native-reference/FABRIC/index.tsv",index,"META-INF/forbric/native-reference/FABRIC/"+nativeActor.name+".class.bin",binary),List.of("-g"));var effectRun=WeaveHarness.run(work,"bound-effect",effectFixture,configs,chain,EnvType.SERVER,"audit.DrownProbe","run",Map.of());assertTrue(effectRun.printed("mode=custom calls=[nativeAny, bubble, effect, bind-effect, nativeDrown, event:true:0, air:true:0]"),effectRun.describe());assertFalse(effectRun.printed("behavior:custom"),effectRun.describe());
 Files.writeString(deferred,originalDeferred.replace("protected final void bind", "protected void bind"));Path virtualFixture=WeaveHarness.fixture(work,"virtual-binder",files,Map.of("source.mixins.json",config,source.name+".class",raw,"META-INF/forbric/native-reference/FABRIC/index.tsv",index,"META-INF/forbric/native-reference/FABRIC/"+nativeActor.name+".class.bin",binary),List.of("-g"));var virtualRun=WeaveHarness.run(work,"virtual-binder",virtualFixture,configs,chain,EnvType.SERVER,"audit.DrownProbe","run",Map.of());assertTrue(virtualRun.printed("mode=custom calls=[nativeAny, bubble, effect, nativeDrown, event:true:0, air:true:0]"),virtualRun.describe());assertFalse(virtualRun.printed("behavior:custom"),virtualRun.describe());

 }
}
