/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin.weave;
import static org.junit.jupiter.api.Assertions.*;import java.nio.file.*;import java.util.*;import java.security.*;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import org.objectweb.asm.*;import org.objectweb.asm.tree.*;
import net.fabricmc.api.EnvType;import net.forbric.api.Ecosystem;import net.forbric.kernel.mixin.NativeTagSourceFacadeInjector;
@net.forbric.kernel.transform.ExecutesInjector(NativeTagSourceFacadeInjector.class)
class NativeTagSourceFacadeWeaveTest implements Opcodes{
 @TempDir Path work;
 @Test void aSourceTagIsKeptAcrossTheTypedFacadeWhileConcreteUnknownAndOffPathsStayNative()throws Exception{
  Map<String,String>code=new LinkedHashMap<>();
  code.put("net.neoforged.neoforge.fluids.FluidType","package net.neoforged.neoforge.fluids;public class FluidType{public final String id;public FluidType(String id){this.id=id;}}");
  code.put("fixture.Owned","package fixture;public class Owned extends net.neoforged.neoforge.fluids.FluidType{public Owned(String id){super(id);}}");
  code.put("fixture.Tag","package fixture;public record Tag(String id){}");
  code.put("fixture.Mapper","package fixture;public class Mapper{public static net.neoforged.neoforge.fluids.FluidType type(Tag tag){Probe.mapper++;return tag.id().equals(\"native\")?new net.neoforged.neoforge.fluids.FluidType(tag.id()):new Owned(tag.id());}}");
  code.put("net.forbric.kernel.runtime.KernelFabricFluidBehaviors","package net.forbric.kernel.runtime;public class KernelFabricFluidBehaviors{public static boolean enabled(){return true;}public static boolean ownsNeoType(net.neoforged.neoforge.fluids.FluidType type){return type instanceof fixture.Owned;}}");
  code.put("net.forbric.kernel.runtime.KernelFabricTagViews","package net.forbric.kernel.runtime;public class KernelFabricTagViews{public static boolean begin(Object container,String key){return false;}}");
  code.put("fixture.Box","package fixture;public class Box{public final java.util.Map<Object,Object>source=new java.util.LinkedHashMap<>();public boolean ready=true;public void update(){}public void marker(){net.forbric.kernel.runtime.KernelFabricTagViews.begin(this,\"facade-physical\");}public boolean tagged(Tag tag){Probe.source++;return tag.id().equals(\"second\");}public boolean typed(net.neoforged.neoforge.fluids.FluidType type){Probe.typed++;return false;}}");
  code.put("net.minecraft.fixture.TagFacade","package net.minecraft.fixture;public class TagFacade{public final fixture.Box box=new fixture.Box();public boolean legacy(fixture.Tag tag){return nativeResult(fixture.Mapper.type(tag));}public boolean nativeResult(net.neoforged.neoforge.fluids.FluidType type){return box.typed(type);}}");
  code.put("fixture.Concrete","package fixture;public class Concrete extends net.minecraft.fixture.TagFacade{public boolean nativeResult(net.neoforged.neoforge.fluids.FluidType type){Probe.override++;return true;}}");
  code.put("fixture.Activation","package fixture;public class Activation{public void touch(){}}");
  code.put("fixture.mixin.ActivationMixin","package fixture.mixin;@org.spongepowered.asm.mixin.Mixin(fixture.Activation.class)public class ActivationMixin{@org.spongepowered.asm.mixin.injection.Inject(method=\"touch\",at=@org.spongepowered.asm.mixin.injection.At(\"HEAD\"))private void before(org.spongepowered.asm.mixin.injection.callback.CallbackInfo ci){}}");
  code.put("fixture.Probe", """
   package fixture;import net.forbric.kernel.boot.*;public class Probe{public static int mapper,source,typed,override;public void run()throws Exception{
    new Activation().touch();try(var input=Box.class.getResourceAsStream("/fixture/Box.class")){org.objectweb.asm.tree.ClassNode node=new org.objectweb.asm.tree.ClassNode();new org.objectweb.asm.ClassReader(input.readAllBytes()).accept(node,0);var update=node.methods.stream().filter(m->m.name.equals("update")).findFirst().orElseThrow();var witness=new DefinedMethodContracts.MethodContract(node.name,"update","()V",DefinedMethodContracts.fingerprint(update));KernelTagSourceContracts.register("facade-physical",new KernelTagSourceContracts.Schema(node.name,"source","ready","fixture/Box","fixture/Tag",witness,java.util.List.of(witness),java.util.List.of(),java.util.Map.of(),java.util.List.of(),null,null));}
    for(String test:new String[]{"second","first","native","notReady","concrete","changedWitness"}){mapper=source=typed=override=0;var actor=test.equals("concrete")?new Concrete():new net.minecraft.fixture.TagFacade();if(test.equals("notReady"))actor.box.ready=false;if(test.equals("changedWitness")){try(var in=net.minecraft.fixture.TagFacade.class.getResourceAsStream("/net/minecraft/fixture/TagFacade.class")){org.objectweb.asm.tree.ClassNode changed=new org.objectweb.asm.tree.ClassNode();new org.objectweb.asm.ClassReader(in.readAllBytes()).accept(changed,0);changed.methods.stream().filter(m->m.name.equals("nativeResult")).findFirst().orElseThrow().instructions.insert(new org.objectweb.asm.tree.InsnNode(org.objectweb.asm.Opcodes.NOP));org.objectweb.asm.ClassWriter writer=new org.objectweb.asm.ClassWriter(0);changed.accept(writer);DefinedMethodContracts.observe(actor.getClass().getClassLoader(),net.minecraft.fixture.TagFacade.class.getName(),writer.toByteArray());}}
    boolean result=actor.legacy(new Tag(test.equals("first")||test.equals("native")?test:"second"));System.out.println("[TagFacade] mode="+test+" result="+result+" mapper="+mapper+" source="+source+" typed="+typed+" override="+override);}}}
   """);
  List<Path>files=new ArrayList<>();for(var e:code.entrySet()){Path file=work.resolve("src").resolve(e.getKey().replace('.','/')+".java");Files.createDirectories(file.getParent());Files.writeString(file,e.getValue());files.add(file);}Path runtime=Path.of("src/runtime/java/net/forbric/kernel/runtime/KernelTagFacadeSources.java");if(!Files.exists(runtime))runtime=Path.of("forbric-kernel").resolve(runtime);files.add(runtime);Path config=work.resolve("facade.mixins.json");Files.writeString(config,"{\"required\":true,\"compatibilityLevel\":\"JAVA_21\",\"package\":\"fixture.mixin\",\"mixins\":[\"ActivationMixin\"]}");Path seed=WeaveHarness.fixture(work,"seed",files,Map.of());byte[]nativeBytes;try(var jar=new java.util.zip.ZipFile(seed.toFile())){ClassNode nativeNode=new ClassNode();new ClassReader(jar.getInputStream(jar.getEntry("net/minecraft/fixture/TagFacade.class")).readAllBytes()).accept(nativeNode,0);var legacy=nativeNode.methods.stream().filter(m->m.name.equals("legacy")).findFirst().orElseThrow();legacy.instructions.clear();legacy.instructions.add(new VarInsnNode(ALOAD,0));legacy.instructions.add(new FieldInsnNode(GETFIELD,nativeNode.name,"box","Lfixture/Box;"));legacy.instructions.add(new VarInsnNode(ALOAD,1));legacy.instructions.add(new MethodInsnNode(INVOKEVIRTUAL,"fixture/Box","tagged","(Lfixture/Tag;)Z",false));legacy.instructions.add(new InsnNode(IRETURN));legacy.tryCatchBlocks.clear();legacy.localVariables=null;ClassWriter writer=new ClassWriter(ClassWriter.COMPUTE_MAXS);nativeNode.accept(writer);nativeBytes=writer.toByteArray();}
  Path binary=work.resolve("native.bin"),index=work.resolve("index.tsv");Files.write(binary,nativeBytes);Files.writeString(index,"# forbric-native-reference-v1\nnet/minecraft/fixture/TagFacade\t"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(nativeBytes))+"\n");String prefix="META-INF/forbric/native-reference/FABRIC/";Path fixture=WeaveHarness.fixture(work,"facade",files,Map.of("facade.mixins.json",config,prefix+"index.tsv",index,prefix+"net/minecraft/fixture/TagFacade.class.bin",binary));var configs=List.of(new WeaveHarness.Config("facade.mixins.json","facade-source",Ecosystem.FABRIC));var chain=List.<Class<?extends net.forbric.kernel.transform.ClassTransformer>>of(NativeTagSourceFacadeInjector.class);var on=WeaveHarness.run(work,"on",fixture,configs,chain,EnvType.SERVER,"fixture.Probe","run",Map.of());
  for(String expected:List.of("mode=second result=true mapper=1 source=1 typed=0 override=0","mode=first result=false mapper=1 source=1 typed=0 override=0","mode=native result=false mapper=1 source=0 typed=1 override=0","mode=notReady result=false mapper=1 source=0 typed=1 override=0","mode=concrete result=true mapper=1 source=0 typed=0 override=1","mode=changedWitness result=false mapper=1 source=0 typed=1 override=0"))assertTrue(on.printed(expected),on.describe());WeaveHarness.assertWovenAndVerified(on,"net/minecraft/fixture/TagFacade",fixture);
  var off=WeaveHarness.run(work,"off",fixture,configs,chain,EnvType.SERVER,"fixture.Probe","run",Map.of(NativeTagSourceFacadeInjector.PROPERTY,"off"));assertTrue(off.printed("mode=second result=false mapper=1 source=0 typed=1 override=0"),off.describe());
 }
}
