package net.forbric.kernel.mixin;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.MethodNode;

import net.forbric.api.Ecosystem;
import net.forbric.kernel.TestFixtures;
import net.forbric.kernel.TestFixtures.Fixture;

/**
 * Re-derives {@code carrier-renames.txt} — every vanilla body a carrier moved into a same-shaped method it added, which
 * the merged class still calls or, marked UNCALLED, a private one nothing calls, call by call — and asserts the shipped
 * table equals it. MixinRetarget's R3 moves a selector only along these rows, only for a mod of an ecosystem they name,
 * and only for anchors among their calls.
 *
 * <p>The references are the jars each kind of mod was compiled against: stock 26.2 for Fabric, MinecraftForge's and
 * NeoForge's patched clients for theirs (MinecraftForge's exactly as the merge read it, {@link TestFixtures#forgeMergeInput}).
 * A pair is tagged with an ecosystem only when that jar declares the method and not the renamed one, and the renamed
 * one is made of that jar's method ({@link CarrierRenames}); its rows are the calls and field accesses that moved, and
 * its kind says whether the renamed method carries the whole of that jar's body or a piece.
 */
class CarrierRenameCensusTest {
	private static final Path MERGED = TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar");
	private static final Path VANILLA = TestFixtures.vanillaJar();
	private static final Path FORGE = TestFixtures.forgeMergeInput();
	private static final Path NEOFORGE = TestFixtures.stagedRoot().resolve("neoforge-patched/patched-mc-neoforge-26.2.jar");

	@Test void theShippedTableIsExactlyWhatTheArtifactsSay() throws Exception {
		TreeSet<String> rows = derive();
		List<String> shipped = shipped();
		if (System.getenv("FORBRIC_WRITE_CARRIER_RENAMES") != null) {
			Files.writeString(Path.of("src/main/resources" + CarrierRenames.TABLE),
					"# Generated by CarrierRenameCensusTest (FORBRIC_WRITE_CARRIER_RENAMES=1): a body each listed ecosystem's own\n"
					+ "# jar has in <method>, which the merged base has in <renamed>, a same-shaped method the carrier added and the\n"
					+ "# merged class still calls. One row per call or field access that moved: the reference's <method> makes it\n"
					+ "# <count> times, the merged <method> less often, <renamed> too. RENAME: <renamed> makes every call and field\n"
					+ "# access of the reference's <method>, as often; PIECE: only part. LEFT: the merged <method> returns the piece's\n"
					+ "# result whenever it is an Either left. UNCALLED: <renamed> is private and nothing in its class or its nest\n"
					+ "# calls it. MixinRetarget's R3 moves a selector only along these rows, only for a mod of a listed ecosystem,\n"
					+ "# only when every anchor is a row's member and binds no more often than <count>, for a PIECE only a handler\n"
					+ "# that needs nothing but the call and the arguments, or cancels only with a left into a LEFT one, and into an\n"
					+ "# UNCALLED one only to bind where the body is: the injector never runs there, and is reported so.\n"
					+ "# <class>#<method> -> <renamed> : <call or field> x<count> | <kind> | <ecosystems>[ | LEFT | UNCALLED]\n"
					+ String.join("\n", rows) + "\n");
		}
		assertEquals(rows, new TreeSet<>(shipped), "carrier-renames.txt must equal what the staged jars say; "
				+ "regenerate with FORBRIC_WRITE_CARRIER_RENAMES=1 after a base rebuild");
		for (String row : shipped) assertNotNull(CarrierRenames.Row.parse(row), "unreadable row: " + row);
	}

	/**
	 * The method pairs behind the audited R3 moves, judged against the jars. The genuine renames are rows, for the
	 * ecosystems whose own jar still has the body where the mod looks, and so are Fabric API's own (NeoForge's HUD layers,
	 * the sleep lambda, the configuration it runs from handlePong, the tooltip tail). The five wrong targets are not.
	 */
	@Test void theAuditedMovesAreRowsExactlyWhenACarrierRenamedTheBody() throws Exception {
		Set<String> pairs = pairs(shipped());
		String entity = "net/minecraft/world/level/entity/PersistentEntitySectionManager#addEntity(Lnet/minecraft/world/level/entity/EntityAccess;Z)Z";
		assertTrue(pairs.contains(entity + " -> addEntityWithoutEvent(Lnet/minecraft/world/level/entity/EntityAccess;Z)Z | RENAME | FABRIC"),
				"MinecraftForge renamed it too, so only a Fabric mod still looks for the body in addEntity");
		assertTrue(pairs.contains("net/minecraft/world/inventory/AnvilMenu#createResult()V -> createResultInternal()V | PIECE | FABRIC,FORGE"),
				"NeoForge keeps a few of vanilla's calls in createResult itself");
		String tooltip = "net/minecraft/world/item/ItemStack#addDetailsToTooltip" + TOOLTIP;
		assertTrue(pairs.contains(tooltip + " -> addDetailsToTooltipTail" + TOOLTIP + " | PIECE | FABRIC,FORGE"));
		assertTrue(pairs.contains("net/minecraft/server/level/ServerPlayer#startSleepInBed(Lnet/minecraft/core/BlockPos;)"
				+ "Lcom/mojang/datafixers/util/Either; -> lambda$startSleepInBed$0(Lnet/minecraft/core/BlockPos;)"
				+ "Lcom/mojang/datafixers/util/Either; | PIECE | FABRIC,FORGE | LEFT"), "super.startSleepInBed stayed in the method");
		String configuration = "net/minecraft/server/network/ServerConfigurationPacketListenerImpl#startConfiguration()V -> runConfiguration()V";
		assertTrue(pairs.contains(configuration + " | RENAME | FABRIC"), "called from handlePong, not from the method itself");
		assertTrue(pairs.contains(configuration + " | PIECE | FORGE"), "MinecraftForge's own startConfiguration does more than NeoForge's body");
		String screen = "(Lnet/minecraft/client/gui/GuiGraphicsExtractor;IIIIIFFFLnet/minecraft/world/entity/LivingEntity;)V";
		assertTrue(pairs.contains("net/minecraft/client/gui/screens/inventory/InventoryScreen#extractEntityInInventoryFollowsMouse"
				+ screen + " -> renderEntityInInventoryFollowsAngle" + screen + " | PIECE | FABRIC,FORGE"), "the mouse angles stayed");
		for (String layer : List.of("extractHealthLevel", "extractArmorLevel", "extractFoodLevel", "extractAirLevel")) {
			assertTrue(pairs.contains("net/minecraft/client/gui/Hud#extractPlayerHealth(Lnet/minecraft/client/gui/GuiGraphicsExtractor;)V -> "
					+ layer + "(Lnet/minecraft/client/gui/GuiGraphicsExtractor;)V | PIECE | FABRIC,FORGE"), layer);
		}

		// NeoForge's renamed tooltip body is the body, and nothing calls it: a row marked UNCALLED, where a move binds and
		// never runs.
		assertTrue(pairs.contains(tooltip + " -> addDetailsToTooltipComponents" + TOOLTIP + " | PIECE | FABRIC,FORGE | UNCALLED"),
				"dead body");
		// Vanilla declares every one of these itself: same shape, different method.
		for (String wrong : List.of("net/minecraft/network/chat/Style#withColor(I)Lnet/minecraft/network/chat/Style; -> withShadowColor",
				"net/minecraft/world/entity/LivingEntity#updatingUsingItem()V -> releaseUsingItem",
				"net/minecraft/client/gui/screens/inventory/AbstractContainerScreen#checkHotbarKeyPressed(Lnet/minecraft/client/input/KeyEvent;)Z -> keyPressed",
				"net/minecraft/world/item/CreativeModeTabs#lambda$bootstrap$21(")) {
			assertFalse(pairs.stream().anyMatch(r -> r.startsWith(wrong)), wrong);
		}
	}

	/**
	 * The members are what the reference's method made — vanilla's for a Fabric mod, MinecraftForge's or NeoForge's own
	 * jar's for theirs — and the renamed one makes: the anchors of the audit's genuine moves are rows, and a call only the
	 * carrier's renamed body makes is not — an anchor on it missed on the mod's own game.
	 */
	@Test void aPairsRowsAreTheCallsThatMovedWithTheBody() throws Exception {
		List<String> shipped = shipped();
		String entity = "net/minecraft/world/level/entity/PersistentEntitySectionManager#addEntity(Lnet/minecraft/world/level/entity/EntityAccess;Z)Z"
				+ " -> addEntityWithoutEvent(Lnet/minecraft/world/level/entity/EntityAccess;Z)Z : ";
		for (String anchor : List.of("Lnet/minecraft/core/SectionPos;asLong(Lnet/minecraft/core/BlockPos;)J",
				"Lnet/minecraft/world/level/entity/Visibility;isTicking()Z")) {
			assertTrue(shipped.contains(entity + anchor + " x1 | RENAME | FABRIC"), anchor);
		}
		String tail = "net/minecraft/world/item/ItemStack#addDetailsToTooltip" + TOOLTIP + " -> addDetailsToTooltipTail" + TOOLTIP + " : ";
		assertTrue(shipped.contains(tail + "Lnet/minecraft/core/DefaultedRegistry;getKey(Ljava/lang/Object;)Lnet/minecraft/resources/Identifier;"
				+ " x1 | PIECE | FABRIC,FORGE"), "apoli's item-id anchor: vanilla's advanced tail");
		// The count is the reference method's own: runConfiguration reads the task field twice, as vanilla's startConfiguration did.
		String configuration = "net/minecraft/server/network/ServerConfigurationPacketListenerImpl#startConfiguration()V -> runConfiguration()V : ";
		assertTrue(shipped.contains(configuration + "Lnet/minecraft/server/network/ServerConfigurationPacketListenerImpl;synchronizeRegistriesTask:"
				+ "Lnet/minecraft/server/network/config/SynchronizeRegistriesTask; x2 | RENAME | FABRIC"));
		assertTrue(shipped.contains(configuration + "Lnet/minecraft/server/network/config/SynchronizeRegistriesTask;<init>(Ljava/util/List;"
				+ "Lnet/minecraft/core/LayeredRegistryAccess;)V x1 | RENAME | FABRIC"), "fabric-resource-loader's known-packs anchor, made once");
		// Everything the census reads of the four jars: no row names a call the reference's method never made.
		for (String row : shipped) {
			CarrierRenames.Row parsed = CarrierRenames.Row.parse(row);
			assertNotNull(parsed, row);
			assertFalse(parsed.member().startsWith("Lnet/neoforged/") || parsed.member().startsWith("Lnet/minecraftforge/"),
					"a carrier's own call moved nowhere: " + row);
		}
	}

	/**
	 * Exactly one pair is UNCALLED: NeoForge's renamed tooltip body, private, which neither its class nor any member of
	 * its nest calls. The census also finds four same-shaped renamed methods its class never calls itself, and leaves each
	 * out because it is not private, so another class may call it or it may be called virtually: KeyBindsScreen's
	 * keyReleased (the screen framework calls it on every key release), the configuration listener's vanillaStart,
	 * EnchantmentHelper's getTagEnchantmentLevel, and the item model collector's generateDefaultBlockModels.
	 */
	@Test void onlyNeoForgesRenamedTooltipBodyIsUncalled() throws Exception {
		Set<String> uncalled = new TreeSet<>();
		Set<String> all = new TreeSet<>();
		for (String row : shipped()) {
			CarrierRenames.Row parsed = CarrierRenames.Row.parse(row);
			assertNotNull(parsed, row);
			all.add(parsed.owner() + "#" + parsed.method() + " -> " + parsed.renamed());
			if (!parsed.called()) {
				assertEquals(CarrierRenames.Exit.NONE, parsed.exit(), row);
				uncalled.add(parsed.owner() + "#" + parsed.method() + " -> " + parsed.renamed());
			}
		}
		String tooltip = "net/minecraft/world/item/ItemStack#addDetailsToTooltip" + TOOLTIP + " -> addDetailsToTooltipComponents" + TOOLTIP;
		assertEquals(Set.of(tooltip), uncalled);
		TestFixtures.require(Fixture.STAGED, Files.isRegularFile(MERGED), MERGED + " required");
		try (ZipFile zip = new ZipFile(MERGED.toFile())) {
			ClassNode stack = read(zip, "net/minecraft/world/item/ItemStack.class");
			MethodNode renamed = CarrierHelpers.declared(stack, "addDetailsToTooltipComponents", TOOLTIP);
			assertNotNull(renamed);
			assertTrue((renamed.access & Opcodes.ACC_PRIVATE) != 0 && !CarrierRenames.called(stack, renamed), "private and uncalled");
			assertNotNull(CarrierRenames.neverRuns(stack, renamed, Ecosystem.FABRIC));
			assertNull(CarrierRenames.neverRuns(stack, renamed, Ecosystem.NEOFORGE), "NeoForge's own mods were compiled against it");
			assertNull(CarrierRenames.neverRuns(stack, CarrierHelpers.declared(stack, "addDetailsToTooltipTail", TOOLTIP), Ecosystem.FABRIC),
					"the tail is called");
		}
		for (String reachable : List.of("net/minecraft/client/gui/screens/options/controls/KeyBindsScreen#keyPressed(",
				"net/minecraft/server/network/ServerConfigurationPacketListenerImpl#startConfiguration()V -> vanillaStart",
				"net/minecraft/world/item/enchantment/EnchantmentHelper#getItemEnchantmentLevel(",
				"net/minecraft/client/data/models/ModelProvider$ItemInfoCollector#finalizeAndValidate()V -> generateDefaultBlockModels")) {
			assertFalse(all.stream().anyMatch(r -> r.startsWith(reachable)), reachable);
		}
	}

	/**
	 * Exactly one pair returns its piece's lefts: NeoForge's startSleepInBed hands its lambda's answer to
	 * EventHooks.canPlayerStartSleeping and returns it when it names a problem. Every other piece's method goes on after
	 * it — Hud.extractPlayerHealth calls the next HUD layer, addDetailsToTooltip and createResult return nothing.
	 */
	@Test void onlyTheSleepLambdaIsAPieceWhoseLeftsTheMethodReturns() throws Exception {
		Set<String> left = new TreeSet<>();
		for (String row : shipped()) {
			CarrierRenames.Row parsed = CarrierRenames.Row.parse(row);
			assertNotNull(parsed, row);
			if (parsed.exit() == CarrierRenames.Exit.LEFT) {
				assertEquals(CarrierRenames.Kind.PIECE, parsed.kind(), row);
				left.add(parsed.owner() + "#" + parsed.method() + " -> " + parsed.renamed());
			}
		}
		assertEquals(Set.of("net/minecraft/server/level/ServerPlayer#startSleepInBed(Lnet/minecraft/core/BlockPos;)Lcom/mojang/datafixers/util/Either;"
				+ " -> lambda$startSleepInBed$0(Lnet/minecraft/core/BlockPos;)Lcom/mojang/datafixers/util/Either;"), left);
	}

	/** {@code <head> | <kind> | <ecosystems>[ | <exit>]} of every pair in {@code rows}, one per pair, kind and ecosystems. */
	static Set<String> pairs(List<String> rows) {
		Set<String> pairs = new TreeSet<>();
		for (String row : rows) {
			int colon = row.indexOf(" : "), bar = row.indexOf(" | ");
			pairs.add(row.substring(0, colon) + row.substring(bar));
		}
		return pairs;
	}

	static final String TOOLTIP = "(Lnet/minecraft/world/item/Item$TooltipContext;Lnet/minecraft/world/item/component/TooltipDisplay;"
			+ "Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/item/TooltipFlag;Ljava/util/function/Consumer;)V";

	private static List<String> shipped() throws Exception {
		List<String> shipped = new ArrayList<>();
		try (InputStream in = CarrierRenames.class.getResourceAsStream(CarrierRenames.TABLE)) {
			assertNotNull(in, CarrierRenames.TABLE + " is missing");
			for (String line : new String(in.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
				if (!line.isBlank() && !line.startsWith("#")) shipped.add(line.trim());
			}
		}
		return shipped;
	}

	/** Every row the staged jars support, as the census writes it. */
	static TreeSet<String> derive() throws Exception {
		for (Path jar : List.of(MERGED, VANILLA, FORGE, NEOFORGE)) {
			// MinecraftForge's merge input is the launcher library's copy where the staged one is not the merge's build.
			Fixture kind = jar == VANILLA || jar == FORGE && FORGE.startsWith(TestFixtures.minecraftDir()) ? Fixture.MC_LIBRARIES : Fixture.STAGED;
			TestFixtures.require(kind, Files.isRegularFile(jar), jar + " required");
		}
		Map<Ecosystem, ZipFile> references = new LinkedHashMap<>();
		references.put(Ecosystem.FABRIC, new ZipFile(VANILLA.toFile()));
		references.put(Ecosystem.FORGE, new ZipFile(FORGE.toFile()));
		references.put(Ecosystem.NEOFORGE, new ZipFile(NEOFORGE.toFile()));
		TreeMap<String, Set<Ecosystem>> derived = new TreeMap<>();
		Set<String> lefts = new TreeSet<>(), uncalled = new TreeSet<>();
		try (ZipFile zip = new ZipFile(MERGED.toFile())) {
			for (ZipEntry entry : Collections.list(zip.entries())) {
				if (!entry.getName().endsWith(".class")) continue;
				ClassNode merged = read(zip, entry.getName());
				Map<MethodNode, Map<String, Integer>> members = new HashMap<>();
				for (Map.Entry<Ecosystem, ZipFile> reference : references.entrySet()) {
					ClassNode original = read(reference.getValue(), entry.getName());
					if (original == null) continue;
					for (Pair pair : pairs(merged, original, members, renamed -> calledInNest(zip, merged, renamed))) {
						Map<String, Integer> before = members(CarrierHelpers.declared(original, pair.method().name, pair.method().desc));
						String head = merged.name + "#" + pair.method().name + pair.method().desc + " -> " + pair.renamed().name + pair.renamed().desc;
						CarrierRenames.Kind kind = kind(members.get(pair.renamed()), before);
						boolean called = CarrierRenames.called(merged, pair.renamed());
						boolean left = called && kind == CarrierRenames.Kind.PIECE && CarrierRenames.returnsLefts(merged, pair.method(), pair.renamed());
						for (String member : moved(members.get(pair.renamed()), before, members.get(pair.method()))) {
							String key = head + " : " + member + " x" + before.get(member) + " | " + kind.name();
							derived.computeIfAbsent(key, k -> EnumSet.noneOf(Ecosystem.class)).add(reference.getKey());
							if (left) lefts.add(key);
							if (!called) uncalled.add(key);
						}
					}
				}
			}
		} finally {
			for (ZipFile reference : references.values()) reference.close();
		}
		TreeSet<String> rows = new TreeSet<>();
		derived.forEach((head, ecosystems) -> rows.add(head + " | " + String.join(",", ecosystems.stream().sorted().map(Enum::name).toList())
				+ (lefts.contains(head) ? " | " + CarrierRenames.Exit.LEFT.name() : "")
				+ (uncalled.contains(head) ? " | " + CarrierRenames.UNCALLED : "")));
		return rows;
	}

	/** RENAME when {@code renamed} makes every call and field access of the reference's method as often, else PIECE. */
	static CarrierRenames.Kind kind(Map<String, Integer> renamed, Map<String, Integer> before) {
		for (Map.Entry<String, Integer> member : before.entrySet()) {
			if (renamed.getOrDefault(member.getKey(), 0) < member.getValue()) return CarrierRenames.Kind.PIECE;
		}
		return CarrierRenames.Kind.RENAME;
	}

	/** The calls and field accesses that moved: the reference's method makes them, the merged one less often, {@code renamed} too. */
	static Set<String> moved(Map<String, Integer> renamed, Map<String, Integer> before, Map<String, Integer> mergedMethod) {
		Set<String> moved = new TreeSet<>();
		for (Map.Entry<String, Integer> member : before.entrySet()) {
			if (renamed.getOrDefault(member.getKey(), 0) > 0 && mergedMethod.getOrDefault(member.getKey(), 0) < member.getValue()) {
				moved.add(member.getKey());
			}
		}
		return moved;
	}

	record Pair(MethodNode method, MethodNode renamed) {
	}

	/**
	 * The (method, renamed) pairs of {@code merged} against one reference class: {@code renamed} is a same-shaped method
	 * the reference does not declare, called by the merged class, and made of the reference's {@code method}
	 * ({@link #madeOf}). Then the ambiguous are dropped, since a move along any of them would be a guess: a renamed
	 * method made of two of the reference's methods (lambdas the carrier renumbered, each a line of the same few calls);
	 * two renamed methods of one method that make exactly the same calls (copies); and, of several renamed methods of
	 * one method, any the merged method does not call itself — the pieces of a split are what it dispatches to.
	 */
	static List<Pair> pairs(ClassNode merged, ClassNode original, Map<MethodNode, Map<String, Integer>> members,
			java.util.function.Predicate<MethodNode> calledInNest) {
		List<Pair> found = new ArrayList<>(), dead = new ArrayList<>();
		for (MethodNode renamed : merged.methods) {
			if (!bodied(renamed) || CarrierHelpers.declared(original, renamed.name, renamed.desc) != null) continue;
			boolean called = CarrierRenames.called(merged, renamed);
			// Dead only where nothing else can call it: a private method no other member of its nest calls either.
			// keyReleased or a public static helper may well be called from another class, or virtually.
			if (!called && ((renamed.access & Opcodes.ACC_PRIVATE) == 0 || calledInNest.test(renamed))) continue;
			for (MethodNode method : merged.methods) {
				if (method == renamed || !bodied(method) || !method.desc.equals(renamed.desc)
						|| ((method.access ^ renamed.access) & Opcodes.ACC_STATIC) != 0) continue;
				MethodNode before = CarrierHelpers.declared(original, method.name, method.desc);
				if (before == null || !bodied(before)) continue;
				if (madeOf(members.computeIfAbsent(renamed, CarrierRenameCensusTest::members), members(before),
						members.computeIfAbsent(method, CarrierRenameCensusTest::members))) {
					(called ? found : dead).add(new Pair(method, renamed));
				}
			}
		}
		List<Pair> kept = unambiguous(found, found, members);
		Map<MethodNode, Integer> homes = new HashMap<>();
		for (Pair pair : kept) homes.merge(pair.method(), 1, Integer::sum);
		kept.removeIf(pair -> homes.get(pair.method()) > 1 && !CarrierRenames.calls(merged, pair.method(), pair.renamed()));
		// A body the carrier renamed and nothing calls: kept apart, so the rules above judge the called ones exactly as
		// before. One per method, and none that copies a called one or another dead one: which would be a guess.
		List<Pair> keptDead = unambiguous(dead, java.util.stream.Stream.concat(found.stream(), dead.stream()).toList(), members);
		Map<MethodNode, Integer> deadHomes = new HashMap<>();
		for (Pair pair : keptDead) deadHomes.merge(pair.method(), 1, Integer::sum);
		keptDead.removeIf(pair -> deadHomes.get(pair.method()) > 1);
		kept.addAll(keptDead);
		return kept;
	}

	/** Whether a class nested with {@code merged} (its nest host or a nest member) calls its method {@code renamed}. */
	private static boolean calledInNest(ZipFile zip, ClassNode merged, MethodNode renamed) {
		Set<String> nest = new TreeSet<>();
		if (merged.nestHostClass != null) nest.add(merged.nestHostClass);
		if (merged.nestMembers != null) nest.addAll(merged.nestMembers);
		for (String name : nest) {
			if (name.equals(merged.name)) continue;
			try {
				ClassNode other = read(zip, name + ".class");
				if (other != null && other.methods != null) {
					for (MethodNode method : other.methods) {
						if (method.instructions == null) continue;
						for (AbstractInsnNode insn : method.instructions) {
							if (insn instanceof org.objectweb.asm.tree.MethodInsnNode call && call.owner.equals(merged.name)
									&& call.name.equals(renamed.name) && call.desc.equals(renamed.desc)) return true;
							if (insn instanceof org.objectweb.asm.tree.InvokeDynamicInsnNode indy) {
								for (Object arg : indy.bsmArgs) {
									if (arg instanceof org.objectweb.asm.Handle h && h.getOwner().equals(merged.name)
											&& h.getName().equals(renamed.name) && h.getDesc().equals(renamed.desc)) return true;
								}
							}
						}
					}
				}
			} catch (Exception unreadable) {
				return true;
			}
		}
		return false;
	}

	/**
	 * The pairs of {@code pairs} whose renamed method is made of one method only and copies no other renamed method of it
	 * among {@code all}.
	 */
	private static List<Pair> unambiguous(List<Pair> pairs, List<Pair> all, Map<MethodNode, Map<String, Integer>> members) {
		Map<MethodNode, Integer> origins = new HashMap<>();
		for (Pair pair : all) origins.merge(pair.renamed(), 1, Integer::sum);
		List<Pair> kept = new ArrayList<>();
		for (Pair pair : pairs) {
			if (origins.get(pair.renamed()) != 1) continue;
			boolean copy = false;
			for (Pair other : all) {
				if (other.renamed() != pair.renamed() && other.method() == pair.method()
						&& members.get(other.renamed()).equals(members.get(pair.renamed()))) copy = true;
			}
			if (!copy) kept.add(pair);
		}
		return kept;
	}

	/**
	 * Whether {@code renamed} is made of the reference's {@code before}: of the calls and field accesses of whichever of
	 * the two makes fewer, at least half are the other's too (a whole body renamed, or one piece of a split), at least
	 * two of them (one shared call is a coincidence, not a body), and some of those the merged method no longer makes
	 * (the body left it).
	 */
	static boolean madeOf(Map<String, Integer> renamed, Map<String, Integer> before, Map<String, Integer> mergedMethod) {
		int smaller = Math.min(total(renamed), total(before));
		if (smaller == 0) return false;
		int shared = 0, left = 0;
		for (Map.Entry<String, Integer> member : renamed.entrySet()) {
			int both = Math.min(member.getValue(), before.getOrDefault(member.getKey(), 0));
			shared += both;
			left += Math.max(0, both - mergedMethod.getOrDefault(member.getKey(), 0));
		}
		return shared >= 2 && 2 * shared >= smaller && left > 0;
	}

	private static int total(Map<String, Integer> members) {
		int total = 0;
		for (int count : members.values()) total += count;
		return total;
	}

	/** {@code method}'s calls and field accesses, with how often it makes each. */
	static Map<String, Integer> members(MethodNode method) {
		Map<String, Integer> out = new HashMap<>();
		for (AbstractInsnNode insn : method.instructions) {
			String member = CarrierHelpers.member(insn);
			if (member != null) out.merge(member, 1, Integer::sum);
		}
		return out;
	}

	private static boolean bodied(MethodNode method) {
		return !method.name.startsWith("<") && (method.access & Opcodes.ACC_BRIDGE) == 0 && method.instructions != null
				&& method.instructions.size() > 0;
	}

	private static ClassNode read(ZipFile zip, String name) throws Exception {
		ZipEntry entry = zip.getEntry(name);
		if (entry == null) return null;
		try (InputStream in = zip.getInputStream(entry)) {
			ClassNode node = new ClassNode();
			new ClassReader(in.readAllBytes()).accept(node, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
			return node;
		}
	}
}
