/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.TreeSet;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import net.forbric.api.Ecosystem;
import net.forbric.kernel.TestFixtures;
import net.forbric.kernel.TestFixtures.Fixture;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.LocalVariableNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

/**
 * Re-derives {@code carrier-twins.txt} — every vanilla method the merged base keeps but nothing in the merged game calls
 * ({@code uncalled-methods.txt}), whose class has one overload the carrier added in its place — and asserts the shipped
 * table equals it.
 *
 * <p>A row is written only when the move is PROVABLE, because {@link MixinTwinRebind} hands a mod's handler its arguments
 * along it, and a row that is a guess hands it the wrong object without a word:
 * <ul>
 *   <li>vanilla's method is no carrier stub (those are {@link MixinStubRebind}'s, which forward to their delegate);</li>
 *   <li>the class declares exactly one other method of that name with the same return type and static-ness and a body,
 *       taking more parameters, among them each of vanilla's — matched one to one by local variable name and type;</li>
 *   <li>every method the row's ecosystems call vanilla's from, as the merged base declares it, calls that overload, and
 *       at least one does: the merged game calls the overload where vanilla called vanilla's.</li>
 * </ul>
 */
class CarrierTwinCensusTest {
	private static final Path MERGED = TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar");

	@Test void theShippedTableIsExactlyWhatTheArtifactsSay() throws Exception {
		TestFixtures.require(Fixture.STAGED, Files.isRegularFile(MERGED), "merged base required");
		java.util.Set<String> needed = new java.util.HashSet<>();
		for (MergedBaseUncalledMethods.Row uncalled : MergedBaseUncalledMethods.rows()) {
			needed.add(uncalled.owner());
			for (String caller : uncalled.callers()) needed.add(caller.substring(0, caller.indexOf('#')));
		}
		Map<String, ClassNode> merged = read(MERGED, needed);
		TreeSet<String> rows = new TreeSet<>();
		for (MergedBaseUncalledMethods.Row uncalled : MergedBaseUncalledMethods.rows()) {
			String row = twin(uncalled, merged);
			if (row != null) rows.add(row);
		}
		assertTrue(rows.contains("net/minecraft/client/renderer/block/ModelBlockRenderer#shouldRenderFace("
				+ "Lnet/minecraft/client/renderer/block/BlockAndTintGetter;Lnet/minecraft/world/level/block/state/BlockState;"
				+ "Lnet/minecraft/core/Direction;Lnet/minecraft/core/BlockPos;)Z -> (Lnet/minecraft/client/renderer/block/"
				+ "BlockAndTintGetter;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;"
				+ "Lnet/minecraft/core/Direction;Lnet/minecraft/core/BlockPos;)Z | 0,2,3,4 | FABRIC,FORGE"),
				"the row LiquidBounce's X-Ray face test needs: " + rows);
		List<String> shipped = new ArrayList<>();
		try (InputStream in = MixinTwinRebind.class.getResourceAsStream(MixinTwinRebind.TABLE)) {
			assertNotNull(in, MixinTwinRebind.TABLE + " is missing");
			for (String line : new String(in.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
				if (!line.isBlank() && !line.startsWith("#")) shipped.add(line.trim());
			}
		}
		if (System.getenv("FORBRIC_WRITE_CARRIER_TWINS") != null) {
			Path out = Path.of("src/main/resources" + MixinTwinRebind.TABLE);
			Files.writeString(out, "# Generated by CarrierTwinCensusTest (FORBRIC_WRITE_CARRIER_TWINS=1): a vanilla method the merged base keeps\n"
					+ "# and nothing in the merged game calls (uncalled-methods.txt), no carrier stub, whose class declares one other\n"
					+ "# method of that name -- same return type and static-ness, more parameters, each of vanilla's matched 1:1 by local\n"
					+ "# variable name and type -- that every listed caller calls in the merged base. MixinTwinRebind moves an injector\n"
					+ "# only along these rows, and only for a mod of a listed ecosystem.\n"
					+ "# <class>#<name><vanilla descriptor> -> <overload descriptor> | <overload index of each vanilla parameter> | <ecosystems>\n"
					+ String.join("\n", rows) + "\n");
		}
		assertEquals(rows, new TreeSet<>(shipped), "carrier-twins.txt must equal what the staged merged base and "
				+ "uncalled-methods.txt say; regenerate with FORBRIC_WRITE_CARRIER_TWINS=1 after a base rebuild");
		for (String row : shipped) assertNotNull(MixinTwinRebind.Row.parse(row), "the rebind must accept every shipped row: " + row);
	}

	/** The row for one uncalled method, or null when it has no provable twin. */
	static String twin(MergedBaseUncalledMethods.Row uncalled, Map<String, ClassNode> merged) {
		String method = uncalled.method();
		if (method.startsWith("lambda$") || method.startsWith("<")) return null;
		ClassNode owner = merged.get(uncalled.owner());
		if (owner == null) return null;
		int paren = method.indexOf('(');
		String name = method.substring(0, paren), desc = method.substring(paren);
		String head = uncalled.owner() + "#" + method + " -> ";
		for (String stub : MixinStubRebind.carrierStubs().keySet()) if (stub.startsWith(head)) return null;
		MethodNode vanilla = null;
		List<MethodNode> others = new ArrayList<>();
		for (MethodNode m : owner.methods) {
			if (!m.name.equals(name)) continue;
			if (m.desc.equals(desc)) vanilla = m; else others.add(m);
		}
		if (vanilla == null) return null;
		MethodNode overload = null;
		int[] positions = null;
		for (MethodNode m : others) {
			int[] matched = embedding(vanilla, m);
			if (matched == null) continue;
			if (overload != null) return null;   // two overloads take vanilla's parameters: which one is not provable
			overload = m;
			positions = matched;
		}
		if (overload == null) return null;
		int callers = 0;
		for (String caller : uncalled.callers()) {
			int hash = caller.indexOf('#');
			ClassNode callerOwner = merged.get(caller.substring(0, hash));
			MethodNode callerMethod = callerOwner == null ? null : declared(callerOwner, caller.substring(hash + 1));
			if (callerMethod == null) continue;
			if (!calls(callerMethod, overload)) return null;
			callers++;
		}
		if (callers == 0) return null;
		StringJoiner joined = new StringJoiner(",");
		for (int p : positions) joined.add(Integer.toString(p));
		StringJoiner ecosystems = new StringJoiner(",");
		for (Ecosystem e : Ecosystem.values()) if (uncalled.ecosystems().contains(e)) ecosystems.add(e.name());
		return uncalled.owner() + "#" + method + " -> " + overload.desc + " | " + joined + " | " + ecosystems;
	}

	/**
	 * Where each of vanilla's parameters is among the overload's, or null unless the overload has the same return type and
	 * static-ness, a body, more parameters, and each of vanilla's matches exactly one of them by local variable name and type.
	 */
	static int[] embedding(MethodNode vanilla, MethodNode overload) {
		if (((vanilla.access ^ overload.access) & Opcodes.ACC_STATIC) != 0) return null;
		if ((overload.access & Opcodes.ACC_ABSTRACT) != 0 || overload.instructions == null || overload.instructions.size() == 0) return null;
		if (!Type.getReturnType(vanilla.desc).equals(Type.getReturnType(overload.desc))) return null;
		Type[] from = Type.getArgumentTypes(vanilla.desc), to = Type.getArgumentTypes(overload.desc);
		if (to.length <= from.length) return null;
		String[] fromNames = parameterNames(vanilla), toNames = parameterNames(overload);
		if (fromNames == null || toNames == null) return null;
		int[] positions = new int[from.length];
		boolean[] taken = new boolean[to.length];
		for (int i = 0; i < from.length; i++) {
			int found = -1;
			for (int j = 0; j < to.length; j++) {
				if (!to[j].equals(from[i]) || !toNames[j].equals(fromNames[i])) continue;
				if (found >= 0) return null;
				found = j;
			}
			if (found < 0 || taken[found]) return null;
			taken[found] = true;
			positions[i] = found;
		}
		return positions;
	}

	/** Whether {@code caller} calls {@code overload}, by name and descriptor (through its class or a subtype). */
	private static boolean calls(MethodNode caller, MethodNode overload) {
		if (caller.instructions == null) return false;
		for (AbstractInsnNode insn : caller.instructions) {
			if (insn instanceof MethodInsnNode call && call.name.equals(overload.name) && call.desc.equals(overload.desc)) return true;
		}
		return false;
	}

	private static MethodNode declared(ClassNode node, String nameAndDesc) {
		for (MethodNode m : node.methods) if ((m.name + m.desc).equals(nameAndDesc)) return m;
		return null;
	}

	/** Each parameter's name from the local variable table, or null when the table does not name every one. */
	private static String[] parameterNames(MethodNode method) {
		if (method.localVariables == null) return null;
		Type[] params = Type.getArgumentTypes(method.desc);
		String[] names = new String[params.length];
		int slot = (method.access & Opcodes.ACC_STATIC) != 0 ? 0 : 1;
		for (int i = 0; i < params.length; i++) {
			for (LocalVariableNode local : method.localVariables) {
				if (local.index == slot && local.desc.equals(params[i].getDescriptor())
						&& method.instructions.indexOf(local.start) <= firstRealInstruction(method)) {
					names[i] = local.name;
				}
			}
			if (names[i] == null) return null;
			slot += params[i].getSize();
		}
		return names;
	}

	private static int firstRealInstruction(MethodNode method) {
		for (int i = 0; i < method.instructions.size(); i++) if (method.instructions.get(i).getOpcode() >= 0) return i;
		return method.instructions.size();
	}

	private static Map<String, ClassNode> read(Path jar, java.util.Set<String> names) throws Exception {
		Map<String, ClassNode> out = new HashMap<>();
		try (ZipFile zip = new ZipFile(jar.toFile())) {
			for (ZipEntry entry : java.util.Collections.list(zip.entries())) {
				String entryName = entry.getName();
				if (!entryName.endsWith(".class") || !names.contains(entryName.substring(0, entryName.length() - 6))) continue;
				ClassNode node = new ClassNode();
				new ClassReader(zip.getInputStream(entry).readAllBytes()).accept(node, ClassReader.SKIP_FRAMES);
				out.put(node.name, node);
			}
		}
		return out;
	}
}
