package net.forbric.kernel.mixin;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import net.forbric.kernel.TestFixtures;
import net.forbric.kernel.TestFixtures.Fixture;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

import net.forbric.api.Ecosystem;

/**
 * Re-derives {@code carrier-helpers.txt} — every call a method made in an ecosystem's own jar that the merged base
 * makes in a helper the carrier added — and asserts the shipped table equals it. MixinRetarget moves an injector only
 * along a row here, and only for a mod of an ecosystem the row names.
 *
 * <p>The references are the jars each kind of mod was compiled against: stock 26.2 for Fabric, MinecraftForge's and
 * NeoForge's patched clients for theirs. A row is tagged with an ecosystem only when that jar makes the call exactly
 * once in the method and does not itself declare the helper, so a NeoForge mod — built against the split — is never
 * moved off the shape it expects.
 */
class CarrierHelperCensusTest {
	private static final Path MERGED = TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar");
	private static final Path VANILLA = TestFixtures.vanillaJar();
	private static final Path FORGE = TestFixtures.stagedRoot().resolve("forge-patched/patched-mc-forge-26.2.jar");
	private static final Path NEOFORGE = TestFixtures.stagedRoot().resolve("neoforge-patched/patched-mc-neoforge-26.2.jar");

	@Test void theShippedTableIsExactlyWhatTheArtifactsSay() throws Exception {
		for (Path jar : List.of(MERGED, VANILLA, FORGE, NEOFORGE)) {
			TestFixtures.require(jar == VANILLA ? Fixture.MC_LIBRARIES : Fixture.STAGED, Files.isRegularFile(jar), jar + " required");
		}
		Map<Ecosystem, ZipFile> references = new LinkedHashMap<>();
		references.put(Ecosystem.FABRIC, new ZipFile(VANILLA.toFile()));
		references.put(Ecosystem.FORGE, new ZipFile(FORGE.toFile()));
		references.put(Ecosystem.NEOFORGE, new ZipFile(NEOFORGE.toFile()));
		TreeMap<String, Set<Ecosystem>> derived = new TreeMap<>();
		try (ZipFile zip = new ZipFile(MERGED.toFile())) {
			for (ZipEntry entry : Collections.list(zip.entries())) {
				if (!entry.getName().endsWith(".class") || !entry.getName().startsWith("net/minecraft/")) continue;
				ClassNode merged = read(zip, entry.getName());
				for (MethodNode method : merged.methods) {
					if ((method.access & (Opcodes.ACC_BRIDGE | Opcodes.ACC_SYNTHETIC)) != 0 || method.name.startsWith("<")) continue;
					List<MethodInsnNode> pieces = CarrierHelpers.dispatchedHelpers(merged, method);
					Map<String, Integer> helpers = pieces == null ? helperCalls(merged, method) : Map.of();
					if (pieces == null && helpers.isEmpty()) continue;
					for (Map.Entry<Ecosystem, ZipFile> reference : references.entrySet()) {
						ClassNode original = read(reference.getValue(), entry.getName());
						MethodNode before = CarrierHelpers.declared(original, method.name, method.desc);
						if (pieces != null) splitRows(merged, method, pieces, original, before, reference.getKey(), derived);
						else edgeRows(merged, method, helpers, original, before, reference.getKey(), derived);
					}
				}
			}
		} finally {
			for (ZipFile reference : references.values()) reference.close();
		}
		TreeSet<String> rows = new TreeSet<>();
		derived.forEach((head, ecosystems) -> rows.add(head + " | " + String.join(",", ecosystems.stream().sorted().map(Enum::name).toList())));

		List<String> shipped = new ArrayList<>();
		try (InputStream in = CarrierHelpers.class.getResourceAsStream(CarrierHelpers.TABLE)) {
			assertNotNull(in, CarrierHelpers.TABLE + " is missing");
			for (String line : new String(in.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
				if (!line.isBlank() && !line.startsWith("#")) shipped.add(line.trim());
			}
		}
		if (System.getenv("FORBRIC_WRITE_CARRIER_HELPERS") != null) {
			Files.writeString(Path.of("src/main/resources" + CarrierHelpers.TABLE),
					"# Generated by CarrierHelperCensusTest (FORBRIC_WRITE_CARRIER_HELPERS=1): a call the method makes in each listed\n"
					+ "# ecosystem's own jar, which the merged base makes in a helper the carrier added. MixinRetarget moves an\n"
					+ "# injector only along these rows, and only for a mod of a listed ecosystem.\n"
					+ "# <class>#<method> -> <helper> : <call or field> | <shape> | <ecosystems>\n"
					+ String.join("\n", rows) + "\n");
		}
		assertEquals(rows, new TreeSet<>(shipped), "carrier-helpers.txt must equal what the staged jars say; "
				+ "regenerate with FORBRIC_WRITE_CARRIER_HELPERS=1 after a base rebuild");
		for (String row : shipped) assertNotNull(CarrierHelpers.Row.parse(row), "unreadable row: " + row);
	}

	/**
	 * SPLIT: the merged method is a pure dispatcher over helpers none of which the reference declares, the reference's
	 * method is a body of its own, and the call — made once there — is made in exactly one of the pieces, once.
	 */
	private static void splitRows(ClassNode merged, MethodNode method, List<MethodInsnNode> pieces, ClassNode original,
			MethodNode before, Ecosystem ecosystem, Map<String, Set<Ecosystem>> out) {
		if (before == null || before.instructions == null || CarrierHelpers.dispatchedHelpers(original, before) != null) return;
		Set<MethodNode> helpers = new LinkedHashSet<>();
		for (MethodInsnNode call : pieces) {
			if (CarrierHelpers.declared(original, call.name, call.desc) != null) return;
			helpers.add(CarrierHelpers.declared(merged, call.name, call.desc));
		}
		Set<String> members = new LinkedHashSet<>();
		for (AbstractInsnNode insn : before.instructions) {
			String member = CarrierHelpers.member(insn);
			if (member != null) members.add(member);
		}
		for (String member : members) {
			if (CarrierHelpers.occurrences(before, member) != 1) continue;
			MethodNode home = null;
			int homes = 0;
			for (MethodNode helper : helpers) {
				if (CarrierHelpers.occurrences(helper, member) > 0) { home = helper; homes++; }
			}
			if (homes != 1 || CarrierHelpers.occurrences(home, member) != 1) continue;
			String head = merged.name + "#" + method.name + method.desc + " -> " + home.name + home.desc + " : " + member + " | SPLIT";
			out.computeIfAbsent(head, k -> EnumSet.noneOf(Ecosystem.class)).add(ecosystem);
		}
	}

	/**
	 * HEAD/TAIL: the merged method keeps a body; a helper it calls exactly once, which the reference does not declare,
	 * makes a call the reference's method made exactly once and the merged method no longer makes — exactly once, as
	 * its first or last act ({@link CarrierHelpers#reached}). Same-name overloads are a stub's business (carrier-stubs.txt,
	 * MixinStubRebind), and constructors are left alone.
	 */
	private static void edgeRows(ClassNode merged, MethodNode method, Map<String, Integer> helpers, ClassNode original,
			MethodNode before, Ecosystem ecosystem, Map<String, Set<Ecosystem>> out) {
		if (before == null || before.instructions == null) return;
		Set<String> calls = new LinkedHashSet<>();
		for (AbstractInsnNode insn : before.instructions) if (insn instanceof MethodInsnNode) calls.add(CarrierHelpers.member(insn));
		for (Map.Entry<String, Integer> called : helpers.entrySet()) {
			if (called.getValue() != 1) continue;
			int paren = called.getKey().indexOf('(');
			String name = called.getKey().substring(0, paren), desc = called.getKey().substring(paren);
			if (CarrierHelpers.declared(original, name, desc) != null) continue;
			MethodNode helper = CarrierHelpers.declared(merged, name, desc);
			for (String member : calls) {
				if (CarrierHelpers.occurrences(before, member) != 1 || CarrierHelpers.occurrences(method, member) != 0) continue;
				Set<CarrierHelpers.Shape> shapes = CarrierHelpers.reached(merged, method, helper, member);
				if (shapes.isEmpty()) continue;
				String head = merged.name + "#" + method.name + method.desc + " -> " + helper.name + helper.desc + " : " + member
						+ " | " + String.join(",", shapes.stream().sorted().map(Enum::name).toList());
				out.computeIfAbsent(head, k -> EnumSet.noneOf(Ecosystem.class)).add(ecosystem);
			}
		}
	}

	/** Same-class methods with a body that {@code method} calls, other than its own name and constructors, with how often. */
	private static Map<String, Integer> helperCalls(ClassNode owner, MethodNode method) {
		Map<String, Integer> out = new LinkedHashMap<>();
		if (method.instructions == null) return out;
		for (AbstractInsnNode insn : method.instructions) {
			if (!(insn instanceof MethodInsnNode call) || !call.owner.equals(owner.name) || call.name.equals(method.name)
					|| call.name.startsWith("<")) continue;
			MethodNode helper = CarrierHelpers.declared(owner, call.name, call.desc);
			if (helper == null || helper.instructions == null || helper.instructions.size() == 0) continue;
			out.merge(call.name + call.desc, 1, Integer::sum);
		}
		return out;
	}

	private static ClassNode read(ZipFile zip, String name) throws Exception {
		ZipEntry entry = zip.getEntry(name);
		if (entry == null) return null;
		try (InputStream in = zip.getInputStream(entry)) {
			ClassNode node = new ClassNode();
			new ClassReader(in.readAllBytes()).accept(node, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
			return node;
		}
	}
}
