/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.TreeSet;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import net.forbric.kernel.TestFixtures;
import net.forbric.kernel.TestFixtures.Fixture;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.LocalVariableNode;
import org.objectweb.asm.tree.MethodNode;

/**
 * Re-derives {@code lambda-permutations.txt} — every vanilla lambda the merged base still declares under the same name
 * with the same parameters in ANOTHER ORDER — and asserts the shipped table equals it.
 *
 * <p>javac orders a lambda's captured values by first use, so a carrier patch that uses one of them earlier moves it:
 * NeoForge's {@code WorldLoader.load} passes {@code staticLayerTags} on to {@code RegistryDataLoader.load}, and the
 * capture moved from sixth to fourth. A row is written only when the order is PROVABLE — each vanilla parameter
 * matches exactly one merged parameter by local variable name AND type — because {@link MixinHandlerShim} hands a mod's
 * handler its arguments along the row, and a row that is a guess hands it the wrong object without a word.
 */
class LambdaPermutationCensusTest {
	private static final Path MERGED = TestFixtures.stagedRoot().resolve("merged-base/patched-mc-merged-26.2.jar");
	private static final Path VANILLA = TestFixtures.vanillaJar();

	@Test void theShippedTableIsExactlyWhatTheArtifactsSay() throws Exception {
		TestFixtures.require(Fixture.STAGED, Files.isRegularFile(MERGED), "merged base and vanilla jar required");
		TestFixtures.require(Fixture.MC_LIBRARIES, Files.isRegularFile(VANILLA), "merged base and vanilla jar required");
		Map<String, ClassNode> vanilla = read(VANILLA);
		TreeSet<String> rows = new TreeSet<>();
		try (ZipFile zip = new ZipFile(MERGED.toFile())) {
			for (ZipEntry entry : Collections.list(zip.entries())) {
				if (!entry.getName().endsWith(".class") || !entry.getName().startsWith("net/minecraft/")) continue;
				ClassNode original = vanilla.get(entry.getName().substring(0, entry.getName().length() - ".class".length()));
				if (original == null) continue;
				ClassNode merged = new ClassNode();
				new ClassReader(zip.getInputStream(entry).readAllBytes()).accept(merged, ClassReader.SKIP_FRAMES);
				for (MethodNode lambda : original.methods) {
					if (!lambda.name.startsWith("lambda$")) continue;
					MethodNode live = only(merged, lambda.name);
					if (live == null) continue;
					int[] perm = permutation(lambda, live);
					if (perm == null) continue;
					StringJoiner joined = new StringJoiner(",");
					for (int p : perm) joined.add(Integer.toString(p));
					rows.add(merged.name + "#" + lambda.name + lambda.desc + " -> " + live.desc + " " + joined);
				}
			}
		}
		assertTrue(rows.stream().anyMatch(r -> r.startsWith("net/minecraft/server/WorldLoader#lambda$load$1(") && r.endsWith(" 0,1,2,4,5,6,3,7,8,9,10")),
				"the row wover-events' registry hook needs: " + rows);
		List<String> shipped = new ArrayList<>();
		try (InputStream in = MixinHandlerShim.class.getResourceAsStream(MixinHandlerShim.TABLE)) {
			assertNotNull(in, MixinHandlerShim.TABLE + " is missing");
			for (String line : new String(in.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
				if (!line.isBlank() && !line.startsWith("#")) shipped.add(line.trim());
			}
		}
		if (System.getenv("FORBRIC_WRITE_LAMBDA_PERMUTATIONS") != null) {
			Path out = Path.of("src/main/resources" + MixinHandlerShim.TABLE);
			Files.writeString(out, "# Generated by LambdaPermutationCensusTest (FORBRIC_WRITE_LAMBDA_PERMUTATIONS=1): vanilla lambdas the merged base\n"
					+ "# declares once, same name, same parameters in another order, each matched 1:1 by local variable name and type.\n"
					+ "# <owner>#<lambda><vanilla descriptor> -> <merged descriptor> <merged index holding each vanilla parameter>\n"
					+ String.join("\n", rows) + "\n");
		}
		assertEquals(rows, new TreeSet<>(shipped), "lambda-permutations.txt must equal what the staged merged base and vanilla say; "
				+ "regenerate with FORBRIC_WRITE_LAMBDA_PERMUTATIONS=1 after a base rebuild");
		for (String row : shipped) assertNotNull(MixinHandlerShim.Permutation.parse(row), "the shim must accept every shipped row: " + row);
	}

	/** Where each vanilla parameter went, or null unless the two lists are one reordering provable by name and type. */
	static int[] permutation(MethodNode vanilla, MethodNode merged) {
		if (((vanilla.access ^ merged.access) & Opcodes.ACC_STATIC) != 0) return null;
		if (!Type.getReturnType(vanilla.desc).equals(Type.getReturnType(merged.desc))) return null;
		Type[] from = Type.getArgumentTypes(vanilla.desc), to = Type.getArgumentTypes(merged.desc);
		if (from.length != to.length || Arrays.equals(from, to)) return null;
		String[] fromNames = parameterNames(vanilla), toNames = parameterNames(merged);
		if (fromNames == null || toNames == null) return null;
		int[] perm = new int[from.length];
		boolean[] taken = new boolean[to.length];
		for (int i = 0; i < from.length; i++) {
			int found = -1;
			for (int j = 0; j < to.length; j++) {
				if (!to[j].equals(from[i]) || !toNames[j].equals(fromNames[i])) continue;
				if (found >= 0) return null;   // two parameters of one name and type: not provable
				found = j;
			}
			if (found < 0 || taken[found]) return null;
			taken[found] = true;
			perm[i] = found;
		}
		return perm;
	}

	/** Each parameter's name from the local variable table, or null when the table does not name every one. */
	private static String[] parameterNames(MethodNode method) {
		if (method.localVariables == null) return null;
		Type[] params = Type.getArgumentTypes(method.desc);
		String[] names = new String[params.length];
		int slot = (method.access & Opcodes.ACC_STATIC) != 0 ? 0 : 1;
		for (int i = 0; i < params.length; i++) {
			for (LocalVariableNode local : method.localVariables) {
				if (local.index == slot && local.desc.equals(params[i].getDescriptor())
						&& method.instructions.indexOf(local.start) <= firstRealInstruction(method)) {
					names[i] = local.name;
				}
			}
			if (names[i] == null) return null;
			slot += params[i].getSize();
		}
		return names;
	}

	private static int firstRealInstruction(MethodNode method) {
		for (int i = 0; i < method.instructions.size(); i++) if (method.instructions.get(i).getOpcode() >= 0) return i;
		return method.instructions.size();
	}

	private static MethodNode only(ClassNode node, String name) {
		MethodNode only = null;
		for (MethodNode m : node.methods) {
			if (!m.name.equals(name)) continue;
			if (only != null) return null;
			only = m;
		}
		return only;
	}

	private static Map<String, ClassNode> read(Path jar) throws Exception {
		Map<String, ClassNode> out = new HashMap<>();
		try (ZipFile zip = new ZipFile(jar.toFile())) {
			for (ZipEntry entry : Collections.list(zip.entries())) {
				if (!entry.getName().endsWith(".class") || !entry.getName().startsWith("net/minecraft/")) continue;
				ClassNode node = new ClassNode();
				new ClassReader(zip.getInputStream(entry).readAllBytes()).accept(node, ClassReader.SKIP_FRAMES);
				out.put(node.name, node);
			}
		}
		return out;
	}
}
