/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;
import static org.junit.jupiter.api.Assertions.*;import java.nio.file.*;import java.util.jar.*;import java.security.*;import java.util.*;import org.junit.jupiter.api.*;import org.objectweb.asm.*;import org.objectweb.asm.tree.*;import net.forbric.api.Ecosystem;import net.forbric.kernel.boot.KernelTagFacadeContracts;
@org.junit.jupiter.api.parallel.ResourceLock("NativeGameReferences")
class NativeTagSourceFacadeInjectorTest implements Opcodes{
 @AfterEach void reset(){KernelTagFacadeContracts.resetForTests();NativeGameReferences.bind(null);}
 @Test void theIndexedEntityEyeAndHeightFacadesRecoverTheirOriginalContainerTagOperand()throws Exception{try(var input=new MixinCrossHostPredicateIslandTest.Inputs()){var current=input.current("net/minecraft/world/entity/Entity");var nativeNode=input.original.get(Ecosystem.FABRIC,current.name);assertNotNull(nativeNode);assertTrue(NativeTagSourceFacadeInjector.adapt(nativeNode,current,input::current));List<String>patched=new ArrayList<>();for(var m:current.methods)for(var i:m.instructions)if(i instanceof MethodInsnNode call&&call.owner.equals("net/forbric/kernel/runtime/KernelTagFacadeSources"))patched.add(m.name+m.desc);assertTrue(patched.contains("isEyeInFluid(Lnet/minecraft/tags/TagKey;)Z"));assertTrue(patched.contains("getFluidHeight(Lnet/minecraft/tags/TagKey;)D"));}}
 @Test void missingOriginalSourceOrContainerAndChangedTypedRecipeAreRejected()throws Exception{try(var input=new MixinCrossHostPredicateIslandTest.Inputs()){var current=input.current("net/minecraft/world/entity/Entity");ClassNode absent=new ClassNode();absent.name=current.name;assertFalse(NativeTagSourceFacadeInjector.adapt(absent,current,input::current));var nativeNode=input.original.get(Ecosystem.FABRIC,current.name);assertFalse(NativeTagSourceFacadeInjector.adapt(nativeNode,current,n->null));for(var method:current.methods)if(method.desc.equals("(Lnet/neoforged/neoforge/fluids/FluidType;)Z")||method.desc.equals("(Lnet/neoforged/neoforge/fluids/FluidType;)D"))method.instructions.insert(new InsnNode(NOP));assertFalse(NativeTagSourceFacadeInjector.adapt(nativeNode,current,input::current));}}
 @Test void theCurrentMapperMustKeepItsActualStaticPublicBodyContract()throws Exception{try(var input=new MixinCrossHostPredicateIslandTest.Inputs()){ClassNode current=input.current("net/minecraft/world/entity/Entity"),container=input.current("net/minecraft/world/entity/EntityFluidInteraction");for(var method:container.methods)if(method.name.equals("getFluidTypeByTag"))method.access|=ACC_SYNCHRONIZED;assertFalse(NativeTagSourceFacadeInjector.adapt(input.original.get(Ecosystem.FABRIC,current.name),current,input::current));}}
 @Test void theRealPreMixinReaderRejectsCyclicContainerMetadataWithoutRecursingOrPoisoningItsCache(@org.junit.jupiter.api.io.TempDir Path work)throws Exception{
  String a="net/minecraft/fixture/CycleA",b="net/minecraft/fixture/CycleB";Map<String,byte[]>current=Map.of(a,cycleClass(a,b,false),b,cycleClass(b,a,false)),original=Map.of(a,cycleClass(a,b,true),b,cycleClass(b,a,true));Path jar=work.resolve("cycles.jar");StringBuilder index=new StringBuilder("# forbric-native-reference-v1\n");for(var e:original.entrySet())index.append(e.getKey()).append('\t').append(HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(e.getValue()))).append('\n');try(var out=new JarOutputStream(Files.newOutputStream(jar))){for(var e:current.entrySet()){out.putNextEntry(new JarEntry(e.getKey()+".class"));out.write(e.getValue());out.closeEntry();}out.putNextEntry(new JarEntry("META-INF/forbric/native-reference/FABRIC/index.tsv"));out.write(index.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));out.closeEntry();for(var e:original.entrySet()){out.putNextEntry(new JarEntry("META-INF/forbric/native-reference/FABRIC/"+e.getKey()+".class.bin"));out.write(e.getValue());out.closeEntry();}}
  try(var loader=new net.forbric.kernel.classloading.ForbricClassLoader(new java.net.URL[]{jar.toUri().toURL()},getClass().getClassLoader())){NativeGameReferences.bind(loader);var calls=new java.util.concurrent.atomic.AtomicInteger();var injector=new NativeTagSourceFacadeInjector();loader.setTransformer((name,bytes)->{assertTrue(calls.incrementAndGet()<8,"metadata cycle must close");return injector.transform(name,bytes,null);});byte[]first=assertTimeoutPreemptively(java.time.Duration.ofSeconds(3),()->loader.getPreMixinClassBytes(a));assertArrayEquals(current.get(a),first);assertSame(first,loader.getPreMixinClassBytes(a.replace('/','.')));assertArrayEquals(current.get(b),loader.getPreMixinClassBytes(b));assertEquals(2,calls.get());}
 }
 private static byte[]cycleClass(String owner,String container,boolean nativeBody){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_MAXS);w.visit(V21,ACC_PUBLIC,owner,null,"java/lang/Object",null);w.visitField(ACC_PUBLIC|ACC_FINAL,"other","L"+container+";",null,null).visitEnd();var m=w.visitMethod(ACC_PUBLIC,"legacy","(Lfixture/Tag;)Z",null,null);m.visitCode();m.visitVarInsn(ALOAD,0);if(nativeBody){m.visitFieldInsn(GETFIELD,owner,"other","L"+container+";");m.visitVarInsn(ALOAD,1);m.visitMethodInsn(INVOKEVIRTUAL,container,"legacy","(Lfixture/Tag;)Z",false);}else{m.visitVarInsn(ALOAD,1);m.visitMethodInsn(INVOKESTATIC,"fixture/Mapper","type","(Lfixture/Tag;)Lfixture/Type;",false);m.visitMethodInsn(INVOKEVIRTUAL,owner,"typed","(Lfixture/Type;)Z",false);}m.visitInsn(IRETURN);m.visitMaxs(0,0);m.visitEnd();m=w.visitMethod(ACC_PUBLIC,"typed","(Lfixture/Type;)Z",null,null);m.visitCode();m.visitVarInsn(ALOAD,0);m.visitFieldInsn(GETFIELD,owner,"other","L"+container+";");m.visitVarInsn(ALOAD,1);m.visitMethodInsn(INVOKEVIRTUAL,container,"typed","(Lfixture/Type;)Z",false);m.visitInsn(IRETURN);m.visitMaxs(0,0);m.visitEnd();w.visitEnd();return w.toByteArray();}

}
