package net.forbric.kernel.mixin;

import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import net.forbric.kernel.boot.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.ResourceLock;
import org.objectweb.asm.*;
import org.objectweb.asm.commons.*;
import org.objectweb.asm.tree.*;

@ResourceLock("DefinedMethodContracts")
class SharedFinalSourceCertifierTest {
    private static final String SOURCE="fixture/RememberedSource",HOST="fixture/RememberedHost",OP="com/llamalad7/mixinextras/injector/wrapoperation/Operation";
    private static final Handle LMF=new Handle(Opcodes.H_INVOKESTATIC,"java/lang/invoke/LambdaMetafactory","metafactory","(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;",false);
    @BeforeEach @AfterEach void reset(){SharedFinalSourceCertifier.resetForTests();DefinedMethodContracts.resetForTests();}

    @Test void completeFinalContinuationPublishesOnlyInItsActualDefiningLoader()throws Exception{
        Fixture fixture=fixture();assertEquals(Set.of("plan"),SharedFinalSourceCertifier.certify(fixture.target).keySet());
        byte[] bytes=write(fixture.target);ClassNode read=new ClassNode();new ClassReader(bytes).accept(read,ClassReader.SKIP_DEBUG|ClassReader.SKIP_FRAMES);assertEquals(Set.of("plan"),SharedFinalSourceCertifier.certify(read).keySet());Loader first=new Loader();Class<?> owner=first.define(bytes);Object actor=owner.getConstructor().newInstance();
        assertFalse(SharedFinalSourceContracts.permits(actor,"plan"));DefinedMethodContracts.observe(first,HOST,bytes);SharedFinalSourceContracts.observeDefinition(first,HOST,bytes);for(var contract:SharedFinalSourceCertifier.certify(read).get("plan").methods())assertTrue(DefinedMethodContracts.observed(first,contract),contract.toString());assertDoesNotThrow(owner::getDeclaredMethods);assertTrue(SharedFinalSourceContracts.permits(actor,"plan"));
        Loader second=new Loader();Object other=second.define(bytes).getConstructor().newInstance();DefinedMethodContracts.observe(second,HOST,bytes);assertFalse(SharedFinalSourceContracts.permits(other,"plan"));SharedFinalSourceContracts.observeDefinition(first,HOST,bytes);assertFalse(SharedFinalSourceContracts.permits(other,"plan"));
    }
    @Test void eitherOriginalCallbackChangingDeclinesTheEntireContinuation(){
        for(String name:List.of("merged$under","merged$ground")){Fixture fixture=fixture();MethodNode method=find(fixture.target,name);method.instructions.insertBefore(method.instructions.getLast(),new InsnNode(Opcodes.ICONST_1));method.instructions.insertBefore(method.instructions.getLast(),new InsnNode(Opcodes.IXOR));assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty(),name);}
    }
    @Test void changedGuardAndChangedGeneratedWrapperDoNotRetainAStaleWitness(){
        for(String name:List.of("u","typed","query","guard","host")){Fixture fixture=fixture();MethodNode method=find(fixture.target,name);method.instructions.insert(new InsnNode(Opcodes.NOP));assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty(),name);}
        Fixture fixture=fixture();MethodNode method=find(fixture.target,"u");MethodInsnNode guard=Arrays.stream(method.instructions.toArray()).filter(i->i instanceof MethodInsnNode call&&call.name.equals("passenger")).map(MethodInsnNode.class::cast).findFirst().orElseThrow();method.instructions.insert(guard,new InsnNode(Opcodes.IXOR));method.instructions.insert(guard,new InsnNode(Opcodes.ICONST_1));assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty());
    }
    @Test void wrongSharedRefWrongAtomArgumentAndExtraRelayEffectDecline(){
        Fixture fixture=fixture();List<AbstractInsnNode> code=real(find(fixture.target,"g"));((VarInsnNode)code.get(8)).var=2;assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty());
        fixture=fixture();MethodNode relay=find(fixture.target,"relay");List<AbstractInsnNode> rc=real(relay);((IntInsnNode)rc.get(7)).operand=0;assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty());
        fixture=fixture();find(fixture.target,"relay").instructions.insert(new MethodInsnNode(Opcodes.INVOKESTATIC,"java/lang/System","gc","()V",false));assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty());
    }
    @Test void ambiguousAliasesAndChangedFlagsCannotCertify(){
        Fixture fixture=fixture();MethodNode duplicate=copy(find(fixture.target,"merged$under"));duplicate.name="other$under";fixture.target.methods.add(duplicate);assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty());
        fixture=fixture();find(fixture.target,"relay").access|=Opcodes.ACC_SYNCHRONIZED;assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty());
        fixture=fixture();find(fixture.target,"u").access|=Opcodes.ACC_STATIC;assertTrue(SharedFinalSourceCertifier.certify(fixture.target).isEmpty());
    }
    @Test void normalizationDoesNotMutateExecutableBootstrapArguments(){
        Fixture fixture=fixture();String before=MixinInstructionFingerprint.hash(find(fixture.target,"query"));InvokeDynamicInsnNode dynamic=Arrays.stream(find(fixture.target,"query").instructions.toArray()).filter(InvokeDynamicInsnNode.class::isInstance).map(InvokeDynamicInsnNode.class::cast).findFirst().orElseThrow();Object[] arguments=dynamic.bsmArgs;Object handle=arguments[1];assertEquals(1,SharedFinalSourceCertifier.certify(fixture.target).size());assertSame(arguments,dynamic.bsmArgs);assertSame(handle,dynamic.bsmArgs[1]);assertEquals(before,MixinInstructionFingerprint.hash(find(fixture.target,"query")));
    }
    @Test void aLaterChangedObservationRevokesTheToken()throws Exception{
        Fixture fixture=fixture();byte[] bytes=write(fixture.target);Loader loader=new Loader();Object actor=loader.define(bytes).getConstructor().newInstance();DefinedMethodContracts.observe(loader,HOST,bytes);SharedFinalSourceContracts.observeDefinition(loader,HOST,bytes);assertTrue(SharedFinalSourceContracts.permits(actor,"plan"));
        find(fixture.target,"merged$ground").instructions.insert(new InsnNode(Opcodes.NOP));byte[] changed=write(fixture.target);DefinedMethodContracts.observe(loader,HOST,changed);SharedFinalSourceContracts.observeDefinition(loader,HOST,changed);assertFalse(SharedFinalSourceContracts.permits(actor,"plan"));
    }
    @Test void aReassignedSlotZeroDoesNotProveARemovedCastRedundant(){assertTrue(SharedFinalSourceCertifier.certify(fixture(true).target).isEmpty());}

    private record Fixture(ClassNode target) { }
    private static Fixture fixture(){return fixture(false);}
    private static Fixture fixture(boolean assignSelf){
        MethodNode under=method("under","(ZLjava/lang/Object;)Z",false);under.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));under.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,HOST));under.instructions.add(new InsnNode(Opcodes.POP));under.instructions.add(new VarInsnNode(Opcodes.ILOAD,1));under.instructions.add(new InsnNode(Opcodes.IRETURN));
        if(assignSelf){InsnList overwrite=new InsnList();overwrite.add(new VarInsnNode(Opcodes.ALOAD,2));overwrite.add(new VarInsnNode(Opcodes.ASTORE,0));under.instructions.insert(overwrite);}
        MethodNode ground=method("ground","(Ljava/util/Set;Ljava/lang/Object;L"+OP+";Ljava/lang/Object;)Z",false);ground.instructions.add(new VarInsnNode(Opcodes.ALOAD,3));ground.instructions.add(new InsnNode(Opcodes.ICONST_2));ground.instructions.add(new TypeInsnNode(Opcodes.ANEWARRAY,"java/lang/Object"));for(int i=0;i<2;i++){ground.instructions.add(new InsnNode(Opcodes.DUP));ground.instructions.add(new InsnNode(Opcodes.ICONST_0+i));ground.instructions.add(new VarInsnNode(Opcodes.ALOAD,i+1));ground.instructions.add(new InsnNode(Opcodes.AASTORE));}ground.instructions.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,OP,"call","([Ljava/lang/Object;)Ljava/lang/Object;",true));ground.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,"java/lang/Boolean"));ground.instructions.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL,"java/lang/Boolean","booleanValue","()Z",false));ground.instructions.add(new InsnNode(Opcodes.IRETURN));
        MethodInsnNode ua=new MethodInsnNode(Opcodes.INVOKEVIRTUAL,HOST,"base","()Z",false),ga=new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/Set","contains","(Ljava/lang/Object;)Z",true);
        MethodNode u=method("u","(Ljava/lang/Object;)Z",true);LabelNode fail=new LabelNode();u.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));u.instructions.add(call(ua));u.instructions.add(new JumpInsnNode(Opcodes.IFEQ,fail));u.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));u.instructions.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL,HOST,"passenger","()Z",false));u.instructions.add(new InsnNode(Opcodes.DUP));u.instructions.add(new LdcInsnNode("site"));u.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,"net/forbric/kernel/runtime/KernelSharedPredicateScopes","recordGuard","(ZLjava/lang/String;)V",false));u.instructions.add(new JumpInsnNode(Opcodes.IFNE,fail));u.instructions.add(new InsnNode(Opcodes.ICONST_1));u.instructions.add(new InsnNode(Opcodes.IRETURN));u.instructions.add(fail);u.instructions.add(new InsnNode(Opcodes.ICONST_0));u.instructions.add(new InsnNode(Opcodes.IRETURN));
        MethodNode g=method("g","(Ljava/lang/Object;Ljava/util/Set;)Z",true);g.instructions.add(new VarInsnNode(Opcodes.ALOAD,2));g.instructions.add(new FieldInsnNode(Opcodes.GETSTATIC,HOST,"TAG","Ljava/lang/Object;"));g.instructions.add(call(ga));g.instructions.add(new InsnNode(Opcodes.IRETURN));
        MethodNode typed=method("typed","(Ljava/lang/Object;Ljava/lang/Object;)Z",true);typed.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));typed.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));typed.instructions.add(new VarInsnNode(Opcodes.ALOAD,2));typed.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,"java/util/Set"));typed.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,SOURCE,"g",g.desc,false));typed.instructions.add(new InsnNode(Opcodes.IRETURN));
        MethodNode query=method("query","(Ljava/lang/Object;)Ljava/util/function/BooleanSupplier;",true);query.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));query.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));query.instructions.add(new InvokeDynamicInsnNode("getAsBoolean","(L"+SOURCE+";Ljava/lang/Object;)Ljava/util/function/BooleanSupplier;",LMF,Type.getMethodType("()Z"),new Handle(Opcodes.H_INVOKEVIRTUAL,SOURCE,"u",u.desc,false),Type.getMethodType("()Z")));query.instructions.add(new InsnNode(Opcodes.ARETURN));
        MethodNode guard=method("guard","()Z",true);guard.instructions.add(new InsnNode(Opcodes.ICONST_0));guard.instructions.add(new InsnNode(Opcodes.IRETURN));MethodNode host=method("host","()V",true);host.instructions.add(new InsnNode(Opcodes.RETURN));
        SharedFinalSourceCertifier.remember("plan",HOST,SOURCE,under,ground,u,g,List.of(typed,query,guard,host),ua,ga);
        ClassNode target=new ClassNode();target.version=Opcodes.V21;target.access=Opcodes.ACC_PUBLIC;target.name=HOST;target.superName="java/lang/Object";target.fields.add(new FieldNode(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"TAG","Ljava/lang/Object;",null,null));
        for(MethodNode original:List.of(under,ground,u,g,typed,query,guard,host)){MethodNode finalMethod=remap(original);if(original==under||original==ground)finalMethod.name="merged$"+original.name;merged(finalMethod);target.methods.add(finalMethod);}
        MethodNode finalUnder=find(target,"merged$under");for(AbstractInsnNode node:finalUnder.instructions.toArray())if(node instanceof TypeInsnNode)finalUnder.instructions.remove(node);
        MethodNode finalU=find(target,"u");MethodInsnNode anchor=Arrays.stream(finalU.instructions.toArray()).filter(i->i instanceof MethodInsnNode m&&m.name.equals("base")).map(MethodInsnNode.class::cast).findFirst().orElseThrow();InsnList injection=new InsnList();injection.add(new VarInsnNode(Opcodes.ALOAD,0));injection.add(new InsnNode(Opcodes.SWAP));injection.add(new VarInsnNode(Opcodes.ALOAD,1));injection.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,HOST,"merged$under",under.desc,false));finalU.instructions.insert(anchor,injection);
        MethodNode finalG=find(target,"g");finalG.instructions.clear();finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,2));finalG.instructions.add(new FieldInsnNode(Opcodes.GETSTATIC,HOST,"TAG","Ljava/lang/Object;"));finalG.instructions.add(new VarInsnNode(Opcodes.ASTORE,4));finalG.instructions.add(new VarInsnNode(Opcodes.ASTORE,3));finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,3));finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,4));finalG.instructions.add(new InvokeDynamicInsnNode("call","()L"+OP+";",LMF,Type.getMethodType("([Ljava/lang/Object;)Ljava/lang/Object;"),new Handle(Opcodes.H_INVOKESTATIC,HOST,"relay","([Ljava/lang/Object;)Ljava/lang/Boolean;",false),Type.getMethodType("([Ljava/lang/Object;)Ljava/lang/Boolean;")));finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));finalG.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,HOST,"merged$ground",ground.desc,false));finalG.instructions.add(new InsnNode(Opcodes.IRETURN));
        MethodNode relay=new MethodNode(Opcodes.ACC_PRIVATE|Opcodes.ACC_STATIC|Opcodes.ACC_SYNTHETIC,"relay","([Ljava/lang/Object;)Ljava/lang/Boolean;",null,null);relay.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));relay.instructions.add(new InsnNode(Opcodes.DUP));relay.instructions.add(new IntInsnNode(Opcodes.BIPUSH,0));relay.instructions.add(new InsnNode(Opcodes.AALOAD));relay.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,"java/util/Set"));relay.instructions.add(new InsnNode(Opcodes.SWAP));relay.instructions.add(new InsnNode(Opcodes.DUP));relay.instructions.add(new IntInsnNode(Opcodes.BIPUSH,1));relay.instructions.add(new InsnNode(Opcodes.AALOAD));relay.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,"java/lang/Object"));relay.instructions.add(new InsnNode(Opcodes.SWAP));relay.instructions.add(new InsnNode(Opcodes.POP));relay.instructions.add(call(ga));relay.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,"java/lang/Boolean","valueOf","(Z)Ljava/lang/Boolean;",false));relay.instructions.add(new InsnNode(Opcodes.ARETURN));target.methods.add(relay);
        MethodNode ctor=new MethodNode(Opcodes.ACC_PUBLIC,"<init>","()V",null,null);ctor.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));ctor.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,"java/lang/Object","<init>","()V",false));ctor.instructions.add(new InsnNode(Opcodes.RETURN));target.methods.add(ctor);for(String name:List.of("base","passenger")){MethodNode m=new MethodNode(Opcodes.ACC_PUBLIC,name,"()Z",null,null);m.instructions.add(new InsnNode(Opcodes.ICONST_0));m.instructions.add(new InsnNode(Opcodes.IRETURN));target.methods.add(m);}return new Fixture(target);
    }
    private static MethodNode method(String name,String desc,boolean unique){MethodNode method=new MethodNode(Opcodes.ACC_PRIVATE,name,desc,null,null);if(unique)method.visibleAnnotations=new ArrayList<>(List.of(new AnnotationNode("Lorg/spongepowered/asm/mixin/Unique;")));return method;}
    private static void merged(MethodNode method){if(method.visibleAnnotations==null)method.visibleAnnotations=new ArrayList<>();AnnotationNode annotation=new AnnotationNode("Lorg/spongepowered/asm/mixin/transformer/meta/MixinMerged;");annotation.values=new ArrayList<>(List.of("mixin",SOURCE.replace('/','.')));method.visibleAnnotations.add(annotation);}
    private static MethodNode remap(MethodNode method){MethodNode result=new MethodNode(method.access,method.name,method.desc,null,null);method.accept(new MethodRemapper(result,new Remapper(){@Override public String map(String owner){return owner.equals(SOURCE)?HOST:owner;}}));return result;}
    private static MethodInsnNode call(MethodInsnNode node){return new MethodInsnNode(node.getOpcode(),node.owner,node.name,node.desc,node.itf);}
    private static MethodNode copy(MethodNode method){MethodNode copy=new MethodNode();method.accept(copy);return copy;}
    private static MethodNode find(ClassNode node,String name){return node.methods.stream().filter(m->m.name.equals(name)).findFirst().orElseThrow();}
    private static List<AbstractInsnNode> real(MethodNode method){return Arrays.stream(method.instructions.toArray()).filter(n->n.getOpcode()>=0).toList();}
    private static byte[] write(ClassNode node){ClassWriter writer=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);node.accept(writer);return writer.toByteArray();}
    private static class Loader extends ClassLoader{
        Class<?> define(byte[] bytes){return defineClass(HOST.replace('/','.'),bytes,0,bytes.length);}
        @Override protected Class<?> findClass(String name)throws ClassNotFoundException{
            if(!name.equals(OP.replace('/','.')))throw new ClassNotFoundException(name);
            ClassWriter writer=new ClassWriter(0);writer.visit(Opcodes.V21,Opcodes.ACC_PUBLIC|Opcodes.ACC_INTERFACE|Opcodes.ACC_ABSTRACT,OP,null,"java/lang/Object",null);writer.visitMethod(Opcodes.ACC_PUBLIC|Opcodes.ACC_ABSTRACT,"call","([Ljava/lang/Object;)Ljava/lang/Object;",null,null).visitEnd();writer.visitEnd();byte[] bytes=writer.toByteArray();return defineClass(name,bytes,0,bytes.length);
        }
    }
}
