package net.forbric.kernel.transform;

import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.util.*;
import java.lang.reflect.*;
import net.fabricmc.api.EnvType;
import net.forbric.kernel.boot.*;
import net.forbric.kernel.boot.DefinedMethodContracts.MethodContract;
import net.forbric.kernel.boot.KernelPredicateSeams.*;
import net.forbric.kernel.boot.KernelSharedPredicateContracts.*;
import net.forbric.kernel.mixin.MixinInstructionFingerprint;
import net.forbric.kernel.mixin.SharedFinalSourceCertifier;
import org.objectweb.asm.*;
import org.objectweb.asm.tree.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.api.parallel.ResourceLock;

/** Executes transparent records and the production leaf/continuation scope over renamed independent programs. */
@ResourceLock("system-properties")
class PredicateGetterResultRecorderExecutionTest {
 private static final String OWNER="fixture/records/Mirror",RUNTIME="net/forbric/kernel/runtime/",OP="com/llamalad7/mixinextras/injector/wrapoperation/Operation";
 private static final Handle LAMBDA=new Handle(Opcodes.H_INVOKESTATIC,"java/lang/invoke/LambdaMetafactory","metafactory","(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;",false);
 @AfterEach void clean(){System.clearProperty(PredicateGetterResultRecorder.PROPERTY);}
 @Test void inactiveGettersKeepExactResultCountExceptionAndOffBytes(@TempDir Path work)throws Throwable{
  Fixture f=fixture(work,true);Object mirror=InjectorExecution.construct(f.loader.loadClass(OWNER.replace('/','.')));Object first=InjectorExecution.invoke(mirror,"ground");assertSame(first,InjectorExecution.invoke(mirror,"ground"));assertEquals(2,field(mirror,"getters"));
  IllegalStateException failure=new IllegalStateException("getter-marker");set(mirror,"failure",failure);assertSame(failure,assertThrows(IllegalStateException.class,()->InjectorExecution.invoke(mirror,"ground")));assertEquals(3,field(mirror,"getters"));
  byte[]original=f.original;System.setProperty(PredicateGetterResultRecorder.PROPERTY,"off");assertSame(original,InjectorExecution.transform(new PredicateGetterResultRecorder(),OWNER.replace('/','.'),original,EnvType.SERVER));assertEquals("",InjectorExecution.verify(f.bytes,f.loader));
 }
 @Test void ownedLeavesConsumeOneSharedSourceAndGuardBeforeTheExistingGetter(@TempDir Path work)throws Throwable{Fixture f=fixture(work,true);Object mirror=object(f);assertEquals(true,InjectorExecution.invoke(mirror,"run"));assertEquals("under,guard,getter,ground",field(mirror,"order"));assertEquals(1,field(mirror,"underCalls"));assertEquals(1,field(mirror,"groundCalls"));assertEquals(1,field(mirror,"guards"));assertEquals(1,field(mirror,"getters"));assertEquals(1,field(mirror,"nativeQueries"));}
 @Test void sourceGuardShortCircuitsAndHostCleanupPreventsAStaleGuard(@TempDir Path work)throws Throwable{Fixture f=fixture(work,true);Object mirror=object(f);set(mirror,"blocked",true);assertEquals(false,InjectorExecution.invoke(mirror,"run"));assertEquals("under,guard",field(mirror,"order"));assertEquals(0,field(mirror,"getters"));assertEquals(0,field(mirror,"groundCalls"));assertEquals(true,InjectorExecution.invoke(mirror,"outsideGuard"));assertEquals(2,field(mirror,"guards"));}
 @Test void mixedNativeLeavesRetainTheirOwnDecisionWithoutEarlyReads(@TempDir Path work)throws Throwable{Fixture f=fixture(work,true);Object mirror=object(f);InjectorExecution.invoke(mirror,"nativeGround");assertEquals(false,InjectorExecution.invoke(mirror,"run"));assertEquals(1,field(mirror,"underCalls"));assertEquals(0,field(mirror,"groundCalls"));assertEquals(1,field(mirror,"getters"));assertEquals(1,field(mirror,"nativeLeaves"));mirror=object(f);InjectorExecution.invoke(mirror,"nativeEye");assertEquals(false,InjectorExecution.invoke(mirror,"run"));assertEquals(0,field(mirror,"underCalls"));assertEquals(0,field(mirror,"guards"));assertEquals(0,field(mirror,"getters"));assertEquals(1,field(mirror,"nativeLeaves"));}
 @Test void nativeTruePredecessorNeverMisroutesTheSecondOwnedLeafAsUnder(@TempDir Path work)throws Throwable{Fixture f=fixture(work,true);Object mirror=object(f);InjectorExecution.invoke(mirror,"nativeEyeTrue");assertEquals(false,InjectorExecution.invoke(mirror,"run"));assertEquals(0,field(mirror,"underCalls"));assertEquals(0,field(mirror,"groundCalls"));assertEquals(0,field(mirror,"guards"));assertEquals(1,field(mirror,"getters"));assertEquals(2,field(mirror,"nativeLeaves"));mirror=object(f);InjectorExecution.invoke(mirror,"nativeEyeTrue");set(mirror,"ownedDefault",true);assertEquals(true,InjectorExecution.invoke(mirror,"run"));assertEquals(0,field(mirror,"underCalls"));assertEquals(0,field(mirror,"groundCalls"));assertEquals(1,field(mirror,"getters"));assertEquals(1,field(mirror,"guards"));assertEquals("getter,guard",field(mirror,"order"));}
 @Test void exceptionsNestedActivationsAndOtherThreadsRestoreEveryScope(@TempDir Path work)throws Throwable{Fixture f=fixture(work,true);Object outer=object(f),inner=object(f);set(outer,"nested",inner);assertEquals(true,InjectorExecution.invoke(outer,"run"));assertEquals(1,field(outer,"underCalls"));assertEquals(1,field(inner,"underCalls"));IllegalStateException marker=new IllegalStateException("source-marker");set(outer,"sourceFailure",marker);assertSame(marker,assertThrows(IllegalStateException.class,()->InjectorExecution.invoke(outer,"run")));assertEquals(false,InjectorExecution.invoke(outer,"outsideEye"));assertEquals(true,InjectorExecution.invoke(outer,"threadProbe"));set(outer,"sourceFailure",null);set(outer,"nested",null);set(outer,"order","");assertEquals(true,InjectorExecution.invoke(outer,"run"));assertEquals("under,guard,getter,ground",field(outer,"order"));assertEquals(3,field(outer,"underCalls"));assertEquals(1,field(inner,"underCalls"));assertEquals(2,field(outer,"groundCalls"));assertEquals(false,InjectorExecution.invoke(outer,"outsideEye"));}
 @Test void changedActualNativeSubjectCannotConsumeTheSourceActivation(@TempDir Path work)throws Throwable{Fixture f=fixture(work,true);Object owner=object(f),other=object(f);assertEquals(false,InjectorExecution.invoke(owner,"changedSubject",other));assertEquals(0,field(owner,"underCalls"));assertEquals(0,field(owner,"groundCalls"));assertEquals(0,field(other,"underCalls"));assertEquals(1,field(other,"nativeLeaves"));}
 @Test void missingRecordsFailThePinnedDefinitionGateBeforeAnySourceLeaf(@TempDir Path work)throws Throwable{Fixture f=fixture(work,false);Object mirror=object(f);assertEquals(false,InjectorExecution.invoke(mirror,"run"));assertEquals(0,field(mirror,"underCalls"));assertEquals(0,field(mirror,"groundCalls"));assertEquals(0,field(mirror,"getters"));assertEquals(1,field(mirror,"nativeLeaves"));}
 private record Fixture(ClassLoader loader,byte[]original,byte[]bytes,String key){ }
 private static Fixture fixture(Path work,boolean recorded)throws Exception{
  Map<String,String>sources=new LinkedHashMap<>();sources.put("net.neoforged.neoforge.fluids.FluidType","package net.neoforged.neoforge.fluids;public class FluidType{public boolean respond(fixture.records.Mirror receiver){receiver.nativeLeaves++;return false;}}");
  sources.put(OP.replace('/','.'),"package com.llamalad7.mixinextras.injector.wrapoperation;public interface Operation<T>{T call(Object...arguments);}");
  sources.put("net.forbric.kernel.runtime.KernelFabricFluidBehaviors","""
   package net.forbric.kernel.runtime;import fixture.records.Mirror;import net.neoforged.neoforge.fluids.FluidType;
   public class KernelFabricFluidBehaviors{public static boolean enabled(){return true;}public static boolean ownsNeoType(FluidType value){return value instanceof NeoType;}
    public static final class NeoType extends FluidType{public boolean respond(Mirror receiver){var frame=StackWalker.getInstance(StackWalker.Option.RETAIN_CLASS_REFERENCE).walk(s->s.findFirst().orElseThrow());Boolean answer=KernelSharedPredicateScopes.answer(this,receiver,frame);if(answer!=null)return answer;receiver.nativeLeaves++;return receiver.ownedDefault;}}
   }
   """);
  sources.put("fixture.records.Mirror","""
   package fixture.records;import java.util.*;import net.neoforged.neoforge.fluids.FluidType;import net.forbric.kernel.runtime.*;import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
   public class Mirror{public String key,order="";public int getters,guards,underCalls,groundCalls,nativeQueries,nativeLeaves;public boolean blocked,ownedDefault;public RuntimeException failure,sourceFailure;public Mirror nested;private final Map<Object,Object>view=new LinkedHashMap<>();private boolean ready=true;private FluidType eye=new KernelFabricFluidBehaviors.NeoType(),feet=new KernelFabricFluidBehaviors.NeoType();
    private static final Object TAG=new Object();
    private void add(String s){order+=(order.isEmpty()?"":",")+s;}public void refresh(){}
    public FluidType ground(){getters++;add("getter");if(failure!=null)throw failure;return feet;}
    public boolean gate(){guards++;add("guard");return blocked;}
    private boolean sourceUnder(boolean original,Object reference){underCalls++;add("under");if(sourceFailure!=null)throw sourceFailure;if(nested!=null)nested.run();return true;}
    private boolean sourceGround(Mirror state,Object tag,Operation<Boolean> original,Object reference){if(state!=this)throw new AssertionError("wrong recorded SSA receiver");groundCalls++;add("ground");return true;}
    public boolean nativeUnder(){return false;}public boolean membership(Object tag){return false;}
    private boolean under(Object reference){throw new AssertionError("source seam must be emitted");}
    private boolean standing(Object reference,Mirror state){throw new AssertionError("source seam must be emitted");}
    private boolean typed(Object reference,Object state){return standing(reference,(Mirror)state);}
    private boolean query(){nativeQueries++;return eye.respond(this)&&ground().respond(this);}
    public boolean run(){Object reference=new Object();return(Boolean)KernelSharedPredicateScopes.host(this,key,()->KernelSharedPredicateScopes.query(this,key,()->query(),()->under(reference),state->typed(reference,state))&&!KernelSharedPredicateScopes.guard(this,key,"closed-gate",()->gate()));}
    public boolean changedSubject(Mirror other){Object reference=new Object();return(Boolean)KernelSharedPredicateScopes.host(this,key,()->KernelSharedPredicateScopes.query(this,key,()->other.query(),()->under(reference),state->typed(reference,state)));}public boolean outsideEye(){return eye.respond(this);}public boolean outsideGuard(){return KernelSharedPredicateScopes.guard(this,key,"closed-gate",()->gate());}
    public void nativeGround(){feet=new FluidType();}public void nativeEye(){eye=new FluidType();}public void nativeEyeTrue(){eye=new FluidType(){public boolean respond(Mirror receiver){receiver.nativeLeaves++;return true;}};}
    public boolean threadProbe()throws Exception{boolean[]result={true};Thread t=new Thread(()->result[0]=outsideEye());t.start();t.join(5000);return !t.isAlive()&&!result[0];}
   }
   """);
  List<Path>files=new ArrayList<>();for(var entry:sources.entrySet()){Path path=work.resolve("sources").resolve(entry.getKey().replace('.','/')+".java");Files.createDirectories(path.getParent());Files.writeString(path,entry.getValue());files.add(path);}Path repository=Path.of(System.getProperty("user.dir"));files.add(repository.resolve("src/runtime/java/"+RUNTIME+"KernelSharedPredicateScopes.java"));files.add(repository.resolve("src/runtime/java/"+RUNTIME+"KernelFluidPredicateSeams.java"));
  Map<String,byte[]>classes=new HashMap<>(InjectorExecution.compile(work,files));ClassNode compiled=parse(classes.get(OWNER));Seam seam=emitSourceSeam(compiled);byte[]original=write(compiled),output=InjectorExecution.transform(new PredicateGetterResultRecorder(),OWNER.replace('/','.'),original,EnvType.SERVER);assertNotSame(original,output);
  ClassNode before=parse(original),after=parse(output);MethodNode getter=method(before,"ground","()Lnet/neoforged/neoforge/fluids/FluidType;"),emitted=method(after,getter.name,getter.desc),update=method(after,"refresh","()V");String schema="fixture-tag-"+MixinInstructionFingerprint.hash(update);
  KernelTagSourceContracts.register(schema,new KernelTagSourceContracts.Schema(OWNER,"view","ready","fixture/records/Tracker","fixture/records/Tag",contract(OWNER,update),List.of(),List.of(),Map.of(),List.of(),null,null));
  MethodNode query=method(after,"query","()Z");List<Integer>sites=callOffsets(query,"respond");assertEquals(2,sites.size());Site site=new Site(OWNER,getter.name,getter.desc,MixinInstructionFingerprint.hash(getter));String key=KernelSharedPredicateContracts.register(new KernelSharedPredicateContracts.Contract(List.of(),List.of(contract(OWNER,emitted),contract(OWNER,query)),Map.of(OWNER.replace('/','.')+"#"+emitted.name+emitted.desc,emitted.access,OWNER.replace('/','.')+"#"+query.name+query.desc,query.access),List.of(),"respond","(Lfixture/records/Mirror;)Z",null,new Leaf(contract(OWNER,query),sites.get(0)),new Leaf(contract(OWNER,query),sites.get(1)),site,new Site(OWNER,"under","(Ljava/lang/Object;)Z","source"),"closed-gate",schema,new Root(0)));
  List<MethodNode>remaining=after.methods.stream().filter(m->!m.name.equals("<init>")&&!m.name.equals("<clinit>")&&!Set.of("sourceUnder","sourceGround","under","standing","relay").contains(m.name)).toList();SharedFinalSourceCertifier.remember(key,OWNER,OWNER,seam.originalUnder,seam.originalGround,seam.under,seam.ground,remaining,seam.underAnchor,seam.groundAnchor);assertEquals(Set.of(key),SharedFinalSourceCertifier.certify(after).keySet(),"the scope fixture must carry a real final source witness");
  classes.put(OWNER,recorded?output:original);
  ClassLoader loader=InjectorExecution.load(classes);loader.loadClass(OWNER.replace('/','.'));DefinedMethodContracts.observe(loader,OWNER,classes.get(OWNER));SharedFinalSourceContracts.observeDefinition(loader,OWNER,classes.get(OWNER));Class<?>owned=loader.loadClass("net.forbric.kernel.runtime.KernelFabricFluidBehaviors$NeoType");DefinedMethodContracts.observe(loader,owned.getName(),classes.get(owned.getName().replace('.','/')));Object proofSubject=loader.loadClass(OWNER.replace('/','.')).getConstructor().newInstance();assertEquals(recorded,SharedFinalSourceContracts.permits(proofSubject,key),"only the actually observed and authenticated final body may enable the source scope");return new Fixture(loader,original,output,key);
 }
 /** A renamed bytecode fixture carries the same source/helper/Operation shape as the production final verifier.
  * The source bodies below are independently compiled counters/throws/nesting, rather than a fabricated token. */
 private record Seam(MethodNode originalUnder,MethodNode originalGround,MethodNode under,MethodNode ground,MethodInsnNode underAnchor,MethodInsnNode groundAnchor){ }
 private static Seam emitSourceSeam(ClassNode target){
  MethodNode sourceUnder=method(target,"sourceUnder","(ZLjava/lang/Object;)Z"),sourceGround=method(target,"sourceGround","(L"+OWNER+";Ljava/lang/Object;L"+OP+";Ljava/lang/Object;)Z");
  MethodInsnNode ua=new MethodInsnNode(Opcodes.INVOKEVIRTUAL,OWNER,"nativeUnder","()Z",false),ga=new MethodInsnNode(Opcodes.INVOKEVIRTUAL,OWNER,"membership","(Ljava/lang/Object;)Z",false);
  MethodNode u=new MethodNode(Opcodes.ACC_PRIVATE,"under","(Ljava/lang/Object;)Z",null,null);unique(u);LabelNode fail=new LabelNode();u.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));u.instructions.add(call(ua));u.instructions.add(new JumpInsnNode(Opcodes.IFEQ,fail));u.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));u.instructions.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL,OWNER,"gate","()Z",false));u.instructions.add(new InsnNode(Opcodes.DUP));u.instructions.add(new LdcInsnNode("closed-gate"));u.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME+"KernelSharedPredicateScopes","recordGuard","(ZLjava/lang/String;)V",false));u.instructions.add(new JumpInsnNode(Opcodes.IFNE,fail));u.instructions.add(new InsnNode(Opcodes.ICONST_1));u.instructions.add(new InsnNode(Opcodes.IRETURN));u.instructions.add(fail);u.instructions.add(new InsnNode(Opcodes.ICONST_0));u.instructions.add(new InsnNode(Opcodes.IRETURN));
  MethodNode g=new MethodNode(Opcodes.ACC_PRIVATE,"standing","(Ljava/lang/Object;L"+OWNER+";)Z",null,null);unique(g);g.instructions.add(new VarInsnNode(Opcodes.ALOAD,2));g.instructions.add(new FieldInsnNode(Opcodes.GETSTATIC,OWNER,"TAG","Ljava/lang/Object;"));g.instructions.add(call(ga));g.instructions.add(new InsnNode(Opcodes.IRETURN));
  MethodNode finalU=copy(u);MethodInsnNode anchor=Arrays.stream(finalU.instructions.toArray()).filter(i->i instanceof MethodInsnNode m&&m.name.equals(ua.name)).map(MethodInsnNode.class::cast).findFirst().orElseThrow();InsnList injected=new InsnList();injected.add(new VarInsnNode(Opcodes.ALOAD,0));injected.add(new InsnNode(Opcodes.SWAP));injected.add(new VarInsnNode(Opcodes.ALOAD,1));injected.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,OWNER,sourceUnder.name,sourceUnder.desc,false));finalU.instructions.insert(anchor,injected);
  MethodNode finalG=copy(g);finalG.instructions.clear();finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,2));finalG.instructions.add(new FieldInsnNode(Opcodes.GETSTATIC,OWNER,"TAG","Ljava/lang/Object;"));finalG.instructions.add(new VarInsnNode(Opcodes.ASTORE,4));finalG.instructions.add(new VarInsnNode(Opcodes.ASTORE,3));finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,3));finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,4));finalG.instructions.add(new InvokeDynamicInsnNode("call","()L"+OP+";",LAMBDA,org.objectweb.asm.Type.getMethodType("([Ljava/lang/Object;)Ljava/lang/Object;"),new Handle(Opcodes.H_INVOKESTATIC,OWNER,"relay","([Ljava/lang/Object;)Ljava/lang/Boolean;",false),org.objectweb.asm.Type.getMethodType("([Ljava/lang/Object;)Ljava/lang/Boolean;")));finalG.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));finalG.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,OWNER,sourceGround.name,sourceGround.desc,false));finalG.instructions.add(new InsnNode(Opcodes.IRETURN));
  MethodNode relay=new MethodNode(Opcodes.ACC_PRIVATE|Opcodes.ACC_STATIC|Opcodes.ACC_SYNTHETIC,"relay","([Ljava/lang/Object;)Ljava/lang/Boolean;",null,null);relay.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));relay.instructions.add(new InsnNode(Opcodes.ICONST_0));relay.instructions.add(new InsnNode(Opcodes.AALOAD));relay.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,OWNER));relay.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));relay.instructions.add(new InsnNode(Opcodes.ICONST_1));relay.instructions.add(new InsnNode(Opcodes.AALOAD));relay.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,"java/lang/Object"));relay.instructions.add(call(ga));relay.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,"java/lang/Boolean","valueOf","(Z)Ljava/lang/Boolean;",false));relay.instructions.add(new InsnNode(Opcodes.ARETURN));
  target.methods.removeIf(m->m.name.equals("under")||m.name.equals("standing"));target.methods.add(finalU);target.methods.add(finalG);target.methods.add(relay);for(MethodNode method:target.methods)if(!method.name.equals("<init>")&&!method.name.equals("<clinit>"))merged(method);
  return new Seam(copy(sourceUnder),copy(sourceGround),u,g,ua,ga);
 }
 private static void unique(MethodNode method){method.visibleAnnotations=new ArrayList<>(List.of(new AnnotationNode("Lorg/spongepowered/asm/mixin/Unique;")));}
 private static void merged(MethodNode method){if(method.visibleAnnotations==null)method.visibleAnnotations=new ArrayList<>();AnnotationNode merged=new AnnotationNode("Lorg/spongepowered/asm/mixin/transformer/meta/MixinMerged;");merged.values=new ArrayList<>(List.of("mixin",OWNER.replace('/','.')));method.visibleAnnotations.add(merged);}
 private static MethodNode copy(MethodNode method){MethodNode copy=new MethodNode(method.access,method.name,method.desc,null,null);method.accept(copy);for(AbstractInsnNode instruction:copy.instructions)if(instruction instanceof InvokeDynamicInsnNode dynamic)dynamic.bsmArgs=dynamic.bsmArgs.clone();return copy;}
 private static MethodInsnNode call(MethodInsnNode instruction){return new MethodInsnNode(instruction.getOpcode(),instruction.owner,instruction.name,instruction.desc,instruction.itf);}
 private static byte[]write(ClassNode owner){ClassWriter writer=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);owner.accept(writer);return writer.toByteArray();}
 private static Object object(Fixture f)throws Throwable{Object mirror=InjectorExecution.construct(f.loader.loadClass(OWNER.replace('/','.')));set(mirror,"key",f.key);return mirror;}
 private static void set(Object receiver,String name,Object value)throws Exception{receiver.getClass().getField(name).set(receiver,value);}private static Object field(Object receiver,String name)throws Exception{return receiver.getClass().getField(name).get(receiver);}
 private static List<Integer>callOffsets(MethodNode method,String target){List<Integer>result=new ArrayList<>();int offset=0;for(var instruction:method.instructions){if(instruction.getOpcode()<0)continue;if(instruction instanceof MethodInsnNode call){if(call.name.equals(target))result.add(offset);offset+=call.getOpcode()==Opcodes.INVOKEINTERFACE?5:3;}else if(instruction instanceof FieldInsnNode||instruction instanceof TypeInsnNode||instruction instanceof JumpInsnNode)offset+=3;else if(instruction instanceof VarInsnNode variable){assertTrue(variable.var<256);offset+=variable.var<4?1:2;}else if(instruction instanceof InsnNode)offset++;else throw new AssertionError("unproved bytecode width "+instruction);}return result;}
 private static MethodContract contract(String owner,MethodNode method){return new MethodContract(owner,method.name,method.desc,DefinedMethodContracts.fingerprint(method));}
 private static MethodNode method(ClassNode owner,String name,String desc){return owner.methods.stream().filter(m->m.name.equals(name)&&m.desc.equals(desc)).findFirst().orElseThrow();}
 private static ClassNode parse(byte[]bytes){ClassNode node=new ClassNode();new ClassReader(bytes).accept(node,ClassReader.EXPAND_FRAMES);return node;}
}
