/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;
import java.util.*;import java.util.function.Function;
import org.objectweb.asm.*;import org.objectweb.asm.tree.*;

/** Carry the authored sound-group callback into native playback, with lazy native lookup and exact block position. */
public final class CreateEntitySoundMixinAdapter {
	public static final String PROPERTY="forbric.createEntitySounds";
	private static final String STATE="net/minecraft/world/level/block/state/BlockState", POS="net/minecraft/core/BlockPos", OP=MixinWrapOperationShim.OPERATION, SCOPE="net/forbric/kernel/interop/CreateSoundScope";
	private CreateEntitySoundMixinAdapter() { }
	public static int adapt(ClassNode mixin,Function<String,ClassNode> targets){
		boolean fall=mixin.name.equals("com/zurrtum/create/mixin/LivingEntityMixin");if((!fall&&!mixin.name.equals("com/zurrtum/create/mixin/EntityMixin"))||"off".equalsIgnoreCase(System.getProperty(PROPERTY)))return 0;
		MethodNode original=CreateInjectionAdapters.named(mixin,fall?"getBlockFallSound":"getStepSound");String targetName=fall?"net/minecraft/world/entity/LivingEntity":"net/minecraft/world/entity/Entity";ClassNode target=targets.apply(targetName);
		if(original==null||target==null||MixinFit.injectorOf(original)==null||!Type.getReturnType(original.desc).equals(Type.getObjectType("net/minecraft/world/level/block/SoundType")))return 0;
		String callDesc=fall?"(Lnet/minecraft/world/level/Level;L"+POS+";Lnet/minecraft/world/entity/LivingEntity;)V":"(Lnet/minecraft/world/level/Level;L"+POS+";Lnet/minecraft/world/entity/Entity;FF)V";
		List<String> hosts=new ArrayList<>();for(MethodNode method:target.methods)if((fall?Set.of("playBlockFallSound"):Set.of("playStepSound","playCombinationStepSounds","playMuffledStepSound")).contains(method.name)&&CarpetMixinAdapter.count(method,"L"+STATE+";"+(fall?"playFallSound":"playStepSound")+callDesc)>0)hosts.add(method.name+method.desc);
		if(hosts.size()!=(fall?1:3))return 0;AnnotationNode annotation=MixinFit.injectorOf(original);CarpetMixinAdapter.set(annotation,"method",hosts);CarpetMixinAdapter.set(MixinFit.atNodes(annotation).getFirst(),"target","L"+STATE+";"+(fall?"playFallSound":"playStepSound")+callDesc);
		MethodNode callback=callback(mixin,original,fall);mixin.methods.add(callback);
		MethodNode wrapper=new MethodNode(Opcodes.ACC_PRIVATE,original.name,"(L"+STATE+";"+callDesc.substring(1,callDesc.indexOf(')'))+"L"+OP+";)V",null,null);wrapper.visibleAnnotations=new ArrayList<>(List.of(annotation));
		original.name+="$forbricOriginal";CreateInjectionAdapters.removeInjector(original,annotation);original.invisibleParameterAnnotations=null;original.visibleParameterAnnotations=null;
		InsnList c=wrapper.instructions;c.add(new VarInsnNode(Opcodes.ALOAD,0));c.add(new InvokeDynamicInsnNode("apply","(L"+mixin.name+";)Ljava/util/function/Function;",new Handle(Opcodes.H_INVOKESTATIC,"java/lang/invoke/LambdaMetafactory","metafactory","(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;",false),Type.getMethodType("(Ljava/lang/Object;)Ljava/lang/Object;"),new Handle(Opcodes.H_INVOKEVIRTUAL,mixin.name,callback.name,callback.desc,false),Type.getMethodType("([Ljava/lang/Object;)Ljava/lang/Object;")));
		c.add(new MethodInsnNode(Opcodes.INVOKESTATIC,SCOPE,"enter","(Ljava/util/function/Function;)Ljava/lang/Object;",false));int op=fall?5:7,prev=op+1;c.add(new VarInsnNode(Opcodes.ASTORE,prev));LabelNode start=new LabelNode(),end=new LabelNode(),fail=new LabelNode();c.add(start);
		c.add(new VarInsnNode(Opcodes.ALOAD,op));c.add(new IntInsnNode(Opcodes.BIPUSH,op-1));c.add(new TypeInsnNode(Opcodes.ANEWARRAY,"java/lang/Object"));for(int i=0;i<op-1;i++){c.add(new InsnNode(Opcodes.DUP));c.add(new IntInsnNode(Opcodes.BIPUSH,i));c.add(new VarInsnNode(i<4?Opcodes.ALOAD:Opcodes.FLOAD,i+1));if(i>=4)c.add(new MethodInsnNode(Opcodes.INVOKESTATIC,"java/lang/Float","valueOf","(F)Ljava/lang/Float;",false));c.add(new InsnNode(Opcodes.AASTORE));}
		c.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,OP,"call","([Ljava/lang/Object;)Ljava/lang/Object;",true));c.add(new InsnNode(Opcodes.POP));c.add(end);leave(c,prev);c.add(new InsnNode(Opcodes.RETURN));c.add(fail);
		List<Object> locals=new ArrayList<>(List.of(mixin.name,STATE,"net/minecraft/world/level/Level",POS,fall?"net/minecraft/world/entity/LivingEntity":"net/minecraft/world/entity/Entity"));if(!fall){locals.add(Opcodes.FLOAT);locals.add(Opcodes.FLOAT);}locals.add(OP);locals.add("java/lang/Object");c.add(new FrameNode(Opcodes.F_FULL,locals.size(),locals.toArray(),1,new Object[]{"java/lang/Throwable"}));c.add(new VarInsnNode(Opcodes.ASTORE,prev+1));leave(c,prev);c.add(new VarInsnNode(Opcodes.ALOAD,prev+1));c.add(new InsnNode(Opcodes.ATHROW));wrapper.tryCatchBlocks.add(new TryCatchBlockNode(start,end,fail,null));wrapper.maxStack=7;wrapper.maxLocals=prev+2;mixin.methods.add(wrapper);return 1;
	}
	private static void leave(InsnList c,int slot){c.add(new VarInsnNode(Opcodes.ALOAD,slot));c.add(new MethodInsnNode(Opcodes.INVOKESTATIC,SCOPE,"leave","(Ljava/lang/Object;)V",false));}
	private static MethodNode callback(ClassNode mixin,MethodNode original,boolean fall){MethodNode fn=new MethodNode(Opcodes.ACC_PRIVATE,"forbric$"+(fall?"fall":"step")+"SoundCallback","([Ljava/lang/Object;)Ljava/lang/Object;",null,null);InsnList c=fn.instructions;c.add(new VarInsnNode(Opcodes.ALOAD,0));element(c,0,STATE);element(c,2,"java/util/function/Supplier");c.add(new MethodInsnNode(Opcodes.INVOKESTATIC,MixinWrapOperationShim.RUNTIME,"supplied","(Ljava/util/function/Supplier;)L"+OP+";",false));if(fall)for(String name:List.of("getX","getY","getZ")){element(c,1,POS);c.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL,POS,name,"()I",false));}else element(c,1,POS);c.add(MixinHandlerShim.callOwn(mixin,false,original.name+"$forbricOriginal",original.desc));c.add(new InsnNode(Opcodes.ARETURN));fn.maxStack=7;fn.maxLocals=2;return fn;}
	private static void element(InsnList c,int index,String type){c.add(new VarInsnNode(Opcodes.ALOAD,1));c.add(new IntInsnNode(Opcodes.BIPUSH,index));c.add(new InsnNode(Opcodes.AALOAD));c.add(new TypeInsnNode(Opcodes.CHECKCAST,type));}
}
