/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;

import java.util.*;
import java.util.function.Function;
import org.objectweb.asm.*;
import org.objectweb.asm.tree.*;
import static net.forbric.kernel.mixin.PredicateDecisionGraph.*;

/** Relates the native source short-circuit cluster to a typed host's pre-event predicate island. */
final class CrossHostPredicateIslandPlan implements Opcodes {
    record Member(String owner,String name,String descriptor){}
    record Plan(String owner,MethodNode method,MethodInsnNode caller,AbstractInsnNode start,AbstractInsnNode end,
                int interactionLocal,int primaryLocal,int boolLocal,int consumeLocal,Member interactionGetter,Member query,
                Member anyTypeQuestion,Member typedActorQuestion,Member protection,NativeSourcePredicateIsland.Extraction source){}
    private CrossHostPredicateIslandPlan(){}
    static Plan derive(String actorOwner,MethodNode caller,NativeSourcePredicateIsland.Extraction source,Function<String,ClassNode> classes){
        try{return checked(actorOwner,caller,source,classes);}catch(RuntimeException unknown){return null;}
    }
    private static Plan checked(String actor,MethodNode caller,NativeSourcePredicateIsland.Extraction source,Function<String,ClassNode> classes){
        List<MethodInsnNode>candidates=new ArrayList<>();for(AbstractInsnNode i:caller.instructions)if(i instanceof MethodInsnNode call&&call.getOpcode()==INVOKESTATIC){Type[]args=Type.getArgumentTypes(call.desc);if(Type.getReturnType(call.desc)==Type.VOID_TYPE&&args.length==4&&args[0].getDescriptor().equals("L"+actor+";")&&args[1].getDescriptor().equals("L"+source.worldType()+";")&&args[2]==Type.INT_TYPE&&args[3]==Type.INT_TYPE)candidates.add(call);}
        if(candidates.size()!=1)return null;MethodInsnNode dispatch=candidates.getFirst();ClassNode host=classes.apply(dispatch.owner);if(host==null)return null;MethodNode method=find(host,dispatch.name,dispatch.desc);if(method==null||(method.access&ACC_STATIC)==0||(method.access&(ACC_ABSTRACT|ACC_NATIVE|ACC_SYNCHRONIZED))!=0||!method.tryCatchBlocks.isEmpty())return null;
        Logical logical=logical(method);if(logical==null)return null;MethodNode compared=logical.method();List<AbstractInsnNode>body=code(compared);if(body.size()<12||!aload(body.get(0),0)||!(body.get(1)instanceof MethodInsnNode getter&&getter.getOpcode()==INVOKEVIRTUAL&&Type.getReturnType(getter.desc).getSort()==Type.OBJECT&&Type.getArgumentTypes(getter.desc).length==0)||!(body.get(2)instanceof VarInsnNode saved&&saved.getOpcode()==ASTORE))return null;
        AbstractInsnNode end=null;int eventAt=-1;for(int i=3;i<body.size();i++)if(body.get(i)instanceof TypeInsnNode allocation&&allocation.getOpcode()==NEW){end=allocation;eventAt=i;break;}
        if(eventAt<0||eventAt+6>=body.size()||body.get(eventAt+1).getOpcode()!=DUP||!aload(body.get(eventAt+2),0)||!(body.get(eventAt+3)instanceof VarInsnNode breathe&&breathe.getOpcode()==ILOAD)||!(body.get(eventAt+4)instanceof VarInsnNode amount&&amount.getOpcode()==ILOAD&&amount.var==2)||!(body.get(eventAt+5)instanceof VarInsnNode consume&&consume.getOpcode()==ILOAD&&consume.var==3)||!(body.get(eventAt+6)instanceof MethodInsnNode constructor&&constructor.getOpcode()==INVOKESPECIAL&&constructor.owner.equals(((TypeInsnNode)end).desc)&&constructor.name.equals("<init>")&&constructor.desc.equals("(L"+actor+";ZII)V")))return null;
        int primaryLocal=-1;for(int n=3;n<eventAt-2;n++)if(body.get(n)instanceof VarInsnNode store&&store.getOpcode()==ISTORE&&body.get(n+1)instanceof VarInsnNode load&&load.getOpcode()==ILOAD&&load.var==store.var&&body.get(n+2)instanceof VarInsnNode copy&&copy.getOpcode()==ISTORE&&copy.var==breathe.var){if(primaryLocal>=0)return null;primaryLocal=store.var;}if(primaryLocal<0)return null;
        Function<Expr,Expr>normalize=value->canonical(value,source.worldGetter(),classes);
        Tree nativeTree=PredicateDecisionGraph.helper(source.helper(),normalize),currentTree=PredicateDecisionGraph.eventPredicate(compared,end,breathe.var,consume.var,normalize);
        if(!(nativeTree instanceof Test eye)||!result(eye.no(),3)||!(eye.yes()instanceof Test bubble)||!result(bubble.yes(),3)||!(bubble.no()instanceof Test protection)||!result(protection.yes(),1)||!(protection.no()instanceof Test effect)||!result(effect.yes(),1)||!(effect.no()instanceof Test kind)||!result(kind.no(),0)||!(kind.yes()instanceof Test immune)||!result(immune.yes(),1)||!result(immune.no(),0))return null;
        if(!(currentTree instanceof Test any)||!result(any.no(),3)||!(any.yes()instanceof Test currentBubble)||!result(currentBubble.yes(),3)||!(currentBubble.no()instanceof Test currentEffect)||!result(currentEffect.yes(),1)||!(currentEffect.no()instanceof Test typed)||!result(typed.no(),1)||!(typed.yes()instanceof Test currentKind)||!result(currentKind.no(),0)||!(currentKind.yes()instanceof Test currentImmune)||!result(currentImmune.yes(),1)||!result(currentImmune.no(),0))return null;
        if(!bubble.condition().equals(currentBubble.condition())||!effect.condition().equals(currentEffect.condition())||!kind.condition().equals(currentKind.condition())||!immune.condition().equals(currentImmune.condition()))return null;
        if(!protection.condition().operation().equals("call")||protection.condition().inputs().size()!=1||!protection.condition().inputs().getFirst().equals(Expr.root(0)))return null;Member protects=member(protection.condition());if(protects==null||!protects.descriptor.equals("()Z"))return null;
        if(!any.condition().operation().equals("call")||!typed.condition().operation().equals("call")||!any.condition().symbol().equals(typed.condition().symbol())||any.condition().inputs().size()!=3||typed.condition().inputs().size()!=3||!any.condition().inputs().subList(0,2).equals(typed.condition().inputs().subList(0,2)))return null;
        Member query=member(any.condition()),anyLambda=member(any.condition().inputs().get(2)),typedLambda=member(typed.condition().inputs().get(2));if(query==null||anyLambda==null||typedLambda==null||!anyLambda.owner.equals(host.name)||!typedLambda.owner.equals(host.name))return null;
        MethodNode first=find(host,anyLambda.name,anyLambda.descriptor),second=find(host,typedLambda.name,typedLambda.descriptor);if(first==null||second==null)return null;
        Member air=negatedTypeQuestion(first),drowning=actorTypeQuestion(second);if(air==null||drowning==null)return null;
        if(!any.condition().inputs().get(1).equals(Expr.root(0))||!any.condition().inputs().getFirst().equals(canonical(new Expr("call",getter.getOpcode()+":"+getter.owner+"."+getter.name+getter.desc,List.of(Expr.root(0))),source.worldGetter(),classes)))return null;
        return new Plan(host.name,method,dispatch,logical.original().get(body.get(3)),logical.original().get(end),saved.var,primaryLocal,breathe.var,consume.var,new Member(getter.owner,getter.name,getter.desc),query,air,drowning,protects,source);
    }
    private record Logical(MethodNode method,Map<AbstractInsnNode,AbstractInsnNode>original){}
    /** The existing kernel observation seam is an exact transparent decoration on the native fallback.
     * It remains in the executable host; only this logical comparison removes its three complete recipes. */
    private static Logical logical(MethodNode actual){
        MethodNode copy=new MethodNode(actual.access,actual.name,actual.desc,actual.signature,actual.exceptions.toArray(String[]::new));actual.accept(copy);
        Map<AbstractInsnNode,AbstractInsnNode>original=new IdentityHashMap<>();AbstractInsnNode[]a=actual.instructions.toArray(),b=copy.instructions.toArray();for(int i=0;i<a.length;i++)original.put(b[i],a[i]);
        String runtime="net/forbric/kernel/runtime/KernelFluidBreathing",observation="L"+runtime+"$Observation;";List<MethodInsnNode>calls=new ArrayList<>();for(var i:copy.instructions)if(i instanceof MethodInsnNode c&&c.owner.equals(runtime))calls.add(c);
        if(calls.isEmpty())return new Logical(copy,original);if(calls.size()!=3)return null;
        MethodInsnNode enter=null,remember=null,refill=null;for(var c:calls){if(c.getOpcode()!=INVOKESTATIC)return null;if(c.name.equals("observation")&&c.desc.equals("()"+observation))enter=c;else if(c.name.equals("remember")&&c.desc.startsWith("(L")&&c.desc.endsWith(observation+")"+c.desc.substring(1,c.desc.indexOf(';')+1)))remember=c;else if(c.name.equals("refillDefault")&&c.desc.equals("("+Type.getArgumentTypes(actual.desc)[0].getDescriptor()+"I"+observation+")I"))refill=c;else return null;}
        if(enter==null||remember==null||refill==null||next(copy.instructions.getFirst())!=enter||!(next(enter.getNext())instanceof VarInsnNode store&&store.getOpcode()==ASTORE))return null;int slot=store.var;
        AbstractInsnNode remBefore=previous(remember),factory=previous(remBefore),refBefore=previous(refill),amount=previous(refBefore),actor=previous(amount),sink=next(refill.getNext());
        if(!(remBefore instanceof VarInsnNode seen&&seen.getOpcode()==ALOAD&&seen.var==slot)||!(factory instanceof InvokeDynamicInsnNode lambda)||!remember.desc.equals("("+Type.getReturnType(lambda.desc).getDescriptor()+observation+")"+Type.getReturnType(lambda.desc).getDescriptor())||!(refBefore instanceof VarInsnNode seenAgain&&seenAgain.getOpcode()==ALOAD&&seenAgain.var==slot)||!(amount instanceof VarInsnNode value&&value.getOpcode()==ILOAD&&value.var==3)||!aload(actor,0)||!(sink instanceof VarInsnNode result&&result.getOpcode()==ISTORE&&result.var==3))return null;
        int uses=0;for(var i:copy.instructions)if(i instanceof VarInsnNode v&&v.var==slot)uses++;if(uses!=3)return null;
        copy.instructions.remove(enter);copy.instructions.remove(store);copy.instructions.remove(remBefore);copy.instructions.remove(remember);copy.instructions.insertBefore(actor,new InsnNode(ICONST_0));copy.instructions.remove(actor);copy.instructions.remove(amount);copy.instructions.remove(refBefore);copy.instructions.remove(refill);return new Logical(copy,original);
    }
    private static AbstractInsnNode previous(AbstractInsnNode i){i=i.getPrevious();while(i!=null&&i.getOpcode()<0)i=i.getPrevious();return i;}
    private static Member negatedTypeQuestion(MethodNode method){if((method.access&ACC_STATIC)==0||!method.tryCatchBlocks.isEmpty())return null;Type[]args=Type.getArgumentTypes(method.desc);if(args.length!=3||args[0].getSort()!=Type.OBJECT||args[1].getSort()!=Type.OBJECT||args[2]!=Type.DOUBLE_TYPE||Type.getReturnType(method.desc)!=Type.BOOLEAN_TYPE)return null;
        List<AbstractInsnNode>c=code(method);if(c.size()!=7||!aload(c.get(0),1)||!(c.get(1)instanceof MethodInsnNode call&&call.getOpcode()==INVOKEVIRTUAL&&call.owner.equals(args[1].getInternalName())&&call.desc.equals("()Z"))||!(c.get(2)instanceof JumpInsnNode falseBranch&&falseBranch.getOpcode()==IFNE)||c.get(3).getOpcode()!=ICONST_1||!(c.get(4)instanceof JumpInsnNode join&&join.getOpcode()==GOTO)||c.get(5).getOpcode()!=ICONST_0||c.get(6).getOpcode()!=IRETURN||next(falseBranch.label)!=c.get(5)||next(join.label)!=c.get(6))return null;return new Member(call.owner,call.name,call.desc);}
    private static Member actorTypeQuestion(MethodNode method){if((method.access&ACC_STATIC)==0||!method.tryCatchBlocks.isEmpty())return null;Type[]args=Type.getArgumentTypes(method.desc);if(args.length!=3||args[0].getSort()!=Type.OBJECT||args[1].getSort()!=Type.OBJECT||args[2]!=Type.DOUBLE_TYPE||Type.getReturnType(method.desc)!=Type.BOOLEAN_TYPE)return null;List<AbstractInsnNode>c=code(method);if(c.size()!=4||!aload(c.get(0),0)||!aload(c.get(1),1)||!(c.get(2)instanceof MethodInsnNode call&&call.getOpcode()==INVOKEVIRTUAL&&call.owner.equals(args[0].getInternalName())&&call.desc.equals("(L"+args[1].getInternalName()+";)Z"))||c.get(3).getOpcode()!=IRETURN)return null;return new Member(call.owner,call.name,call.desc);}
    private static Expr canonical(Expr original,MethodInsnNode world,Function<String,ClassNode> classes){List<Expr>inputs=original.inputs().stream().map(x->canonical(x,world,classes)).toList();Expr value=new Expr(original.operation(),original.symbol(),inputs);
        if(value.operation().equals("call")){Member member=member(value);if(member==null)return value;String declaration=declaring(member,classes,new HashSet<>());if(declaration!=null)value=new Expr("call",value.symbol().substring(0,value.symbol().indexOf(':')+1)+declaration+"."+member.name+member.descriptor,inputs);
            String worldDecl=declaring(new Member(world.owner,world.name,world.desc),classes,new HashSet<>());if(inputs.equals(List.of(Expr.root(0)))&&member.name.equals(world.name)&&member.descriptor.equals(world.desc)&&Objects.equals(declaration,worldDecl))return Expr.root(1);
        }return value;
    }
    static String declaring(Member member,Function<String,ClassNode> classes,Set<String>seen){if(!seen.add(member.owner))return null;ClassNode type=classes.apply(member.owner);if(type==null)return null;if(find(type,member.name,member.descriptor)!=null)return type.name;if(type.superName!=null){String inherited=declaring(new Member(type.superName,member.name,member.descriptor),classes,seen);if(inherited!=null)return inherited;}for(String face:type.interfaces){String inherited=declaring(new Member(face,member.name,member.descriptor),classes,seen);if(inherited!=null)return inherited;}return null;}
    private static Member member(Expr value){String symbol=value.symbol();if(value.operation().equals("call"))symbol=symbol.substring(symbol.indexOf(':')+1);else if(!value.operation().equals("lambda"))return null;int method=symbol.indexOf('.'),descriptor=symbol.indexOf('(');return method<0||descriptor<0?null:new Member(symbol.substring(0,method),symbol.substring(method+1,descriptor),symbol.substring(descriptor));}
    private static boolean result(Tree tree,int value){return tree.equals(new Result(value));}
    static MethodNode find(ClassNode owner,String name,String desc){return owner.methods.stream().filter(m->m.name.equals(name)&&m.desc.equals(desc)).findFirst().orElse(null);}
    private static List<AbstractInsnNode>code(MethodNode method){List<AbstractInsnNode>out=new ArrayList<>();for(AbstractInsnNode i:method.instructions)if(i.getOpcode()>=0)out.add(i);return out;}
    private static boolean aload(AbstractInsnNode i,int slot){return i instanceof VarInsnNode v&&v.getOpcode()==ALOAD&&v.var==slot;}
    private static AbstractInsnNode next(AbstractInsnNode i){while(i!=null&&i.getOpcode()<0)i=i.getNext();return i;}
}
