/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;

import java.util.*;
import java.util.function.Function;
import net.forbric.kernel.boot.KernelSharedPredicateContracts;
import net.forbric.kernel.boot.KernelSharedPredicateContracts.*;
import org.objectweb.asm.*;
import org.objectweb.asm.tree.*;

/** Restores a source two-leaf shared-reference continuation at a fully closed carrier query. */
public final class MixinSharedPredicateSeam {
 public static final String PROPERTY="forbric.sharedPredicateSeams";
 private static final String REF="com/llamalad7/mixinextras/sugar/ref/LocalRef",OP="com/llamalad7/mixinextras/injector/wrapoperation/Operation",RUNTIME="net/forbric/kernel/runtime/KernelSharedPredicateScopes";
 private static final String WRAP="Lcom/llamalad7/mixinextras/injector/wrapoperation/WrapOperation;",MODIFY="Lcom/llamalad7/mixinextras/injector/ModifyExpressionValue;",SHARE="Lcom/llamalad7/mixinextras/sugar/Share;";
 private static final Handle LAMBDA=new Handle(Opcodes.H_INVOKESTATIC,"java/lang/invoke/LambdaMetafactory","metafactory","(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;",false);
 private MixinSharedPredicateSeam(){ }
 public static int adapt(ClassNode mixin,Function<String,ClassNode>classes,Function<String,ClassNode>source,Function<String,ClassNode>carrier){if("off".equalsIgnoreCase(System.getProperty(PROPERTY,"on")))return 0;List<String>targets=MixinFit.mixinTargets(mixin);if(targets.size()!=1)return 0;ClassNode live=classes.apply(targets.getFirst()),old=source.apply(targets.getFirst());if(live==null||old==null)return 0;
  List<MethodNode>unders=mixin.methods.stream().filter(m->eligible(m,MODIFY)&&Type.getArgumentTypes(m.desc).length==2&&Type.getArgumentTypes(m.desc)[0].equals(Type.BOOLEAN_TYPE)&&Type.getArgumentTypes(m.desc)[1].equals(Type.getObjectType(REF))).toList();int count=0;
  for(MethodNode under:unders){
   // Read as Mixin reads them, never by spelling: the host is the one method the selectors bind in the class the mod was
   // compiled against, each point the one member its target names in that host, and the pair one host however written.
   AnnotationNode ui=MixinFit.injectorOf(under);MethodNode written=MixinTargetSelectors.one(under,old);NativeSharedPredicateTemplate.Member ua=anchor(ui,written);String shared=share(under,1);if(written==null||ua==null||shared==null||!ua.descriptor().equals("()Z"))continue;
   List<MethodNode>grounds=mixin.methods.stream().filter(m->eligible(m,WRAP)&&Type.getArgumentTypes(m.desc).length==4&&Type.getArgumentTypes(m.desc)[2].equals(Type.getObjectType(OP))&&Type.getArgumentTypes(m.desc)[3].equals(Type.getObjectType(REF))&&Objects.equals(shared,share(m,3))&&sameShare(under,1,m,3)&&MixinTargetSelectors.one(m,old)==written).toList();if(grounds.size()!=1)continue;MethodNode ground=grounds.getFirst();AnnotationNode gi=MixinFit.injectorOf(ground);NativeSharedPredicateTemplate.Member ga=anchor(gi,written);if(ga==null||!ga.descriptor().equals("("+Type.getArgumentTypes(ground.desc)[1].getDescriptor()+")Z")||!ga.owner().equals(Type.getArgumentTypes(ground.desc)[0].getInternalName()))continue;
   NativeSharedPredicateTemplate.Plan plan=NativeSharedPredicateTemplate.derive(old,live,ua,ga,written,classes,source,carrier);if(plan==null)continue;
   String underName=MixinHandlerShim.asideName(mixin.name,under.name,"$forbricsharedsource"),groundName=MixinHandlerShim.asideName(mixin.name,ground.name,"$forbricsharedsource");String ref="L"+REF+";",state="L"+ga.owner()+";";String guardSite=live.name+"#"+plan.guard().name+plan.guard().desc+"#"+MixinInstructionFingerprint.hash(plan.original());
   MethodNode u=underHelper(mixin,plan,underName,ref,guardSite),g=groundHelper(plan,groundName,ref,state);if(live.methods.stream().anyMatch(m->m.name.equals(u.name)&&m.desc.equals(u.desc)||m.name.equals(g.name)&&m.desc.equals(g.desc)))continue;
   Site recorder=new Site(live.name,u.name,u.desc,MixinInstructionFingerprint.hash(u));String key=KernelSharedPredicateContracts.register(new Contract(plan.roots(),plan.definitions(),plan.flags(),plan.stateGuards(),plan.question().name(),plan.question().descriptor(),plan.dispatchKey(),plan.first(),plan.second(),plan.getterSite(),recorder,guardSite,plan.sourceSchema(),plan.interaction()));
   MethodNode originalUnder=copy(under),originalGround=copy(ground);AnnotationNode sharedAnnotation=shareNodeCopy(under,1);removeShare(under,1);removeShare(ground,3);set(ui,"method",List.of(u.name+u.desc));set(gi,"method",List.of(g.name+g.desc));mixin.methods.add(u);mixin.methods.add(g);
   MethodNode groundAdapter=groundAdapter(mixin,g,ref,state),query=queryWrapper(mixin,plan,u,groundAdapter,sharedAnnotation,key,ref),guard=guardWrapper(mixin,plan,key,guardSite),host=hostWrapper(mixin,plan,key);List<MethodNode>generated=List.of(groundAdapter,query,guard,host);mixin.methods.addAll(generated);SharedFinalSourceCertifier.remember(key,live.name,mixin.name,originalUnder,originalGround,u,g,generated,plan.under(),plan.ground());count+=2;
  }return count;
 }
 private static MethodNode copy(MethodNode input){MethodNode copy=new MethodNode(input.access,input.name,input.desc,input.signature,input.exceptions.toArray(String[]::new));input.accept(copy);return copy;}
 private static MethodNode underHelper(ClassNode mixin,NativeSharedPredicateTemplate.Plan plan,String name,String ref,String guardSite){MethodNode method=unique(name,"("+ref+")Z");LabelNode fail=new LabelNode();method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));var under=plan.under();method.instructions.add(new MethodInsnNode(under.getOpcode(),under.owner,under.name,under.desc,under.itf));method.instructions.add(new JumpInsnNode(Opcodes.IFEQ,fail));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));var guard=plan.guard();method.instructions.add(new MethodInsnNode(guard.getOpcode(),guard.owner,guard.name,guard.desc,guard.itf));method.instructions.add(new InsnNode(Opcodes.DUP));method.instructions.add(new LdcInsnNode(guardSite));method.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"recordGuard","(ZLjava/lang/String;)V",false));method.instructions.add(new JumpInsnNode(Opcodes.IFNE,fail));method.instructions.add(new InsnNode(Opcodes.ICONST_1));method.instructions.add(new InsnNode(Opcodes.IRETURN));method.instructions.add(fail);method.instructions.add(new InsnNode(Opcodes.ICONST_0));method.instructions.add(new InsnNode(Opcodes.IRETURN));method.maxLocals=2;method.maxStack=3;return method;}
 private static MethodNode groundHelper(NativeSharedPredicateTemplate.Plan plan,String name,String ref,String state){MethodNode method=unique(name,"("+ref+state+")Z");method.instructions.add(new VarInsnNode(Opcodes.ALOAD,2));var tag=plan.constant();method.instructions.add(new FieldInsnNode(tag.getOpcode(),tag.owner,tag.name,tag.desc));var atom=plan.ground();method.instructions.add(new MethodInsnNode(atom.getOpcode(),atom.owner,atom.name,atom.desc,atom.itf));method.instructions.add(new InsnNode(Opcodes.IRETURN));method.maxLocals=3;method.maxStack=2;return method;}
 private static MethodNode groundAdapter(ClassNode mixin,MethodNode source,String ref,String state){MethodNode method=unique(source.name+"$typed","("+ref+"Ljava/lang/Object;)Z");method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,2));method.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,Type.getType(state).getInternalName()));method.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,mixin.name,source.name,source.desc,false));method.instructions.add(new InsnNode(Opcodes.IRETURN));method.maxLocals=3;method.maxStack=3;return method;}
 private static MethodNode queryWrapper(ClassNode mixin,NativeSharedPredicateTemplate.Plan plan,MethodNode under,MethodNode ground,AnnotationNode shared,String key,String ref){var query=plan.query();MethodNode method=new MethodNode(Opcodes.ACC_PRIVATE,under.name+"$query","(L"+query.owner+";L"+OP+";"+ref+")Z",null,null);method.visibleAnnotations=new ArrayList<>(List.of(wrap(plan.current().name+plan.current().desc,query,null)));method.invisibleParameterAnnotations=new List[3];method.invisibleParameterAnnotations[2]=new ArrayList<>(List.of(shared));
  method.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));method.instructions.add(new LdcInsnNode(key));supplier(method.instructions,2,new int[]{1},"java/lang/Boolean");method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,3));method.instructions.add(new InvokeDynamicInsnNode("getAsBoolean","(L"+mixin.name+";"+ref+")Ljava/util/function/BooleanSupplier;",LAMBDA,Type.getMethodType("()Z"),new Handle(Opcodes.H_INVOKEVIRTUAL,mixin.name,under.name,under.desc,false),Type.getMethodType("()Z")));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,3));method.instructions.add(new InvokeDynamicInsnNode("test","(L"+mixin.name+";"+ref+")Ljava/util/function/Predicate;",LAMBDA,Type.getMethodType("(Ljava/lang/Object;)Z"),new Handle(Opcodes.H_INVOKEVIRTUAL,mixin.name,ground.name,ground.desc,false),Type.getMethodType("(Ljava/lang/Object;)Z")));method.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"query","(Ljava/lang/Object;Ljava/lang/String;Ljava/util/function/Supplier;Ljava/util/function/BooleanSupplier;Ljava/util/function/Predicate;)Z",false));method.instructions.add(new InsnNode(Opcodes.IRETURN));method.maxLocals=4;method.maxStack=12;return method;}
 private static MethodNode guardWrapper(ClassNode mixin,NativeSharedPredicateTemplate.Plan plan,String key,String site){var guard=plan.guard();MethodNode method=new MethodNode(Opcodes.ACC_PRIVATE,MixinHandlerShim.asideName(mixin.name,guard.name,"$forbricsharedguard"),"(L"+guard.owner+";L"+OP+";)Z",null,null);method.visibleAnnotations=new ArrayList<>(List.of(wrap(plan.current().name+plan.current().desc,guard,plan.guardOrdinal())));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));method.instructions.add(new LdcInsnNode(key));method.instructions.add(new LdcInsnNode(site));supplier(method.instructions,2,new int[]{1},"java/lang/Boolean");method.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"guard","(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/util/function/Supplier;)Z",false));method.instructions.add(new InsnNode(Opcodes.IRETURN));method.maxLocals=3;method.maxStack=10;return method;}
 private static MethodNode hostWrapper(ClassNode mixin,NativeSharedPredicateTemplate.Plan plan,String key){MethodNode method=new MethodNode(Opcodes.ACC_PRIVATE,MixinHandlerShim.asideName(mixin.name,plan.current().name,"$forbricsharedhost"),"(L"+OP+";)V",null,null);AnnotationNode annotation=new AnnotationNode("Lcom/llamalad7/mixinextras/injector/wrapmethod/WrapMethod;");annotation.values=new ArrayList<>(List.of("method",List.of(plan.current().name+plan.current().desc)));method.visibleAnnotations=new ArrayList<>(List.of(annotation));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new LdcInsnNode(key));supplier(method.instructions,1,new int[0],"java/lang/Object");method.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"host","(Ljava/lang/Object;Ljava/lang/String;Ljava/util/function/Supplier;)Ljava/lang/Object;",false));method.instructions.add(new InsnNode(Opcodes.POP));method.instructions.add(new InsnNode(Opcodes.RETURN));method.maxLocals=2;method.maxStack=9;return method;}
 private static void supplier(InsnList code,int operation,int[]arguments,String output){code.add(new VarInsnNode(Opcodes.ALOAD,operation));code.add(new IntInsnNode(Opcodes.BIPUSH,arguments.length));code.add(new TypeInsnNode(Opcodes.ANEWARRAY,"java/lang/Object"));for(int i=0;i<arguments.length;i++){code.add(new InsnNode(Opcodes.DUP));code.add(new IntInsnNode(Opcodes.BIPUSH,i));code.add(new VarInsnNode(Opcodes.ALOAD,arguments[i]));code.add(new InsnNode(Opcodes.AASTORE));}code.add(new InvokeDynamicInsnNode("get","(L"+OP+";[Ljava/lang/Object;)Ljava/util/function/Supplier;",LAMBDA,Type.getMethodType("()Ljava/lang/Object;"),new Handle(Opcodes.H_INVOKEINTERFACE,OP,"call","([Ljava/lang/Object;)Ljava/lang/Object;",true),Type.getMethodType("()L"+output+";")));}
 private static MethodNode unique(String name,String desc){MethodNode method=new MethodNode(Opcodes.ACC_PRIVATE,name,desc,null,null);method.visibleAnnotations=new ArrayList<>(List.of(new AnnotationNode("Lorg/spongepowered/asm/mixin/Unique;")));return method;}
 private static AnnotationNode wrap(String selector,MethodInsnNode call,Integer ordinal){AnnotationNode at=new AnnotationNode("Lorg/spongepowered/asm/mixin/injection/At;");at.values=new ArrayList<>(List.of("value","INVOKE","target","L"+call.owner+";"+call.name+call.desc));if(ordinal!=null){at.values.add("ordinal");at.values.add(ordinal);}AnnotationNode annotation=new AnnotationNode(WRAP);annotation.values=new ArrayList<>(List.of("method",List.of(selector),"at",List.of(at)));return annotation;}
 /**
  * The one method an injector's single unshifted INVOKE point names, as Mixin resolves its target
  * ({@link MixinCallbackShape#member}): whitespace or a dotted owner are the same target, and one without its owner or
  * descriptor names the member whose calls it selects in {@code written}, the host the handler was written for — and
  * nothing when it selects another member's there too, or a field.
  */
 private static NativeSharedPredicateTemplate.Member anchor(AnnotationNode injector,MethodNode written){if(MixinFit.value(injector,"slice")!=null)return null;List<AnnotationNode>points=MixinFit.atNodes(injector);if(points.size()!=1)return null;AnnotationNode at=points.getFirst();if(!"INVOKE".equals(MixinFit.value(at,"value"))||MixinFit.value(at,"ordinal")!=null||MixinFit.value(at,"shift")!=null)return null;MixinFit.Member member=MixinFit.parseMember(MixinCallbackShape.member(at,written));return member==null||member.owner()==null||member.desc()==null||!member.desc().startsWith("(")?null:new NativeSharedPredicateTemplate.Member(member.owner(),member.name(),member.desc());}
 private static boolean eligible(MethodNode method,String annotation){AnnotationNode injector=MixinFit.injectorOf(method);return injector!=null&&injector.desc.equals(annotation)&&(method.access&Opcodes.ACC_STATIC)==0&&Type.getReturnType(method.desc).equals(Type.BOOLEAN_TYPE)&&!(method.visibleAnnotations!=null&&method.visibleAnnotations.stream().anyMatch(a->a.desc.equals("Lorg/spongepowered/asm/mixin/injection/Group;")));}
 private static String share(MethodNode method,int parameter){for(var arrays:Arrays.asList(method.visibleParameterAnnotations,method.invisibleParameterAnnotations))if(arrays!=null&&arrays.length>parameter&&arrays[parameter]!=null)for(AnnotationNode annotation:arrays[parameter])if(annotation.desc.equals(SHARE))return MixinFit.asString(MixinFit.value(annotation,"value"));return null;}
 private static AnnotationNode shareNodeCopy(MethodNode method,int parameter){for(var arrays:Arrays.asList(method.visibleParameterAnnotations,method.invisibleParameterAnnotations))if(arrays!=null&&arrays.length>parameter&&arrays[parameter]!=null)for(AnnotationNode annotation:arrays[parameter])if(annotation.desc.equals(SHARE)){AnnotationNode copy=new AnnotationNode(SHARE);copy.values=annotation.values==null?null:new ArrayList<>(annotation.values);return copy;}return null;}
 private static boolean sameShare(MethodNode first,int a,MethodNode second,int b){AnnotationNode left=shareNodeCopy(first,a),right=shareNodeCopy(second,b);if(left==null||right==null)return false;Map<String,Object>l=new HashMap<>(),r=new HashMap<>();if(left.values!=null)for(int i=0;i<left.values.size();i+=2)l.put((String)left.values.get(i),left.values.get(i+1));if(right.values!=null)for(int i=0;i<right.values.size();i+=2)r.put((String)right.values.get(i),right.values.get(i+1));return l.equals(r);}
 private static void removeShare(MethodNode method,int parameter){for(var arrays:Arrays.asList(method.visibleParameterAnnotations,method.invisibleParameterAnnotations))if(arrays!=null&&arrays.length>parameter&&arrays[parameter]!=null)arrays[parameter].removeIf(a->a.desc.equals(SHARE));}
 private static void set(AnnotationNode node,String key,Object value){if(node.values==null)node.values=new ArrayList<>();for(int i=0;i<node.values.size();i+=2)if(node.values.get(i).equals(key)){node.values.set(i+1,value);return;}node.values.add(key);node.values.add(value);}
}
