/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.*;
import org.objectweb.asm.*;
import org.objectweb.asm.commons.*;
import org.objectweb.asm.tree.*;
import net.forbric.kernel.boot.*;
import net.forbric.kernel.boot.DefinedMethodContracts.MethodContract;
import net.forbric.kernel.boot.KernelCrossHostPredicateContracts.*;
import net.forbric.kernel.transform.*;

/** An original boolean modifier can remain on its native atom while its whole predicate moves before a native event. */
public final class MixinCrossHostPredicateIsland implements Opcodes {
    public static final String PROPERTY="forbric.crossHostPredicateIslands";
    private static final String MODIFY="Lcom/llamalad7/mixinextras/injector/ModifyExpressionValue;",RUNTIME="net/forbric/kernel/runtime/KernelFluidPredicateIslands",OP="com/llamalad7/mixinextras/injector/wrapoperation/Operation";
    private static final Handle LAMBDA=new Handle(H_INVOKESTATIC,"java/lang/invoke/LambdaMetafactory","metafactory","(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;",false);
    record Installed(String key,String source,String target,String handler,MethodNode original,MethodNode helper,MethodNode wrapper,CrossHostPredicateIslandPlan.Plan plan,Function<String,ClassNode>classes,Schema schema){}
    private static final Map<String,Installed>PLANS=new ConcurrentHashMap<>();
    private MixinCrossHostPredicateIsland(){}
    public static boolean enabled(){return !"off".equalsIgnoreCase(System.getProperty(PROPERTY,"on"));}
    public static int adapt(ClassNode mixin,Function<String,ClassNode>classes,Function<String,ClassNode>originals,BiPredicate<String,Runnable>register){
        if(!enabled())return 0;List<String>targets=MixinFit.mixinTargets(mixin);if(targets.size()!=1)return 0;ClassNode nativeType=originals.apply(targets.getFirst()),current=classes.apply(targets.getFirst());if(nativeType==null||current==null)return 0;
        for(MethodNode handler:new ArrayList<>(mixin.methods)){
            AnnotationNode annotation=MixinFit.injectorOf(handler);
            if(annotation==null||!annotation.desc.equals(MODIFY)||(handler.access&(ACC_STATIC|ACC_SYNCHRONIZED|ACC_ABSTRACT|ACC_NATIVE))!=0||!handler.desc.equals("(Z)Z")||MixinFit.value(annotation,"slice")!=null)continue;
            List<String>selectors=MixinFit.stringList(MixinFit.value(annotation,"method"));List<AnnotationNode>ats=MixinFit.atNodes(annotation);if(selectors.size()!=1||ats.size()!=1||!"INVOKE".equals(MixinFit.value(ats.getFirst(),"value"))||MixinFit.value(ats.getFirst(),"ordinal")!=null||MixinFit.value(ats.getFirst(),"shift")!=null)continue;
            String wanted=MixinFit.asString(MixinFit.value(ats.getFirst(),"target"));List<MethodNode>old=nativeType.methods.stream().filter(m->m.name.equals(selectors.getFirst())||(m.name+m.desc).equals(selectors.getFirst())).toList();if(old.size()!=1)continue;MethodNode nativeMethod=old.getFirst(),live=CrossHostPredicateIslandPlan.find(current,nativeMethod.name,nativeMethod.desc);if(live==null)continue;
            List<MethodInsnNode>anchors=new ArrayList<>();for(AbstractInsnNode instruction:nativeMethod.instructions)if(instruction instanceof MethodInsnNode call&&wanted.equals("L"+call.owner+";"+call.name+call.desc))anchors.add(call);if(anchors.size()!=1)continue;boolean sourceClosed=true;for(var i:handler.instructions)if(i instanceof MethodInsnNode call&&call.owner.equals(mixin.name)){MethodNode member=CrossHostPredicateIslandPlan.find(mixin,call.name,call.desc);boolean shadow=member!=null&&member.visibleAnnotations!=null&&member.visibleAnnotations.stream().anyMatch(a->a.desc.equals("Lorg/spongepowered/asm/mixin/Shadow;"));boolean inherited=member==null&&Objects.equals(mixin.superName,current.superName);if((!shadow&&!inherited)||!call.name.equals(anchors.getFirst().name)||!call.desc.equals(anchors.getFirst().desc))sourceClosed=false;}if(!sourceClosed)continue;
            String helperName=MixinHandlerShim.asideName(mixin.name,handler.name,"$forbricsourceisland");var extraction=NativeSourcePredicateIsland.extract(nativeType.name,nativeType.name,nativeMethod,anchors.getFirst(),helperName);if(extraction==null)continue;
            var plan=CrossHostPredicateIslandPlan.derive(current.name,live,extraction,classes);if(plan==null)continue;Schema schema=schema(plan,current,classes);if(schema==null)continue;
            MethodNode original=copy(handler);String key=MixinInstructionFingerprint.hash(extraction.helper())+":"+MixinInstructionFingerprint.hash(plan.method())+":"+MixinInstructionFingerprint.hash(original)+":"+schemaKey(schema)+":"+mixin.name;
            Installed installed=new Installed(key,mixin.name,current.name,handler.name,original,extraction.helper(),wrapper(mixin,live,plan,extraction.helper(),key),plan,classes,schema);
            if(!register.test(plan.owner(),()->{synchronized(PLANS){Installed oldPlan=PLANS.get(key);if(oldPlan!=null&&(!oldPlan.source.equals(installed.source)||!oldPlan.schema.equals(schema)))throw new IllegalStateException("ambiguous source predicate plan");KernelCrossHostPredicateContracts.register(key,schema);PLANS.putIfAbsent(key,installed);}}))continue;
            set(annotation,"method",List.of(helperName+extraction.helper().desc));mixin.methods.add(extraction.helper());mixin.methods.add(installed.wrapper);return 1;
        }return 0;
    }
    private static Schema schema(CrossHostPredicateIslandPlan.Plan plan,ClassNode actor,Function<String,ClassNode>classes){
        try{
            Decl worldDecl=declaration(new CrossHostPredicateIslandPlan.Member(plan.source().worldGetter().owner,plan.source().worldGetter().name,plan.source().worldGetter().desc),classes),interactionDecl=declaration(plan.interactionGetter(),classes),queryDecl=declaration(plan.query(),classes),typedDecl=declaration(plan.typedActorQuestion(),classes),protection=declaration(plan.protection(),classes),air=declaration(plan.anyTypeQuestion(),classes);
            if(worldDecl==null||interactionDecl==null||queryDecl==null||typedDecl==null||protection==null||air==null)return null;FieldInsnNode world=identityFieldGetter(worldDecl.method);if(world==null)return null;
            ClassNode interaction=classes.apply(plan.query().owner());if(interaction==null)return null;FieldInsnNode primary=null,eyes=null;String tracker=null;
            for(AbstractInsnNode i:queryDecl.method.instructions){if(i instanceof FieldInsnNode f&&f.getOpcode()==GETFIELD&&f.desc.equals("Ljava/util/Map;")){if(primary!=null)return null;primary=f;}if(i instanceof FieldInsnNode f&&f.getOpcode()==GETFIELD&&f.desc.equals("Z")){if(eyes!=null)return null;eyes=f;tracker=f.owner;}}
            if(primary==null||eyes==null)return null;String physicalKey=null;for(MethodNode method:interaction.methods)for(AbstractInsnNode i:method.instructions)if(i instanceof MethodInsnNode call&&call.getOpcode()==INVOKESTATIC&&call.owner.equals("net/forbric/kernel/runtime/KernelFabricTagViews")&&call.name.equals("begin")){AbstractInsnNode before=previous(call);if(!(before instanceof LdcInsnNode id&&id.cst instanceof String key))return null;if(physicalKey!=null&&!physicalKey.equals(key))return null;physicalKey=key;}
            if(physicalKey==null)return null;List<MethodContract>guards=new ArrayList<>();guards.add(contract(typedDecl));guards.add(contract(protection));List<MethodContract>definitions=new ArrayList<>();
            CrossHostPredicateIslandPlan.Member terminal=null;Type type=Type.getArgumentTypes(plan.typedActorQuestion().descriptor())[0];for(AbstractInsnNode i:typedDecl.method.instructions)if(i instanceof MethodInsnNode call){if(call.owner.equals(type.getInternalName())&&call.desc.equals("(L"+actor.name+";)Z")){if(terminal!=null)return null;terminal=new CrossHostPredicateIslandPlan.Member(call.owner,call.name,call.desc);}else if(call.owner.equals(typedDecl.owner)&&call.getOpcode()==INVOKEINTERFACE&&call.desc.equals("()L"+actor.name+";")){var identity=declaration(new CrossHostPredicateIslandPlan.Member(call.owner,call.name,call.desc),classes);if(identity==null||!identityThis(identity.method,actor.name))return null;if((identity.method.access&ACC_PRIVATE)!=0)definitions.add(contract(identity));else guards.add(contract(identity));}}
            if(terminal==null)return null;
            for(MethodInsnNode call:plan.source().calls()){var declared=declaration(new CrossHostPredicateIslandPlan.Member(call.owner,call.name,call.desc),classes);if(declared==null)return null;if(call.getOpcode()!=INVOKESTATIC&&isActorOwner(actor,call.owner,classes))guards.add(contract(declared));else definitions.add(contract(declared));}
            for(var i:plan.method().instructions){if(i==plan.end())break;if(i instanceof InvokeDynamicInsnNode d&&d.bsm.getOwner().equals("java/lang/invoke/LambdaMetafactory")){if(d.bsmArgs.length!=3||!(d.bsmArgs[1]instanceof Handle h))return null;Decl lambda=declaration(new CrossHostPredicateIslandPlan.Member(h.getOwner(),h.getName(),h.getDesc()),classes);if(lambda==null)return null;definitions.add(contract(lambda));}}
            guards=guards.stream().distinct().sorted(Comparator.comparing(MethodContract::toString)).toList();definitions=definitions.stream().distinct().sorted(Comparator.comparing(MethodContract::toString)).toList();Map<MethodContract,Integer>flags=new HashMap<>();List<MethodContract>all=new ArrayList<>(guards);all.addAll(definitions);all.addAll(List.of(contract(worldDecl),contract(interactionDecl),contract(queryDecl),contract(air)));for(var c:all){Decl declared=declaration(new CrossHostPredicateIslandPlan.Member(c.owner().replace('.','/'),c.name(),c.descriptor()),classes);if(declared==null||(declared.method.access&(ACC_ABSTRACT|ACC_NATIVE|ACC_SYNCHRONIZED))!=0)return null;flags.put(c,declared.method.access);}return new Schema(actor.name,interaction.name,tracker,physicalKey,field(primary,classes),field(eyes,classes),field(world,classes),contract(worldDecl),contract(interactionDecl),contract(queryDecl),guards,definitions,contract(air),terminal.name(),terminal.descriptor(),flags,typedClosure(typedDecl,plan,terminal,actor,classes));
        }catch(RuntimeException unknown){return null;}
    }
    private static List<SpecialType>typedClosure(Decl typed,CrossHostPredicateIslandPlan.Plan plan,CrossHostPredicateIslandPlan.Member terminal,ClassNode actor,Function<String,ClassNode>classes){
        PredicateDecisionGraph.Tree tree=PredicateDecisionGraph.helper(typed.method,e->normalizeIdentity(e,actor.name,classes));
        PredicateDecisionGraph.Expr terminalExpression=new PredicateDecisionGraph.Expr("call",INVOKEVIRTUAL+":"+terminal.owner()+"."+terminal.name()+terminal.descriptor(),List.of(PredicateDecisionGraph.Expr.root(1),PredicateDecisionGraph.Expr.root(0)));
        if(tree.equals(new PredicateDecisionGraph.Value(terminalExpression)))return List.of();
        if(!(tree instanceof PredicateDecisionGraph.Test branch)||!branch.condition().operation().equals("same")||branch.condition().inputs().size()!=2||!branch.condition().inputs().getFirst().equals(PredicateDecisionGraph.Expr.root(1))||!branch.no().equals(new PredicateDecisionGraph.Value(terminalExpression))||!(branch.yes()instanceof PredicateDecisionGraph.Test protectedBranch)||!protectedBranch.yes().equals(new PredicateDecisionGraph.Result(0))||!protectedBranch.no().equals(new PredicateDecisionGraph.Result(1)))throw new IllegalArgumentException("unknown typed predicate closure");
        var protects=declaration(plan.protection(),classes);var expected=new PredicateDecisionGraph.Expr("call",INVOKEVIRTUAL+":"+protects.owner+"."+protects.method.name+protects.method.desc,List.of(PredicateDecisionGraph.Expr.root(0)));if(!protectedBranch.condition().equals(expected))throw new IllegalArgumentException("different typed protection");var projection=branch.condition().inputs().get(1);if(!projection.operation().equals("call")||projection.inputs().size()!=1||!projection.inputs().getFirst().operation().equals("static"))throw new IllegalArgumentException("unknown special type projection");
        FieldInsnNode holder=null;MethodInsnNode getter=null;for(var i:typed.method.instructions){if(i instanceof FieldInsnNode f&&f.getOpcode()==GETSTATIC&&(f.owner+"."+f.name+f.desc).equals(projection.inputs().getFirst().symbol()))holder=f;if(i instanceof MethodInsnNode call&&(call.getOpcode()+":"+call.owner+"."+call.name+call.desc).equals(projection.symbol()))getter=call;}
        if(holder==null||getter==null||Type.getArgumentTypes(getter.desc).length!=0||Type.getReturnType(getter.desc).getSort()!=Type.OBJECT)throw new IllegalArgumentException("non-projection special type");FieldShape field=field(holder,classes);if((field.flags()&(ACC_STATIC|ACC_FINAL))!=(ACC_STATIC|ACC_FINAL))throw new IllegalArgumentException("mutable special type holder");return List.of(new SpecialType(field,getter.name,getter.desc));
    }
    private static PredicateDecisionGraph.Expr normalizeIdentity(PredicateDecisionGraph.Expr value,String actor,Function<String,ClassNode>classes){List<PredicateDecisionGraph.Expr>args=value.inputs().stream().map(e->normalizeIdentity(e,actor,classes)).toList();var normalized=new PredicateDecisionGraph.Expr(value.operation(),value.symbol(),args);if(value.operation().equals("call")){int dot=value.symbol().indexOf('.'),paren=value.symbol().indexOf('('),colon=value.symbol().indexOf(':');if(dot<0||paren<0)return normalized;var d=declaration(new CrossHostPredicateIslandPlan.Member(value.symbol().substring(colon+1,dot),value.symbol().substring(dot+1,paren),value.symbol().substring(paren)),classes);if(d!=null&&args.equals(List.of(PredicateDecisionGraph.Expr.root(0)))&&identityThis(d.method,actor))return PredicateDecisionGraph.Expr.root(0);if(d!=null)return new PredicateDecisionGraph.Expr("call",value.symbol().substring(0,colon+1)+d.owner+"."+d.method.name+d.method.desc,args);}return normalized;}
    private record Decl(String owner,MethodNode method){}
    private static Decl declaration(CrossHostPredicateIslandPlan.Member member,Function<String,ClassNode>classes){String owner=CrossHostPredicateIslandPlan.declaring(member,classes,new HashSet<>());if(owner==null)return null;return new Decl(owner,CrossHostPredicateIslandPlan.find(classes.apply(owner),member.name(),member.descriptor()));}
    private static FieldShape field(FieldInsnNode field,Function<String,ClassNode>classes){ClassNode owner=classes.apply(field.owner);if(owner==null)throw new IllegalArgumentException();FieldNode member=owner.fields.stream().filter(f->f.name.equals(field.name)&&f.desc.equals(field.desc)).findFirst().orElse(null);if(member!=null)return new FieldShape(owner.name,member.name,member.desc,member.access);if(owner.superName==null)throw new IllegalArgumentException();return field(new FieldInsnNode(field.getOpcode(),owner.superName,field.name,field.desc),classes);}
    private static MethodContract contract(Decl decl){return new MethodContract(decl.owner,decl.method.name,decl.method.desc,MixinInstructionFingerprint.hash(decl.method));}
    private static FieldInsnNode identityFieldGetter(MethodNode method){List<AbstractInsnNode>code=code(method);return code.size()==3&&code.get(0)instanceof VarInsnNode self&&self.getOpcode()==ALOAD&&self.var==0&&code.get(1)instanceof FieldInsnNode field&&field.getOpcode()==GETFIELD&&code.get(2).getOpcode()==ARETURN?field:null;}
    private static boolean identityThis(MethodNode method,String target){List<AbstractInsnNode>c=code(method);return c.size()==3&&c.get(0)instanceof VarInsnNode self&&self.getOpcode()==ALOAD&&self.var==0&&c.get(1)instanceof TypeInsnNode cast&&cast.getOpcode()==CHECKCAST&&cast.desc.equals(target)&&c.get(2).getOpcode()==ARETURN;}
    private static boolean isActorOwner(ClassNode actor,String owner,Function<String,ClassNode>classes){if(actor.name.equals(owner))return true;return actor.superName!=null&&classes.apply(actor.superName)!=null&&isActorOwner(classes.apply(actor.superName),owner,classes);}
    private static MethodNode wrapper(ClassNode mixin,MethodNode caller,CrossHostPredicateIslandPlan.Plan plan,MethodNode helper,String key){
        Type[]args=Type.getArgumentTypes(plan.caller().desc);StringBuilder descriptor=new StringBuilder("(");for(Type arg:args)descriptor.append(arg.getDescriptor());descriptor.append('L').append(OP).append(";)V");MethodNode method=new MethodNode(ACC_PRIVATE,MixinHandlerShim.asideName(mixin.name,helper.name,"$forbricislandoffload"),descriptor.toString(),null,null);
        AnnotationNode wrap=new AnnotationNode("Lcom/llamalad7/mixinextras/injector/wrapoperation/WrapOperation;"),at=new AnnotationNode("Lorg/spongepowered/asm/mixin/injection/At;");at.values=new ArrayList<>(List.of("value","INVOKE","target","L"+plan.caller().owner+";"+plan.caller().name+plan.caller().desc));wrap.values=new ArrayList<>(List.of("method",List.of(caller.name+caller.desc),"at",at,"require",1));method.visibleAnnotations=new ArrayList<>(List.of(wrap));
        InsnList i=method.instructions;i.add(new VarInsnNode(ALOAD,0));i.add(new VarInsnNode(ALOAD,2));i.add(new LdcInsnNode(key));i.add(new VarInsnNode(ALOAD,0));i.add(new VarInsnNode(ALOAD,2));i.add(new InvokeDynamicInsnNode("getAsInt","(L"+mixin.name+";L"+args[1].getInternalName()+";)Ljava/util/function/IntSupplier;",LAMBDA,Type.getMethodType("()I"),new Handle(H_INVOKEVIRTUAL,mixin.name,helper.name,helper.desc,false),Type.getMethodType("()I")));
        i.add(new MethodInsnNode(INVOKESTATIC,RUNTIME,"enter","(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/util/function/IntSupplier;)L"+RUNTIME+"$Scope;",false));i.add(new VarInsnNode(ASTORE,6));LabelNode start=new LabelNode(),end=new LabelNode(),failure=new LabelNode();i.add(start);i.add(new VarInsnNode(ALOAD,5));i.add(new InsnNode(ICONST_4));i.add(new TypeInsnNode(ANEWARRAY,"java/lang/Object"));int slot=1;for(int n=0;n<args.length;n++){i.add(new InsnNode(DUP));i.add(new InsnNode(ICONST_0+n));i.add(new VarInsnNode(args[n].getOpcode(ILOAD),slot));if(args[n]==Type.INT_TYPE)i.add(new MethodInsnNode(INVOKESTATIC,"java/lang/Integer","valueOf","(I)Ljava/lang/Integer;",false));i.add(new InsnNode(AASTORE));slot+=args[n].getSize();}i.add(new MethodInsnNode(INVOKEINTERFACE,OP,"call","([Ljava/lang/Object;)Ljava/lang/Object;",true));i.add(new InsnNode(POP));i.add(end);i.add(new VarInsnNode(ALOAD,6));i.add(new MethodInsnNode(INVOKEVIRTUAL,RUNTIME+"$Scope","close","()V",false));i.add(new InsnNode(RETURN));i.add(failure);i.add(new VarInsnNode(ASTORE,7));i.add(new VarInsnNode(ALOAD,6));i.add(new MethodInsnNode(INVOKEVIRTUAL,RUNTIME+"$Scope","close","()V",false));i.add(new VarInsnNode(ALOAD,7));i.add(new InsnNode(ATHROW));method.tryCatchBlocks.add(new TryCatchBlockNode(start,end,failure,null));method.maxLocals=8;method.maxStack=10;return method;
    }
    /** Called after the real weaver: copied native helper plus exactly one original modifier call must close. */
    public static void certify(ClassNode target){for(Installed plan:PLANS.values())if(plan.target.equals(target.name)){
        List<MethodNode>helpers=target.methods.stream().filter(m->m.name.equals(plan.helper.name)&&m.desc.equals(plan.helper.desc)).toList(),handlers=target.methods.stream().filter(m->m.desc.equals(plan.original.desc)&&m.name.contains(plan.handler)&&mergedFrom(m,plan.source)).toList();if(helpers.size()!=1||handlers.size()!=1)continue;MethodNode helper=helpers.getFirst(),handler=handlers.getFirst();
        MethodNode original=copy(plan.original),actual=copy(handler);normalizeSelf(original,plan.source,plan.target,plan.handler,handler.name);removeSelfCasts(original,plan.target);removeSelfCasts(actual,plan.target);if(!MixinInstructionFingerprint.hash(original).equals(MixinInstructionFingerprint.hash(actual)))continue;
        MethodNode cleaned=copy(helper);boolean removed=false;for(AbstractInsnNode i:cleaned.instructions.toArray())if(i instanceof MethodInsnNode call&&call.owner.equals(target.name)&&call.name.equals(handler.name)&&call.desc.equals(handler.desc)){AbstractInsnNode swap=previous(call),receiver=previous(swap);if(removed||swap==null||swap.getOpcode()!=SWAP||!(receiver instanceof VarInsnNode thisValue&&thisValue.getOpcode()==ALOAD&&thisValue.var==0))break;cleaned.instructions.remove(receiver);cleaned.instructions.remove(swap);cleaned.instructions.remove(call);removed=true;}
        if(removed&&MixinInstructionFingerprint.hash(cleaned).equals(MixinInstructionFingerprint.hash(plan.helper))){List<MethodNode>wrappers=target.methods.stream().filter(m->m.name.contains(plan.wrapper.name)&&m.desc.equals(plan.wrapper.desc)&&mergedFrom(m,plan.source)).toList();if(wrappers.size()!=1)continue;MethodNode wrapper=wrappers.getFirst(),expectedWrapper=copy(plan.wrapper);normalizeSelf(expectedWrapper,plan.source,plan.target,plan.handler,handler.name);if(!MixinInstructionFingerprint.hash(expectedWrapper).equals(MixinInstructionFingerprint.hash(wrapper)))continue;MethodContract helperContract=contract(new Decl(target.name,helper)),handlerContract=contract(new Decl(target.name,handler)),wrapperContract=contract(new Decl(target.name,wrapper));if((helper.access&(ACC_NATIVE|ACC_ABSTRACT|ACC_SYNCHRONIZED|ACC_STATIC))!=0||(helper.access&ACC_PRIVATE)==0||(handler.access&(ACC_NATIVE|ACC_ABSTRACT|ACC_SYNCHRONIZED|ACC_STATIC))!=0||(handler.access&ACC_PRIVATE)==0||(wrapper.access&(ACC_NATIVE|ACC_ABSTRACT|ACC_SYNCHRONIZED|ACC_STATIC))!=0||(wrapper.access&ACC_PRIVATE)==0)continue;KernelCrossHostPredicateContracts.source(plan.key,new Source(helperContract,List.of(handlerContract,wrapperContract),Map.of(helperContract,helper.access,handlerContract,handler.access,wrapperContract,wrapper.access)));}
    }}
    private static void removeSelfCasts(MethodNode method,String target){for(var i:method.instructions.toArray())if(i instanceof TypeInsnNode cast&&cast.getOpcode()==CHECKCAST&&cast.desc.equals(target)&&previous(cast)instanceof VarInsnNode self&&self.getOpcode()==ALOAD&&self.var==0)method.instructions.remove(cast);}
    private static String schemaKey(Schema s){List<String>parts=new ArrayList<>(List.of(s.actor(),s.interaction(),s.tracker(),s.collectorKey(),s.primaryMap().toString(),s.eyes().toString(),s.world().toString(),s.worldGetter().toString(),s.interactionGetter().toString(),s.query().toString(),s.airQuestion().toString(),s.ownedQuestion(),s.ownedDescriptor(),s.excluded().toString()));s.actorGuards().stream().map(c->"virtual:"+c).sorted().forEach(parts::add);s.definitions().stream().map(c->"direct:"+c).sorted().forEach(parts::add);s.flags().entrySet().stream().map(e->"flags:"+e.getKey()+":"+e.getValue()).sorted().forEach(parts::add);try{return HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(String.join("\n",parts).getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(java.security.NoSuchAlgorithmException impossible){throw new AssertionError(impossible);}}
    public static void observeDefinition(String binary,byte[]bytes){String owner=binary.replace('.','/');if(PLANS.values().stream().noneMatch(p->p.target.equals(owner)))return;try{ClassNode target=new ClassNode();new ClassReader(bytes).accept(target,0);certify(target);}catch(RuntimeException|LinkageError rejected){net.forbric.kernel.util.ForbricLog.warn("[Forbric/Mixin] final source predicate certification declined for "+binary+": "+rejected.getClass().getSimpleName());}}
    private static void normalizeSelf(MethodNode method,String old,String target,String oldHandler,String newHandler){for(AbstractInsnNode i:method.instructions){if(i instanceof MethodInsnNode call&&call.owner.equals(old))call.owner=target;if(i instanceof TypeInsnNode cast&&cast.desc.equals(old))cast.desc=target;if(i instanceof InvokeDynamicInsnNode d){d.desc=d.desc.replace("L"+old+";","L"+target+";");for(int n=0;n<d.bsmArgs.length;n++)if(d.bsmArgs[n]instanceof Handle h&&h.getOwner().equals(old))d.bsmArgs[n]=new Handle(h.getTag(),target,h.getName(),h.getDesc(),h.isInterface());}}}
    private static boolean mergedFrom(MethodNode method,String source){if(method.visibleAnnotations!=null)for(AnnotationNode a:method.visibleAnnotations)if(a.desc.equals("Lorg/spongepowered/asm/mixin/transformer/meta/MixinMerged;")&&source.replace('/','.').equals(MixinFit.value(a,"mixin")))return true;return false;}
    static Collection<Installed> plans(){return PLANS.values();}
    public static void resetForTests(){PLANS.clear();KernelCrossHostPredicateContracts.resetForTests();}
    private static MethodNode copy(MethodNode original){MethodNode copy=new MethodNode(original.access,original.name,original.desc,original.signature,original.exceptions.toArray(String[]::new));original.accept(copy);for(AbstractInsnNode i:copy.instructions)if(i instanceof InvokeDynamicInsnNode d)d.bsmArgs=d.bsmArgs.clone();return copy;}
    private static List<AbstractInsnNode>code(MethodNode method){List<AbstractInsnNode>out=new ArrayList<>();for(AbstractInsnNode i:method.instructions)if(i.getOpcode()>=0)out.add(i);return out;}
    private static AbstractInsnNode previous(AbstractInsnNode i){i=i.getPrevious();while(i!=null&&i.getOpcode()<0)i=i.getPrevious();return i;}
    private static void set(AnnotationNode annotation,String key,Object value){if(annotation.values==null)annotation.values=new ArrayList<>();for(int i=0;i<annotation.values.size();i+=2)if(key.equals(annotation.values.get(i))){annotation.values.set(i+1,value);return;}annotation.values.add(key);annotation.values.add(value);}
}
