/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;

import java.util.*;
import java.util.function.Function;
import net.forbric.api.Ecosystem;
import net.forbric.api.ForeignType;
import net.forbric.kernel.boot.DefinedMethodContracts;
import net.forbric.kernel.boot.DefinedMethodContracts.MethodContract;
import net.forbric.kernel.boot.KernelPredicateSeams.*;
import net.forbric.kernel.boot.KernelSharedPredicateContracts.*;
import net.forbric.kernel.transform.PredicateGetterResultRecorder;
import org.objectweb.asm.*;
import org.objectweb.asm.tree.*;

/** A source two-leaf/guard continuation and a carrier's closed two-leaf native query, without member tables. */
final class NativeSharedPredicateTemplate {
 record Member(String owner,String name,String descriptor){static Member of(MethodInsnNode n){return new Member(n.owner,n.name,n.desc);}String selector(){return "L"+owner+";"+name+descriptor;}}
 record Decl(String owner,MethodNode method){MethodContract contract(){return new MethodContract(owner,method.name,method.desc,DefinedMethodContracts.fingerprint(method));}}
 record Plan(MethodNode original,MethodNode current,MethodInsnNode under,MethodInsnNode guard,MethodInsnNode ground,
   FieldInsnNode constant,MethodInsnNode query,int guardOrdinal,MethodNode lambda,Decl getter,
   List<Dispatch>roots,List<MethodContract>definitions,Map<String,Integer>flags,List<Guard>stateGuards,
   Member question,String dispatchKey,Leaf first,Leaf second,Site getterSite,Value interaction,String sourceSchema){ }
 private static final String TYPE="L"+ForeignType.FLUID_TYPE.internal(Ecosystem.NEOFORGE)+";";
 private NativeSharedPredicateTemplate(){ }
 /** {@code written}: the one method of {@code source} the pair's selectors bind there, as Mixin binds them ({@link MixinTargetSelectors#one}). */
 static Plan derive(ClassNode source,ClassNode current,Member under,Member ground,MethodNode written,
   Function<String,ClassNode>classes,Function<String,ClassNode>sourceClasses,Function<String,ClassNode>carrier){try{
  if(written==null||!source.methods.contains(written))return null;MethodNode old=written,live=find(current,old.name,old.desc);if(live==null||!old.desc.equals("()V")||!old.tryCatchBlocks.isEmpty()||!live.tryCatchBlocks.isEmpty())return null;
  ClassNode carrierHost=carrier.apply(current.name);MethodNode carrierBody=carrierHost==null?null:find(carrierHost,live.name,live.desc);if(carrierBody==null||!sameBody(carrierBody,live))return null;
  MethodInsnNode first=unique(old,under),second=unique(old,ground);if(first==null||second==null||!(previous(first)instanceof VarInsnNode self&&self.getOpcode()==Opcodes.ALOAD&&self.var==0)||!(next(first)instanceof JumpInsnNode underExit&&underExit.getOpcode()==Opcodes.IFEQ))return null;
  AbstractInsnNode guardLoad=next(underExit),guardCall=next(guardLoad),guardExit=next(guardCall);if(!(guardLoad instanceof VarInsnNode g&&g.getOpcode()==Opcodes.ALOAD&&g.var==0)||!(guardCall instanceof MethodInsnNode guard&&guard.desc.equals("()Z"))||!(guardExit instanceof JumpInsnNode gate&&gate.getOpcode()==Opcodes.IFNE&&next(gate.label)==next(underExit.label)))return null;
  if(!(previous(second)instanceof FieldInsnNode constant&&constant.getOpcode()==Opcodes.GETSTATIC&&constant.desc.equals(Type.getArgumentTypes(ground.descriptor())[0].getDescriptor()))||!(next(second)instanceof JumpInsnNode groundExit&&groundExit.getOpcode()==Opcodes.IFEQ&&next(groundExit.label)==next(underExit.label)))return null;
  List<AbstractInsnNode>oldWorld=between(next(gate),constant);if(oldWorld.size()!=5||!(oldWorld.get(0)instanceof VarInsnNode a&&a.var==0)||!(oldWorld.get(1)instanceof MethodInsnNode level)||!(oldWorld.get(2)instanceof VarInsnNode b&&b.var==0)||!(oldWorld.get(3)instanceof FieldInsnNode position&&position.getOpcode()==Opcodes.GETFIELD)||!(oldWorld.get(4)instanceof MethodInsnNode world))return null;
  Set<Member>oldCalls=new HashSet<>();for(var i:old.instructions)if(i instanceof MethodInsnNode call)oldCalls.add(Member.of(call));List<MethodInsnNode>queries=new ArrayList<>();for(var i:live.instructions)if(i instanceof MethodInsnNode call&&call.desc.equals("()Z")&&call.getOpcode()==Opcodes.INVOKEVIRTUAL&&!oldCalls.contains(Member.of(call))&&previous(call)instanceof VarInsnNode receiver&&receiver.getOpcode()==Opcodes.ALOAD&&receiver.var==0)queries.add(call);if(queries.size()!=1)return null;MethodInsnNode query=queries.getFirst();
  AbstractInsnNode currentExit=next(query),currentGuardLoad=next(currentExit),currentGuard=next(currentGuardLoad),currentGuardExit=next(currentGuard);if(!(currentExit instanceof JumpInsnNode exit&&exit.getOpcode()==Opcodes.IFEQ)||!(currentGuardLoad instanceof VarInsnNode cg&&cg.getOpcode()==Opcodes.ALOAD&&cg.var==0)||!(currentGuard instanceof MethodInsnNode retained&&Member.of(retained).equals(Member.of(guard)))||!(currentGuardExit instanceof JumpInsnNode ge&&ge.getOpcode()==Opcodes.IFNE&&next(ge.label)==next(exit.label)))return null;
  int ordinal=0;for(var i:live.instructions){if(i==retained)break;if(i instanceof MethodInsnNode call&&Member.of(call).equals(Member.of(retained)))ordinal++;}
  Proof proof=new Proof(classes,sourceClasses,carrier,current.name);proof.read(Member.of(first),new Root(0),new HashSet<>());proof.read(Member.of(guard),new Root(0),new HashSet<>());
  Entry entry=proof.entry(Member.of(query));if(entry==null)return null;List<AbstractInsnNode>code=ops(entry.lambda().method());if(code.size()!=17||!(code.get(0)instanceof VarInsnNode actor&&actor.getOpcode()==Opcodes.ALOAD&&actor.var==0)||!(code.get(1)instanceof VarInsnNode kind&&kind.getOpcode()==Opcodes.ALOAD&&kind.var==1)||!(code.get(2)instanceof MethodInsnNode q1)||!(code.get(3)instanceof JumpInsnNode fail&&fail.getOpcode()==Opcodes.IFEQ))return null;
  if(!(code.get(4)instanceof VarInsnNode e0&&e0.var==0)||!(code.get(5)instanceof VarInsnNode e1&&e1.var==0)||!(code.get(6)instanceof MethodInsnNode newLevel&&Member.of(newLevel).equals(Member.of(level)))||!(code.get(7)instanceof VarInsnNode e2&&e2.var==0)||!(code.get(8)instanceof MethodInsnNode newPosition)||!(code.get(9)instanceof MethodInsnNode newWorld&&Member.of(newWorld).equals(Member.of(world)))||!(code.get(10)instanceof MethodInsnNode stateType)||!(code.get(11)instanceof MethodInsnNode q2&&Member.of(q2).equals(Member.of(q1)))||!(code.get(12)instanceof JumpInsnNode f2&&f2.getOpcode()==Opcodes.IFEQ&&next(f2.label)==next(fail.label))||code.get(13).getOpcode()!=Opcodes.ICONST_1||!(code.get(14)instanceof JumpInsnNode success&&success.getOpcode()==Opcodes.GOTO)||code.get(15).getOpcode()!=Opcodes.ICONST_0||code.get(16).getOpcode()!=Opcodes.IRETURN)return null;
  // The exact closed lambda grammar includes 17 executable opcodes (its last return is shared).
  if(code.size()!=17)return null;
  Decl positionGetter=resolve(Member.of(newPosition),classes,new HashSet<>());if(positionGetter==null||!fieldGetter(positionGetter.method(),position))return null;proof.read(Member.of(newPosition),new Root(0),new HashSet<>());
  Member question=proof.question(Member.of(q1));if(question==null)return null;Decl getter=resolve(Member.of(stateType),classes,new HashSet<>());if(getter==null)return null;Site getterSite=recordSite(getter);if(getterSite==null)return null;
  List<Guard>stateGuards=new ArrayList<>();proof.stateGetter(Member.of(stateType),new Root(0),stateGuards,new HashSet<>());proof.stateRead(ground,new Root(0),stateGuards,new HashSet<>());
  List<Integer>offsets=offsets(entry.lambda().method(),Member.of(q1));if(offsets.size()!=2)return null;String schema=null;Value interaction=entry.interaction();if(!(interaction instanceof Projection projection))return null;ClassNode control=classes.apply(Type.getType(projection.descriptor()).getInternalName());if(control==null)return null;for(MethodNode method:control.methods)for(var i:method.instructions)if(i instanceof MethodInsnNode call&&call.owner.equals("net/forbric/kernel/runtime/KernelFabricTagViews")&&call.name.equals("begin")&&previous(i)instanceof LdcInsnNode ldc&&ldc.cst instanceof String key){if(schema!=null&&!schema.equals(key))return null;schema=key;}if(schema==null)return null;
  return new Plan(old,live,first,guard,second,constant,query,ordinal,entry.lambda().method(),getter,List.copyOf(proof.roots),List.copyOf(proof.definitions),Map.copyOf(proof.flags),List.copyOf(stateGuards),question,proof.dispatchKey,new Leaf(entry.lambda().contract(),offsets.get(0)),new Leaf(entry.lambda().contract(),offsets.get(1)),getterSite,interaction,schema);
 }catch(RuntimeException unsupported){return null;}}
 private record Entry(Decl lambda,Value interaction){ }
 private static final class Proof{
  final Function<String,ClassNode>classes,source,carrier;final String host;String dispatchKey;final List<Dispatch>roots=new ArrayList<>();final List<MethodContract>definitions=new ArrayList<>();final Map<String,Integer>flags=new HashMap<>();
  Proof(Function<String,ClassNode>classes,Function<String,ClassNode>source,Function<String,ClassNode>carrier,String host){this.classes=classes;this.source=source;this.carrier=carrier;this.host=host;}
  void define(Decl decl){if(!definitions.contains(decl.contract()))definitions.add(decl.contract());flags.put(decl.contract().owner()+"#"+decl.method().name+decl.method().desc,decl.method().access);}
  void witness(Decl decl){ClassNode nativeOwner=carrier.apply(decl.owner());MethodNode nativeBody=nativeOwner==null?null:find(nativeOwner,decl.method().name,decl.method().desc);if(nativeBody==null||!sameBody(nativeBody,stripRecord(decl.method()))||((nativeBody.access^decl.method().access)&(Opcodes.ACC_STATIC|Opcodes.ACC_PRIVATE|Opcodes.ACC_PUBLIC|Opcodes.ACC_PROTECTED|Opcodes.ACC_SYNCHRONIZED|Opcodes.ACC_NATIVE|Opcodes.ACC_ABSTRACT))!=0)throw new IllegalArgumentException();define(decl);}
  void root(Decl decl,Value receiver,boolean direct){roots.add(new Dispatch(new Guard(receiver,decl.contract(),direct),forwarder(decl.method())));define(decl);}
  Entry entry(Member member){return entry(member,false);}
  Entry entry(Member member,boolean direct){Decl decl=resolve(member,classes,new HashSet<>());if(decl==null)return null;if(forwarder(decl.method())){root(decl,new Root(0),false);MethodInsnNode delegate=(MethodInsnNode)ops(decl.method()).get(1);return entry(Member.of(delegate),true);}witness(decl);root(decl,new Root(0),direct);
   List<Object>stack=new ArrayList<>();Decl lambda=null;Value interaction=null;for(var instruction:decl.method().instructions){if(instruction.getOpcode()<0)continue;if(instruction instanceof VarInsnNode load&&load.getOpcode()==Opcodes.ALOAD&&load.var==0)stack.add(new Root(0));else if(instruction instanceof MethodInsnNode call){Type[]args=Type.getArgumentTypes(call.desc);List<Object>passed=new ArrayList<>();for(int i=0;i<args.length;i++)passed.addFirst(stack.removeLast());Object receiver=stack.removeLast();Decl target=resolve(Member.of(call),classes,new HashSet<>());if(target==null)throw new IllegalArgumentException();List<AbstractInsnNode>body=ops(target.method());if(identity(target.method())){witness(target);roots.add(new Dispatch(new Guard((Value)receiver,target.contract(),(target.method().access&Opcodes.ACC_PRIVATE)!=0),false));stack.add(receiver);}else if(fieldGetter(target.method(),null)){witness(target);root(target,(Value)receiver,(target.method().access&Opcodes.ACC_PRIVATE)!=0);FieldInsnNode field=(FieldInsnNode)body.get(1);String owner=fieldOwner(field,classes);if(owner==null)throw new IllegalArgumentException();Projection value=new Projection((Value)receiver,owner,field.name,field.desc);stack.add(value);}else{if(passed.size()!=2||!passed.get(0).equals(new Root(0))||!(passed.get(1)instanceof Decl recipe)||!(receiver instanceof Projection))throw new IllegalArgumentException();witness(target);loop(target,recipe);lambda=recipe;interaction=(Value)receiver;roots.add(new Dispatch(new Guard(interaction,target.contract(),false),false));stack.add("boolean");}}
   else if(instruction instanceof InvokeDynamicInsnNode factory){if(!factory.bsm.getOwner().equals("java/lang/invoke/LambdaMetafactory")||Type.getArgumentTypes(factory.desc).length!=0||factory.bsmArgs.length!=3||!(factory.bsmArgs[1]instanceof Handle handle)||handle.getTag()!=Opcodes.H_INVOKESTATIC)throw new IllegalArgumentException();Decl recipe=resolve(new Member(handle.getOwner(),handle.getName(),handle.getDesc()),classes,new HashSet<>());if(recipe==null)throw new IllegalArgumentException();witness(recipe);stack.add(recipe);}else if(instruction.getOpcode()==Opcodes.IRETURN){if(stack.size()!=1||!stack.removeLast().equals("boolean"))throw new IllegalArgumentException();}else throw new IllegalArgumentException();}return lambda==null?null:new Entry(lambda,interaction);
  }
  void loop(Decl decl,Decl recipe){List<AbstractInsnNode>code=ops(decl.method());int callbacks=0;for(var instruction:code){if(instruction instanceof MethodInsnNode call){if(call.owner.equals("java/util/Map")&&call.name.equals("entrySet")||call.owner.equals("java/util/Set")&&call.name.equals("iterator")||call.owner.equals("java/util/Iterator")&&(call.name.equals("hasNext")||call.name.equals("next"))||call.owner.equals("java/util/Map$Entry")&&(call.name.equals("getKey")||call.name.equals("getValue")))continue;Type[]passed=Type.getArgumentTypes(call.desc);if(call.getOpcode()!=Opcodes.INVOKEINTERFACE||passed.length!=3||!passed[0].equals(Type.getArgumentTypes(recipe.method().desc)[0])||!passed[1].equals(Type.getArgumentTypes(recipe.method().desc)[1])||!passed[2].equals(Type.DOUBLE_TYPE)||!Type.getReturnType(call.desc).equals(Type.BOOLEAN_TYPE)||!(next(call)instanceof JumpInsnNode branch&&branch.getOpcode()==Opcodes.IFEQ))throw new IllegalArgumentException();callbacks++;}else if(instruction instanceof FieldInsnNode field){if(field.getOpcode()!=Opcodes.GETFIELD)throw new IllegalArgumentException();}else if(instruction instanceof VarInsnNode||instruction instanceof TypeInsnNode||instruction instanceof JumpInsnNode||instruction instanceof InsnNode)continue;else throw new IllegalArgumentException();}if(callbacks!=1)throw new IllegalArgumentException();}
  void read(Member member,Value receiver,Set<Member>active){if(!active.add(member))throw new IllegalArgumentException();Decl decl=resolve(member,classes,new HashSet<>());if(decl==null)throw new IllegalArgumentException();ClassNode before=source.apply(decl.owner());MethodNode baseline=before==null?null:find(before,member.name(),member.descriptor());if(baseline==null||!sameBody(baseline,decl.method()))throw new IllegalArgumentException();root(decl,receiver,(decl.method().access&Opcodes.ACC_PRIVATE)!=0);for(var instruction:decl.method().instructions){if(instruction.getOpcode()<0)continue;if(instruction instanceof MethodInsnNode call){if(Type.getArgumentTypes(call.desc).length!=0||call.getOpcode()==Opcodes.INVOKESTATIC)throw new IllegalArgumentException();read(Member.of(call),receiver,active);}else if(instruction instanceof FieldInsnNode field){if(field.getOpcode()!=Opcodes.GETFIELD)throw new IllegalArgumentException();}else if(instruction instanceof VarInsnNode load){if(load.var!=0||load.getOpcode()!=Opcodes.ALOAD)throw new IllegalArgumentException();}else if(instruction instanceof JumpInsnNode||instruction instanceof InsnNode||instruction instanceof TypeInsnNode)continue;else throw new IllegalArgumentException();}active.remove(member);}
  Member question(Member member){Decl decl=resolve(member,classes,new HashSet<>());if(decl==null)throw new IllegalArgumentException();if(forwarder(decl.method())){root(decl,new Root(0),false);return question(Member.of((MethodInsnNode)ops(decl.method()).get(ops(decl.method()).size()-2)));}witness(decl);dispatchKey=net.forbric.kernel.boot.NativeDefaultDispatchPaths.register(decl.contract(),classes,carrier);List<AbstractInsnNode>code=ops(decl.method());MethodInsnNode terminal=null;for(var instruction:code)if(instruction instanceof MethodInsnNode call){Decl target=resolve(Member.of(call),classes,new HashSet<>());if(target!=null&&identity(target.method())){witness(target);roots.add(new Dispatch(new Guard(new Root(0),target.contract(),true),false));}else{if(terminal!=null)return null;terminal=call;}}if(terminal==null||!Type.getReturnType(terminal.desc).equals(Type.BOOLEAN_TYPE)||Type.getArgumentTypes(terminal.desc).length!=1)return null;Decl value=resolve(Member.of(terminal),classes,new HashSet<>());if(value==null)return null;witness(value);List<AbstractInsnNode>body=ops(value.method());if(body.size()!=3||!(body.get(0)instanceof VarInsnNode a&&a.var==0)||!(body.get(1)instanceof FieldInsnNode field&&field.getOpcode()==Opcodes.GETFIELD&&field.desc.equals("Z"))||body.get(2).getOpcode()!=Opcodes.IRETURN)return null;return Member.of(terminal);}
  void stateGetter(Member member,Value receiver,List<Guard>guards,Set<Member>active){if(!active.add(member))throw new IllegalArgumentException();Decl decl=resolve(member,classes,new HashSet<>());if(decl==null)throw new IllegalArgumentException();witness(decl);guards.add(new Guard(receiver,decl.contract(),(decl.method().access&Opcodes.ACC_PRIVATE)!=0));List<Object>stack=new ArrayList<>();for(var instruction:stripRecord(decl.method()).instructions){if(instruction.getOpcode()<0)continue;if(instruction instanceof VarInsnNode load&&load.getOpcode()==Opcodes.ALOAD&&load.var==0)stack.add(receiver);else if(instruction instanceof TypeInsnNode cast&&cast.getOpcode()==Opcodes.CHECKCAST){}else if(instruction instanceof FieldInsnNode field&&field.getOpcode()==Opcodes.GETFIELD){Value object=(Value)stack.removeLast();String owner=fieldOwner(field,classes);if(owner==null)throw new IllegalArgumentException();stack.add(new Projection(object,owner,field.name,field.desc));}else if(instruction instanceof MethodInsnNode call&&Type.getArgumentTypes(call.desc).length==0){Value object=(Value)stack.removeLast();Decl target=resolve(Member.of(call),classes,new HashSet<>());if(target==null)throw new IllegalArgumentException();if(identity(target.method())){witness(target);guards.add(new Guard(object,target.contract(),(target.method().access&Opcodes.ACC_PRIVATE)!=0));stack.add(object);}else if(Type.getReturnType(call.desc).getDescriptor().equals(TYPE)){define(target);guards.add(new Guard(object,target.contract(),false));stack.add("terminal");}else{stateGetter(Member.of(call),object,guards,active);List<AbstractInsnNode>body=ops(target.method());if(!fieldGetter(target.method(),null))throw new IllegalArgumentException();FieldInsnNode field=(FieldInsnNode)body.get(1);String owner=fieldOwner(field,classes);stack.add(new Projection(object,owner,field.name,field.desc));}}else if(instruction.getOpcode()==Opcodes.ARETURN){}else throw new IllegalArgumentException();}active.remove(member);}
  record Projected(Value value,String type){ }
  Projected projectionGetter(Member member,Value receiver,String concrete,List<Guard>guards,Set<Member>active){Member selected=new Member(concrete,member.name(),member.descriptor());Decl decl=resolve(selected,classes,new HashSet<>());if(decl==null||!active.add(selected))throw new IllegalArgumentException();witness(decl);guards.add(new Guard(receiver,decl.contract(),(decl.method().access&Opcodes.ACC_PRIVATE)!=0));List<Projected>stack=new ArrayList<>();Projected result=null;
   for(var instruction:decl.method().instructions){if(instruction.getOpcode()<0)continue;if(instruction instanceof VarInsnNode load&&load.getOpcode()==Opcodes.ALOAD&&load.var==0)stack.add(new Projected(receiver,concrete));else if(instruction instanceof FieldInsnNode field&&field.getOpcode()==Opcodes.GETFIELD){Projected object=stack.removeLast();String owner=fieldOwner(field,classes);if(owner==null||Type.getType(field.desc).getSort()!=Type.OBJECT)throw new IllegalArgumentException();stack.add(new Projected(new Projection(object.value(),owner,field.name,field.desc),Type.getType(field.desc).getInternalName()));}else if(instruction instanceof TypeInsnNode cast&&cast.getOpcode()==Opcodes.CHECKCAST){Projected object=stack.removeLast();stack.add(new Projected(object.value(),cast.desc));}else if(instruction instanceof MethodInsnNode call&&call.getOpcode()!=Opcodes.INVOKESTATIC&&Type.getArgumentTypes(call.desc).length==0){Projected object=stack.removeLast();stack.add(projectionGetter(Member.of(call),object.value(),object.type(),guards,active));}else if(instruction.getOpcode()==Opcodes.ARETURN){if(stack.size()!=1)throw new IllegalArgumentException();result=stack.removeLast();}else throw new IllegalArgumentException();}
   active.remove(selected);if(result==null)return null;return result;
  }
  void stateRead(Member member,Value receiver,List<Guard>guards,Set<Member>active){Decl decl=resolve(member,classes,new HashSet<>());if(decl==null)throw new IllegalArgumentException();ClassNode before=source.apply(decl.owner());MethodNode baseline=before==null?null:find(before,decl.method().name,decl.method().desc);if(baseline==null||!sameBody(baseline,decl.method()))throw new IllegalArgumentException();define(decl);guards.add(new Guard(receiver,decl.contract(),false));List<AbstractInsnNode>code=ops(decl.method());
   // The original predicate may directly read an immutable membership collection; its entire default is pinned.
   if(code.size()==5&&code.get(0)instanceof VarInsnNode direct&&direct.var==0&&code.get(1)instanceof FieldInsnNode&&code.get(2)instanceof VarInsnNode argument&&argument.var==1&&code.get(3)instanceof MethodInsnNode query&&query.owner.equals("java/util/Set")&&query.name.equals("contains")&&query.desc.equals("(Ljava/lang/Object;)Z")&&code.get(4).getOpcode()==Opcodes.IRETURN)return;
   if(code.size()!=5||!(code.get(0)instanceof VarInsnNode self&&self.var==0)||!(code.get(1)instanceof MethodInsnNode getter&&Type.getArgumentTypes(getter.desc).length==0)||!(code.get(2)instanceof VarInsnNode tag&&tag.var==1)||!(code.get(3)instanceof MethodInsnNode terminal&&terminal.desc.equals(member.descriptor()))||code.get(4).getOpcode()!=Opcodes.IRETURN)throw new IllegalArgumentException();Projected value=projectionGetter(Member.of(getter),receiver,member.owner(),guards,active);if(value==null)throw new IllegalArgumentException();Decl predicate=resolve(new Member(value.type(),terminal.name,terminal.desc),classes,new HashSet<>());if(predicate==null)throw new IllegalArgumentException();ClassNode original=source.apply(predicate.owner());MethodNode sourceBody=original==null?null:find(original,predicate.method().name,predicate.method().desc);if(sourceBody==null||!sameBody(sourceBody,predicate.method()))throw new IllegalArgumentException();define(predicate);guards.add(new Guard(value.value(),predicate.contract(),false));List<AbstractInsnNode>body=ops(predicate.method());if(body.size()!=5||!(body.get(0)instanceof VarInsnNode a&&a.var==0)||!(body.get(2)instanceof VarInsnNode b&&b.var==1)||!(body.get(3)instanceof MethodInsnNode contains&&contains.owner.equals("java/util/Set")&&contains.name.equals("contains")&&contains.desc.equals("(Ljava/lang/Object;)Z"))||body.get(4).getOpcode()!=Opcodes.IRETURN)throw new IllegalArgumentException();
   if(body.get(1)instanceof FieldInsnNode field&&field.getOpcode()==Opcodes.GETFIELD&&field.desc.equals("Ljava/util/Set;"))return;
   if(!(body.get(1)instanceof MethodInsnNode read&&read.desc.equals("()Ljava/util/Set;")))throw new IllegalArgumentException();Decl bound=resolve(Member.of(read),classes,new HashSet<>());if(bound==null||(bound.method().access&Opcodes.ACC_PRIVATE)==0)throw new IllegalArgumentException();witness(bound);guards.add(new Guard(value.value(),bound.contract(),true));List<AbstractInsnNode>checked=ops(bound.method());
   if(checked.size()!=11||!(checked.get(0)instanceof VarInsnNode load&&load.var==0)||!(checked.get(1)instanceof FieldInsnNode tags&&tags.getOpcode()==Opcodes.GETFIELD&&tags.desc.equals("Ljava/util/Set;"))||!(checked.get(2)instanceof JumpInsnNode exists&&exists.getOpcode()==Opcodes.IFNONNULL&&next(exists.label)==checked.get(8))||!(checked.get(3)instanceof TypeInsnNode failure&&failure.getOpcode()==Opcodes.NEW&&failure.desc.equals("java/lang/IllegalStateException"))||checked.get(4).getOpcode()!=Opcodes.DUP||!(checked.get(5)instanceof LdcInsnNode message&&message.cst instanceof String)||!(checked.get(6)instanceof MethodInsnNode init&&init.owner.equals(failure.desc)&&init.name.equals("<init>")&&init.desc.equals("(Ljava/lang/String;)V"))||checked.get(7).getOpcode()!=Opcodes.ATHROW||!(checked.get(8)instanceof VarInsnNode selfAgain&&selfAgain.var==0)||!(checked.get(9)instanceof FieldInsnNode again&&again.owner.equals(tags.owner)&&again.name.equals(tags.name)&&again.desc.equals(tags.desc))||checked.get(10).getOpcode()!=Opcodes.ARETURN)throw new IllegalArgumentException();}

 }
 static List<Integer>offsets(MethodNode method,Member target){List<Integer>result=new ArrayList<>();int offset=0;for(var instruction:method.instructions){if(instruction.getOpcode()<0)continue;if(instruction instanceof MethodInsnNode call){if(Member.of(call).equals(target))result.add(offset);offset+=call.getOpcode()==Opcodes.INVOKEINTERFACE?5:3;}else if(instruction instanceof FieldInsnNode||instruction instanceof TypeInsnNode||instruction instanceof JumpInsnNode)offset+=3;else if(instruction instanceof VarInsnNode variable){if(variable.var>=256)throw new IllegalArgumentException();offset+=variable.var<4?1:2;}else if(instruction instanceof InsnNode)offset++;else throw new IllegalArgumentException();}return result;}
 private static Site recordSite(Decl decl){Site found=null;for(var instruction:decl.method().instructions)if(instruction instanceof MethodInsnNode call&&call.owner.equals(PredicateGetterResultRecorder.RUNTIME)&&call.name.equals("capture")&&call.desc.equals(PredicateGetterResultRecorder.DESCRIPTOR)&&previous(call)instanceof LdcInsnNode ldc&&ldc.cst instanceof String id){MethodNode stripped=stripRecord(decl.method());Site expected=new Site(decl.owner(),decl.method().name,decl.method().desc,MixinInstructionFingerprint.hash(stripped));if(!expected.id().equals(id)||found!=null&&!found.equals(expected))return null;found=expected;}return found;}
 private static MethodNode stripRecord(MethodNode input){MethodNode copy=new MethodNode(input.access,input.name,input.desc,input.signature,input.exceptions.toArray(String[]::new));input.accept(copy);for(var instruction:copy.instructions.toArray())if(instruction instanceof MethodInsnNode call&&call.owner.equals(PredicateGetterResultRecorder.RUNTIME)&&call.name.equals("capture")&&call.desc.equals(PredicateGetterResultRecorder.DESCRIPTOR)){AbstractInsnNode id=previous(call),self=previous(id),dup=previous(self);if(!(id instanceof LdcInsnNode)||!(self instanceof VarInsnNode load&&load.getOpcode()==Opcodes.ALOAD&&load.var==0)||dup.getOpcode()!=Opcodes.DUP)throw new IllegalArgumentException();copy.instructions.remove(call);copy.instructions.remove(id);copy.instructions.remove(self);copy.instructions.remove(dup);}return copy;}
 private static boolean identity(MethodNode method){List<AbstractInsnNode>code=ops(method);return Type.getArgumentTypes(method.desc).length==0&&code.size()>=2&&code.size()<=3&&code.get(0)instanceof VarInsnNode a&&a.var==0&&a.getOpcode()==Opcodes.ALOAD&&code.getLast().getOpcode()==Opcodes.ARETURN&&(code.size()==2||code.get(1)instanceof TypeInsnNode cast&&cast.getOpcode()==Opcodes.CHECKCAST);}
 private static boolean forwarder(MethodNode method){List<AbstractInsnNode>code=ops(method);Type[]args=Type.getArgumentTypes(method.desc);if(code.size()!=args.length+3||!(code.get(0)instanceof VarInsnNode a&&a.var==0)||!(code.get(code.size()-2)instanceof MethodInsnNode call&&call.getOpcode()==Opcodes.INVOKESPECIAL&&call.itf&&call.name.equals(method.name)&&call.desc.equals(method.desc)))return false;int slot=1;for(int i=0;i<args.length;i++){if(!(code.get(i+1)instanceof VarInsnNode load&&load.var==slot&&load.getOpcode()==args[i].getOpcode(Opcodes.ILOAD)))return false;slot+=args[i].getSize();}return code.getLast().getOpcode()==Type.getReturnType(method.desc).getOpcode(Opcodes.IRETURN);}
 private static boolean fieldGetter(MethodNode method,FieldInsnNode expected){List<AbstractInsnNode>code=ops(method);return Type.getArgumentTypes(method.desc).length==0&&(code.size()==3||code.size()==4)&&code.get(0)instanceof VarInsnNode a&&a.var==0&&a.getOpcode()==Opcodes.ALOAD&&code.get(1)instanceof FieldInsnNode f&&f.getOpcode()==Opcodes.GETFIELD&&(expected==null||f.owner.equals(expected.owner)&&f.name.equals(expected.name)&&f.desc.equals(expected.desc))&&code.getLast().getOpcode()==Opcodes.ARETURN&&(code.size()==3||code.get(2)instanceof TypeInsnNode c&&c.getOpcode()==Opcodes.CHECKCAST);}
 private static String fieldOwner(FieldInsnNode field,Function<String,ClassNode>classes){Set<String>seen=new HashSet<>();for(String owner=field.owner;owner!=null&&seen.add(owner);){ClassNode node=classes.apply(owner);if(node==null)return null;for(FieldNode found:node.fields)if(found.name.equals(field.name)&&found.desc.equals(field.desc))return(found.access&Opcodes.ACC_FINAL)!=0&&(found.access&Opcodes.ACC_STATIC)==0?owner:null;owner=node.superName;}return null;}
 private static Decl resolve(Member member,Function<String,ClassNode>classes,Set<String>seen){if(!seen.add(member.owner()))return null;ClassNode owner=classes.apply(member.owner());if(owner==null)return null;MethodNode own=find(owner,member.name(),member.descriptor());if(own!=null)return new Decl(owner.name,own);if(owner.superName!=null){Decl inherited=resolve(new Member(owner.superName,member.name(),member.descriptor()),classes,seen);if(inherited!=null)return inherited;}Decl found=null;for(String iface:owner.interfaces){Decl inherited=resolve(new Member(iface,member.name(),member.descriptor()),classes,seen);if(inherited!=null){if(found!=null&&!found.equals(inherited))return null;found=inherited;}}return found;}
 private static MethodNode find(ClassNode owner,String name,String desc){return owner.methods.stream().filter(m->m.name.equals(name)&&m.desc.equals(desc)).findFirst().orElse(null);}private static MethodInsnNode unique(MethodNode method,Member member){MethodInsnNode found=null;for(var i:method.instructions)if(i instanceof MethodInsnNode call&&Member.of(call).equals(member)){if(found!=null)return null;found=call;}return found;}
 private static boolean sameBody(MethodNode a,MethodNode b){return MixinInstructionFingerprint.hash(a).equals(MixinInstructionFingerprint.hash(b));}private static List<AbstractInsnNode>ops(MethodNode method){List<AbstractInsnNode>result=new ArrayList<>();for(var i:method.instructions)if(i.getOpcode()>=0)result.add(i);return result;}private static List<AbstractInsnNode>between(AbstractInsnNode start,AbstractInsnNode end){List<AbstractInsnNode>result=new ArrayList<>();for(var i=start;i!=null&&i!=end;i=next(i))result.add(i);return result;}private static AbstractInsnNode previous(AbstractInsnNode insn){for(var i=insn.getPrevious();i!=null;i=i.getPrevious())if(i.getOpcode()>=0)return i;return null;}private static AbstractInsnNode next(AbstractInsnNode insn){for(var i=insn.getNext();i!=null;i=i.getNext())if(i.getOpcode()>=0)return i;return null;}
}
