/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;
import java.util.*;import java.util.function.Function;import org.objectweb.asm.*;import org.objectweb.asm.tree.*;
import net.forbric.api.Ecosystem;import net.forbric.kernel.boot.*;import net.forbric.kernel.boot.KernelTagFacadeContracts.*;import net.forbric.kernel.transform.*;
/** Rebuilds an indexed legacy field/container facade from a unique current tag-to-type forwarding recipe. */
public final class NativeTagSourceFacadeInjector implements ClassTransformer,Opcodes{
 public static final String PROPERTY="forbric.nativeTagSourceFacades";private static final String RUNTIME="net/forbric/kernel/runtime/KernelTagFacadeSources";
 private static final ThreadLocal<Set<String>>ACTIVE=ThreadLocal.withInitial(HashSet::new);
 public static boolean enabled(){return!"off".equalsIgnoreCase(System.getProperty(PROPERTY,"on"));}
 @Override public AnchorSet anchors(){return AnchorSet.scanned("proved original tag/container facades");}
 @Override public byte[]transform(String name,byte[]bytes,TransformContext context){if(!enabled()||bytes==null)return bytes;ClassNode current=node(bytes),original=NativeGameReferences.reference(Ecosystem.FABRIC,current.name);if(original==null||!adapt(original,current,NativeGameReferences::current))return bytes;ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_MAXS);current.accept(w);return w.toByteArray();}
 static boolean adapt(ClassNode original,ClassNode current,Function<String,ClassNode>reader){Set<String>active=ACTIVE.get();if(!active.add(current.name))return false;try{Function<String,ClassNode>classes=owner->owner.equals(current.name)?current:active.contains(owner)?null:reader.apply(owner);return adaptClosed(original,current,classes);}finally{active.remove(current.name);if(active.isEmpty())ACTIVE.remove();}}
 private static boolean adaptClosed(ClassNode original,ClassNode current,Function<String,ClassNode>classes){boolean changed=false;for(MethodNode old:original.methods){MethodNode live=method(current,old.name,old.desc);if(live==null||!safe(old)||!safe(live))continue;List<AbstractInsnNode>source=code(old);Type[]args=Type.getArgumentTypes(old.desc);Type out=Type.getReturnType(old.desc);if(args.length==0||args[0].getSort()!=Type.OBJECT||source.size()!=args.length+4||!aload(source.get(0),0)||!(source.get(1)instanceof FieldInsnNode field&&field.getOpcode()==GETFIELD&&field.owner.equals(original.name))||!(source.get(source.size()-2)instanceof MethodInsnNode tagCall&&tagCall.getOpcode()==INVOKEVIRTUAL&&tagCall.desc.equals(old.desc))||source.getLast().getOpcode()!=out.getOpcode(IRETURN)||!arguments(source.subList(2,source.size()-2),args))continue;
  if(!potential(live,args,out,current.name))continue;ClassNode container=classes.apply(tagCall.owner);if(container==null||!Type.getType(field.desc).equals(Type.getObjectType(container.name)))continue;MethodNode containerTag=method(container,tagCall.name,tagCall.desc);if(containerTag==null||!safe(containerTag))continue;String collector=collectorKey(container);if(collector==null)continue;
  List<AbstractInsnNode>body=code(live);int start=-1;MethodInsnNode mapper=null;for(int i=0;i<body.size();i++)if(body.get(i)instanceof MethodInsnNode call&&call.getOpcode()==INVOKESTATIC&&call.desc.startsWith("("+args[0].getDescriptor()+")L")){if(mapper!=null){mapper=null;break;}mapper=call;start=i-2;}if(mapper==null||start<0)continue;ClassNode mapperOwner=classes.apply(mapper.owner);MethodNode mapBody=mapperOwner==null?null:method(mapperOwner,mapper.name,mapper.desc);if(mapBody==null||(mapBody.access&(ACC_STATIC|ACC_ABSTRACT|ACC_NATIVE|ACC_SYNCHRONIZED))!=ACC_STATIC||!accessibleMapper(current.name,mapper.owner,mapBody.access))continue;List<AbstractInsnNode>tail=body.subList(start,body.size());if(tail.size()!=args.length+4||!aload(tail.get(0),0)||!aload(tail.get(1),1)||tail.get(2)!=mapper||!(tail.get(tail.size()-2)instanceof MethodInsnNode typedCall&&typedCall.getOpcode()==INVOKEVIRTUAL&&typedCall.owner.equals(current.name))||tail.getLast().getOpcode()!=out.getOpcode(IRETURN))continue;Type[]typedArgs=args.clone();typedArgs[0]=Type.getReturnType(mapper.desc);if(!typedCall.desc.equals(Type.getMethodDescriptor(out,typedArgs))||!arguments(tail.subList(3,tail.size()-2),Arrays.copyOfRange(args,1,args.length),1+args[0].getSize()))continue;MethodNode typed=method(current,typedCall.name,typedCall.desc);if(typed==null||!safe(typed))continue;List<AbstractInsnNode>typedBody=code(typed);if(typedBody.size()!=args.length+4||!aload(typedBody.get(0),0)||!(typedBody.get(1)instanceof FieldInsnNode actualField&&same(field,actualField))||!arguments(typedBody.subList(2,typedBody.size()-2),typedArgs)||!(typedBody.get(typedBody.size()-2)instanceof MethodInsnNode containerTypedCall&&containerTypedCall.getOpcode()==INVOKEVIRTUAL&&containerTypedCall.owner.equals(container.name)&&containerTypedCall.desc.equals(typedCall.desc))||typedBody.getLast().getOpcode()!=out.getOpcode(IRETURN))continue;MethodNode containerTyped=method(container,containerTypedCall.name,containerTypedCall.desc);FieldNode containerField=current.fields.stream().filter(f->f.name.equals(field.name)&&f.desc.equals(field.desc)).findFirst().orElse(null);if(containerTyped==null||!safe(containerTyped)||containerField==null||(containerField.access&(ACC_STATIC|ACC_VOLATILE))!=0)continue;
  InsnList prefix=prefix(live,body,start,field,container);if(prefix==null)continue;int typeSlot=1;for(Type a:args)typeSlot+=a.getSize();int containerSlot=typeSlot+1;InsnList replacement=new InsnList();replacement.add(prefix);replacement.add(new VarInsnNode(ALOAD,1));replacement.add(new MethodInsnNode(mapper.getOpcode(),mapper.owner,mapper.name,mapper.desc,mapper.itf));replacement.add(new VarInsnNode(ASTORE,typeSlot));replacement.add(new VarInsnNode(ALOAD,0));replacement.add(field.clone(new IdentityHashMap<>()));replacement.add(new VarInsnNode(ASTORE,containerSlot));replacement.add(new VarInsnNode(ALOAD,0));replacement.add(new VarInsnNode(ALOAD,containerSlot));replacement.add(new VarInsnNode(ALOAD,typeSlot));String key=current.name+"."+live.name+live.desc+":"+MixinInstructionFingerprint.hash(old)+":"+MixinInstructionFingerprint.hash(typed)+":"+MixinInstructionFingerprint.hash(containerTag)+":"+MixinInstructionFingerprint.hash(containerTyped)+":"+MixinInstructionFingerprint.hash(mapBody)+":"+collector+":"+containerField.access+":"+live.access+":"+typed.access+":"+containerTag.access+":"+containerTyped.access+":"+mapBody.access;replacement.add(new LdcInsnNode(key));replacement.add(new MethodInsnNode(INVOKESTATIC,RUNTIME,"permits","(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)Z",false));LabelNode nativeOnly=new LabelNode();replacement.add(new JumpInsnNode(IFEQ,nativeOnly));replacement.add(new VarInsnNode(ALOAD,containerSlot));load(replacement,args,1);replacement.add(new MethodInsnNode(tagCall.getOpcode(),tagCall.owner,tagCall.name,tagCall.desc,tagCall.itf));replacement.add(new InsnNode(out.getOpcode(IRETURN)));replacement.add(nativeOnly);replacement.add(new VarInsnNode(ALOAD,0));replacement.add(new VarInsnNode(ALOAD,typeSlot));load(replacement,Arrays.copyOfRange(args,1,args.length),1+args[0].getSize());replacement.add(new MethodInsnNode(typedCall.getOpcode(),typedCall.owner,typedCall.name,typedCall.desc,typedCall.itf));replacement.add(new InsnNode(out.getOpcode(IRETURN)));live.instructions=replacement;live.tryCatchBlocks.clear();live.localVariables=null;live.visibleLocalVariableAnnotations=null;live.invisibleLocalVariableAnnotations=null;live.maxLocals=containerSlot+1;live.maxStack=12;
  // Expanded frames are recomputed below for this one closed, acyclic facade.
  ClassWriter frames=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS){@Override protected String getCommonSuperClass(String a,String b){return a.equals(b)?a:"java/lang/Object";}};ClassNode single=new ClassNode();single.version=current.version;single.access=current.access;single.name=current.name;single.superName=current.superName;single.interfaces=new ArrayList<>(current.interfaces);single.methods.add(live);single.accept(frames);MethodNode framed=node(frames.toByteArray()).methods.getFirst();current.methods.set(current.methods.indexOf(live),framed);
  KernelTagFacadeContracts.register(key,new Schema(collector,new FieldShape(current.name,field.name,field.desc,containerField.access),shape(current.name,framed),shape(mapper.owner,mapBody),shape(current.name,typed),shape(container.name,containerTag),shape(container.name,containerTyped)));changed=true;
 }return changed;}
 private static boolean potential(MethodNode live,Type[]args,Type out,String owner){List<AbstractInsnNode>body=code(live);for(int i=2;i<body.size();i++)if(body.get(i)instanceof MethodInsnNode call&&call.getOpcode()==INVOKESTATIC&&call.desc.startsWith("("+args[0].getDescriptor()+")L")&&body.size()-(i-2)==args.length+4&&aload(body.get(i-2),0)&&aload(body.get(i-1),1)&&body.get(body.size()-2)instanceof MethodInsnNode delegate&&delegate.getOpcode()==INVOKEVIRTUAL&&delegate.owner.equals(owner)&&body.getLast().getOpcode()==out.getOpcode(IRETURN))return true;return false;}
 private static InsnList prefix(MethodNode live,List<AbstractInsnNode>body,int start,FieldInsnNode field,ClassNode container){if(start==0)return new InsnList();List<AbstractInsnNode>p=body.subList(0,start);if(p.size()!=10||!aload(p.get(0),1)||!(p.get(1)instanceof MethodInsnNode test&&test.getOpcode()==INVOKESTATIC&&test.owner.equals("net/forbric/kernel/runtime/KernelFluidTypes")&&test.name.equals("hasTagType")&&Type.getReturnType(test.desc)==Type.BOOLEAN_TYPE)||!(p.get(2)instanceof JumpInsnNode skip&&skip.getOpcode()==IFNE)||!aload(p.get(3),0)||!(p.get(4)instanceof FieldInsnNode actualField&&same(field,actualField))||!aload(p.get(5),1)||!(p.get(6)instanceof MethodInsnNode lookup&&lookup.getOpcode()==INVOKEVIRTUAL&&lookup.owner.equals(container.name)&&Type.getReturnType(lookup.desc).getSort()==Type.OBJECT)||!(p.get(7)instanceof JumpInsnNode found&&found.getOpcode()==IFNONNULL)||p.get(8).getOpcode()!=ICONST_0||p.get(9).getOpcode()!=IRETURN||next(skip.label)!=body.get(start)||next(found.label)!=body.get(start))return null;Map<LabelNode,LabelNode>labels=new IdentityHashMap<>();for(var i:live.instructions)if(i instanceof LabelNode l)labels.put(l,new LabelNode());LabelNode joined=new LabelNode();labels.put(skip.label,joined);labels.put(found.label,joined);InsnList result=new InsnList();for(var i:live.instructions){if(i==body.get(start))break;if(i instanceof LabelNode l&&next(l)==body.get(start))continue;if(i instanceof FrameNode||i instanceof LineNumberNode)continue;result.add(i.clone(labels));}result.add(joined);return result;}
 private static String collectorKey(ClassNode container){String key=null;for(MethodNode method:container.methods)for(var i:method.instructions)if(i instanceof MethodInsnNode call&&call.getOpcode()==INVOKESTATIC&&call.owner.equals("net/forbric/kernel/runtime/KernelFabricTagViews")&&call.name.equals("begin")){var before=previous(call);if(!(before instanceof LdcInsnNode value&&value.cst instanceof String id)||key!=null&&!key.equals(id))return null;key=id;}return key;}
 private static boolean accessibleMapper(String caller,String owner,int flags){return(flags&ACC_PUBLIC)!=0||caller.equals(owner)||(flags&ACC_PRIVATE)==0&&caller.substring(0,caller.lastIndexOf('/')+1).equals(owner.substring(0,owner.lastIndexOf('/')+1));}
 private static MethodShape shape(String owner,MethodNode m){return new MethodShape(new DefinedMethodContracts.MethodContract(owner,m.name,m.desc,MixinInstructionFingerprint.hash(m)),m.access);}
 private static boolean safe(MethodNode m){return(m.access&ACC_PUBLIC)!=0&&(m.access&(ACC_STATIC|ACC_ABSTRACT|ACC_NATIVE|ACC_SYNCHRONIZED))==0&&m.tryCatchBlocks.isEmpty();}
 private static boolean same(FieldInsnNode a,FieldInsnNode b){return a.getOpcode()==b.getOpcode()&&a.owner.equals(b.owner)&&a.name.equals(b.name)&&a.desc.equals(b.desc);}
 private static boolean arguments(List<AbstractInsnNode>code,Type[]args){return arguments(code,args,1);}
 private static boolean arguments(List<AbstractInsnNode>code,Type[]args,int slot){if(code.size()!=args.length)return false;for(int i=0;i<args.length;i++){if(!(code.get(i)instanceof VarInsnNode load&&load.var==slot&&load.getOpcode()==args[i].getOpcode(ILOAD)))return false;slot+=args[i].getSize();}return true;}
 private static void load(InsnList code,Type[]args,int slot){for(Type arg:args){code.add(new VarInsnNode(arg.getOpcode(ILOAD),slot));slot+=arg.getSize();}}
 private static boolean aload(AbstractInsnNode i,int slot){return i instanceof VarInsnNode load&&load.getOpcode()==ALOAD&&load.var==slot;}
 private static AbstractInsnNode previous(AbstractInsnNode i){i=i.getPrevious();while(i!=null&&i.getOpcode()<0)i=i.getPrevious();return i;}
 private static AbstractInsnNode next(AbstractInsnNode i){while(i!=null&&i.getOpcode()<0)i=i.getNext();return i;}
 private static List<AbstractInsnNode>code(MethodNode m){List<AbstractInsnNode>result=new ArrayList<>();for(var i:m.instructions)if(i.getOpcode()>=0)result.add(i);return result;}
 private static MethodNode method(ClassNode n,String name,String desc){return n.methods.stream().filter(m->m.name.equals(name)&&m.desc.equals(desc)).findFirst().orElse(null);}
 private static ClassNode node(byte[]bytes){ClassNode n=new ClassNode();new ClassReader(bytes).accept(n,0);return n;}
}
