/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.mixin;

import java.util.*;
import java.util.function.Function;
import org.objectweb.asm.*;
import org.objectweb.asm.tree.*;
import net.forbric.api.Ecosystem;
import net.forbric.api.ForeignType;
import net.forbric.kernel.boot.DefinedMethodContracts;
import net.forbric.kernel.boot.DefinedMethodContracts.MethodContract;
import net.forbric.kernel.boot.KernelTagSourceContracts;
import net.forbric.kernel.transform.*;
import net.forbric.kernel.util.ForbricLog;

/** Restores a native constructor's tag view from the same current physical samples. No world scan is replayed. */
public final class NativeTagTrackerSourceInjector implements ClassTransformer{
	public static final String PROPERTY="forbric.nativeTagTrackerSource";
	private static final String RUNTIME="net/forbric/kernel/runtime/KernelFabricTagViews",MAP="Ljava/util/Map;",TYPE=ForeignType.FLUID_TYPE.internal(Ecosystem.NEOFORGE);
	private final Function<String,ClassNode>originals,classes;
	public NativeTagTrackerSourceInjector(){this(name->NativeGameReferences.reference(Ecosystem.FABRIC,name),NativeGameReferences::current);}
	public NativeTagTrackerSourceInjector(Function<String,ClassNode>originals,Function<String,ClassNode>classes){this.originals=originals;this.classes=classes;}
	@Override public String name(){return "forbric-native-tag-tracker-source";}
	@Override public AnchorSet anchors(){return AnchorSet.scanned("native tag constructors and physical metric schemas are discovered structurally");}
	@Override public byte[]transform(String binary,byte[]bytes,TransformContext context){
		if("off".equalsIgnoreCase(System.getProperty(PROPERTY,"on"))||bytes==null||!mentions(bytes,"net/minecraft/tags/TagKey"))return bytes;
		ClassNode current=parse(bytes);if(current.methods.stream().noneMatch(m->m.name.equals("<init>")&&m.desc.equals("(Ljava/util/Set;)V")))return bytes;
		ClassNode original=originals.apply(current.name);if(original==null||!repair(current,original,classes,originals))return bytes;
		ClassWriter writer=new Frames(current,classes);current.accept(writer);ForbricLog.info("[Forbric/Fluid] %s retains its native tag tracker order and metrics beside type tracking, using the same physical samples",binary);return writer.toByteArray();
	}
	static boolean repair(ClassNode current,ClassNode original,Function<String,ClassNode>classes,Function<String,ClassNode>originals){try{
		String prefix="$forbricTagSource$"+Integer.toHexString(original.name.hashCode()),sourceMap=prefix+"Map",ready=prefix+"Ready";
		if(current.fields.stream().anyMatch(f->f.name.equals(sourceMap)))return false;
		MethodNode sourceCtor=method(original,"<init>","(Ljava/util/Set;)V"),ctor=method(current,"<init>","(Ljava/util/Set;)V");if(sourceCtor==null||ctor==null||!sourceCtor.tryCatchBlocks.isEmpty())return false;
		List<TypeInsnNode>allocations=new ArrayList<>();FieldInsnNode mapField=null;String tag=null;
		for(var i:sourceCtor.instructions){if(i instanceof TypeInsnNode allocation&&allocation.getOpcode()==Opcodes.NEW)allocations.add(allocation);if(i instanceof FieldInsnNode f&&f.getOpcode()==Opcodes.PUTFIELD&&f.desc.equals(MAP)){if(mapField!=null)return false;mapField=f;}if(i instanceof TypeInsnNode cast&&cast.getOpcode()==Opcodes.CHECKCAST)tag=cast.desc;}
		if(allocations.size()!=2||mapField==null||tag==null)return false;String mapName=mapField.name;if(current.fields.stream().noneMatch(f->f.name.equals(mapName)&&f.desc.equals(MAP)))return false;
		String tracker=allocations.getLast().desc;ClassNode sourceTracker=classes.apply(tracker),nativeTracker=originals.apply(tracker);if(sourceTracker==null||nativeTracker==null)return false;
		NativeTagMetricTemplate.Template template=NativeTagMetricTemplate.derive(original,current,tracker,prefix+"Metric");if(template==null)return false;
		FieldInsnNode primary=mapField;String tagType=tag;
		List<MethodNode>tagMethods=original.methods.stream().filter(m->(m.access&Opcodes.ACC_PUBLIC)!=0&&Type.getArgumentTypes(m.desc).length>0&&Type.getArgumentTypes(m.desc)[0].equals(Type.getObjectType(tagType))).toList();if(tagMethods.isEmpty())return false;
		MethodNode lookup=original.methods.stream().filter(m->Type.getArgumentTypes(m.desc).length==1&&Type.getArgumentTypes(m.desc)[0].equals(Type.getObjectType(template.fluid()))&&Type.getReturnType(m.desc).equals(Type.getObjectType(tracker))).findFirst().orElse(null);if(lookup==null)return false;
		MethodInsnNode query=null;for(var i:lookup.instructions)if(i instanceof MethodInsnNode call&&call.desc.equals("(L"+tag+";)Z")){if(query!=null)return false;query=call;}if(query==null)return false;
		ClassNode fluid=classes.apply(template.fluid());if(fluid==null)return false;MethodNode queryBody=method(fluid,query.name,query.desc),typeBody=method(fluid,template.typeGetter().name,template.typeGetter().desc);if(queryBody==null||typeBody==null)return false;
		String id=MixinInstructionFingerprint.hash(sourceCtor)+":"+MixinInstructionFingerprint.hash(template.source())+":"+MixinInstructionFingerprint.hash(ctor)+":"+MixinInstructionFingerprint.hash(template.current())+":"+MixinInstructionFingerprint.hash(queryBody)+":"+MixinInstructionFingerprint.hash(typeBody);
		Map<String,String>names=new HashMap<>();for(MethodNode m:tagMethods)names.put(m.name+m.desc,prefix+m.name);
		current.fields.add(new FieldNode(Opcodes.ACC_PRIVATE|Opcodes.ACC_FINAL,sourceMap,MAP,null,null));current.fields.add(new FieldNode(Opcodes.ACC_PRIVATE,ready,"Z",null,null));
		MethodNode extract=extract(current,sourceCtor,primary,tracker,sourceMap,prefix+"Extract",id);current.methods.add(extract);
		for(var i:new ArrayList<>(Arrays.asList(ctor.instructions.toArray())))if(i.getOpcode()==Opcodes.RETURN){InsnList init=new InsnList();init.add(new VarInsnNode(Opcodes.ALOAD,0));init.add(new VarInsnNode(Opcodes.ALOAD,0));init.add(new VarInsnNode(Opcodes.ALOAD,1));init.add(new VarInsnNode(Opcodes.ALOAD,0));init.add(new FieldInsnNode(Opcodes.GETFIELD,current.name,primary.name,MAP));init.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,current.name,extract.name,extract.desc,false));init.add(new FieldInsnNode(Opcodes.PUTFIELD,current.name,sourceMap,MAP));ctor.instructions.insertBefore(i,init);}
		MethodNode sourceLookup=copy(lookup,prefix+"Lookup",Opcodes.ACC_PRIVATE,current.name,primary.name,sourceMap,names);current.methods.add(sourceLookup);
		List<MethodNode>resets=nativeTracker.methods.stream().filter(m->m.desc.equals("()V")&&m.instructions.size()>0&&!m.name.equals("<init>")&&!m.name.equals("<clinit>")).toList();if(resets.size()!=1)return false;MethodNode reset=resets.getFirst();
		MethodNode resetCopy=staticCopy(reset,prefix+"Reset",tracker);current.methods.add(resetCopy);MethodNode begin=begin(current,sourceMap,ready,tracker,resetCopy,prefix+"Begin",id);current.methods.add(begin);
		List<MethodNode>rewritten=new ArrayList<>();for(MethodNode source:tagMethods){MethodNode live=method(current,source.name,source.desc);if(live==null)return false;MethodNode helper=copy(source,names.get(source.name+source.desc),Opcodes.ACC_PRIVATE,current.name,primary.name,sourceMap,names);current.methods.add(helper);if(!forwarder(live,current.name,tag,TYPE,helper,sourceMap,ready,primary.name))return false;rewritten.add(live);}
		for(MethodNode live:current.methods)if(Type.getArgumentTypes(live.desc).length==1&&Type.getArgumentTypes(live.desc)[0].equals(Type.getObjectType(tag))&&Type.getReturnType(live.desc).equals(Type.getObjectType(tracker))&&directTrackerGetter(live,current.name,primary.name,sourceMap,tracker))rewritten.add(live);
		instrument(current,template,sourceLookup,begin,ready,id);
		current.methods.add(template.metric());
		List<MethodContract>definitions=new ArrayList<>();definitions.add(contract(current.name,ctor));definitions.add(contract(current.name,extract));definitions.add(contract(current.name,sourceLookup));definitions.add(contract(current.name,begin));definitions.add(contract(current.name,resetCopy));definitions.add(contract(current.name,template.metric()));for(MethodNode m:rewritten)definitions.add(contract(current.name,m));for(MethodNode m:current.methods)if(names.containsValue(m.name))definitions.add(contract(current.name,m));
		Set<String>trackerSymbols=new HashSet<>();trackerSymbols.add(reset.name+reset.desc);for(var instruction:template.metric().instructions)if(instruction instanceof MethodInsnNode call&&call.owner.equals(tracker))trackerSymbols.add(call.name+call.desc);
		for(MethodNode source:nativeTracker.methods){MethodNode live=method(sourceTracker,source.name,source.desc);if(live==null||trackerSymbols.contains(source.name+source.desc)&&!MixinInstructionFingerprint.hash(source).equals(MixinInstructionFingerprint.hash(live)))return false;definitions.add(contract(sourceTracker.name,live));}
		ClassNode vector=classes.apply(template.vector()),nativeVector=originals.apply(template.vector());if(vector==null||nativeVector==null)return false;List<MethodContract>vectorMethods=new ArrayList<>();Set<String>vectorSymbols=new HashSet<>();
		for(MethodNode source:nativeTracker.methods)if(trackerSymbols.contains(source.name+source.desc))for(var instruction:source.instructions)if(instruction instanceof MethodInsnNode call&&call.owner.equals(template.vector())&&call.getOpcode()!=Opcodes.INVOKESTATIC)vectorSymbols.add(call.name+call.desc);
		for(var instruction:template.metric().instructions)if(instruction instanceof MethodInsnNode call&&call.owner.equals(template.vector())&&call.getOpcode()!=Opcodes.INVOKESTATIC)vectorSymbols.add(call.name+call.desc);
		boolean expanded;do{expanded=false;for(MethodNode candidate:vector.methods)if(vectorSymbols.contains(candidate.name+candidate.desc))for(var instruction:candidate.instructions)if(instruction instanceof MethodInsnNode call&&call.owner.equals(vector.name))expanded|=vectorSymbols.add(call.name+call.desc);}while(expanded);
		for(MethodNode dependency:vector.methods)if(dependency.name.equals("<clinit>")||dependency.name.equals("<init>")||vectorSymbols.contains(dependency.name+dependency.desc)){MethodNode nativeBody=method(nativeVector,dependency.name,dependency.desc);if(nativeBody==null||!MixinInstructionFingerprint.hash(nativeBody).equals(MixinInstructionFingerprint.hash(dependency)))return false;definitions.add(contract(vector.name,dependency));if(!dependency.name.startsWith("<"))vectorMethods.add(contract(vector.name,dependency));}
		Map<String,Integer>flags=new HashMap<>();for(MethodContract dependency:definitions){ClassNode declaration=dependency.owner().equals(current.name.replace('/','.'))?current:classes.apply(dependency.owner().replace('.','/'));if(declaration==null)return false;MethodNode body=method(declaration,dependency.name(),dependency.descriptor());if(body==null)return false;flags.put(dependency.owner()+"#"+dependency.name()+dependency.descriptor(),body.access);}
		List<KernelTagSourceContracts.FieldShape>fields=new ArrayList<>();Set<String>fieldKeys=new HashSet<>();
		for(MethodContract dependency:definitions){ClassNode declaration=dependency.owner().equals(current.name.replace('/','.'))?current:classes.apply(dependency.owner().replace('.','/'));MethodNode body=method(declaration,dependency.name(),dependency.descriptor());for(var instruction:body.instructions)if(instruction instanceof FieldInsnNode field){KernelTagSourceContracts.FieldShape shape=fieldShape(field,current,classes);if(shape==null)return false;if(fieldKeys.add(shape.owner()+"#"+shape.name()))fields.add(shape);}}
		KernelTagSourceContracts.register(id,new KernelTagSourceContracts.Schema(current.name,sourceMap,ready,tracker,tag,contract(current.name,template.current()),definitions,vectorMethods,flags,fields,contract(fluid.name,queryBody),contract(fluid.name,typeBody)));
		return true;
	}catch(RuntimeException unsupported){return false;}}
	private static KernelTagSourceContracts.FieldShape fieldShape(FieldInsnNode instruction,ClassNode current,Function<String,ClassNode>classes){
		String owner=instruction.owner;Set<String>seen=new HashSet<>();while(owner!=null&&seen.add(owner)){ClassNode declaration=owner.equals(current.name)?current:classes.apply(owner);if(declaration==null){try(var in=NativeTagTrackerSourceInjector.class.getClassLoader().getResourceAsStream(owner+".class")){if(in!=null)declaration=parse(in.readAllBytes());}catch(java.io.IOException unavailable){return null;}}if(declaration==null)return null;
			for(FieldNode field:declaration.fields)if(field.name.equals(instruction.name)){boolean staticInsn=instruction.getOpcode()==Opcodes.GETSTATIC||instruction.getOpcode()==Opcodes.PUTSTATIC;if(!field.desc.equals(instruction.desc)||staticInsn!=((field.access&Opcodes.ACC_STATIC)!=0))return null;return new KernelTagSourceContracts.FieldShape(declaration.name,field.name,field.desc,field.access);}owner=declaration.superName;
		}return null;
	}
	private static MethodNode extract(ClassNode owner,MethodNode source,FieldInsnNode primary,String tracker,String field,String name,String key){
		MethodNode result=new MethodNode(Opcodes.ACC_PRIVATE,name,"(Ljava/util/Set;"+MAP+")"+MAP,null,null);LabelNode valid=new LabelNode();result.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));result.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));result.instructions.add(new VarInsnNode(Opcodes.ALOAD,2));result.instructions.add(new LdcInsnNode(key));result.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"construct","(Ljava/lang/Object;Ljava/util/Set;Ljava/util/Map;Ljava/lang/String;)Z",false));result.instructions.add(new JumpInsnNode(Opcodes.IFNE,valid));result.instructions.add(new InsnNode(Opcodes.ACONST_NULL));result.instructions.add(new InsnNode(Opcodes.ARETURN));result.instructions.add(valid);
		MethodNode body=copy(source,"body",source.access,owner.name,primary.name,field,Map.of());Map<LabelNode,LabelNode>labels=labels(body.instructions);int map=source.maxLocals+1;
		Set<AbstractInsnNode>skip=Collections.newSetFromMap(new IdentityHashMap<>());Map<AbstractInsnNode,InsnList>replace=new IdentityHashMap<>();
		for(var i:body.instructions){
			if(i instanceof VarInsnNode load&&load.getOpcode()==Opcodes.ALOAD&&load.var==0){AbstractInsnNode following=next(i);
				if(following instanceof MethodInsnNode call&&call.getOpcode()==Opcodes.INVOKESPECIAL&&call.name.equals("<init>")&&call.owner.equals("java/lang/Object")&&call.desc.equals("()V")){skip.add(i);skip.add(following);}
				else if(following instanceof TypeInsnNode allocation&&allocation.getOpcode()==Opcodes.NEW&&!allocation.desc.equals(tracker))skip.add(i);
				else if(following instanceof FieldInsnNode f&&f.getOpcode()==Opcodes.GETFIELD&&f.owner.equals(owner.name)&&f.name.equals(field)&&f.desc.equals(MAP)){InsnList read=new InsnList();read.add(new VarInsnNode(Opcodes.ALOAD,map));replace.put(i,read);skip.add(following);}
			}
			if(i instanceof FieldInsnNode f&&f.getOpcode()==Opcodes.PUTFIELD&&f.owner.equals(owner.name)&&f.name.equals(field)&&f.desc.equals(MAP)){InsnList store=new InsnList();store.add(new VarInsnNode(Opcodes.ASTORE,map));replace.put(i,store);}
			if(i instanceof TypeInsnNode allocation&&allocation.getOpcode()==Opcodes.NEW&&allocation.desc.equals(tracker)){
				if(!(previous(i)instanceof VarInsnNode tagLoad&&tagLoad.getOpcode()==Opcodes.ALOAD))throw new IllegalArgumentException();int tagLocal=tagLoad.var>=2?tagLoad.var+1:tagLoad.var;
				AbstractInsnNode dup=next(i),constructor=next(dup);if(dup==null||dup.getOpcode()!=Opcodes.DUP||!(constructor instanceof MethodInsnNode call&&call.getOpcode()==Opcodes.INVOKESPECIAL&&call.owner.equals(tracker)&&call.name.equals("<init>")&&call.desc.equals("()V")))throw new IllegalArgumentException();
				InsnList existing=new InsnList();existing.add(new VarInsnNode(Opcodes.ALOAD,2));existing.add(new VarInsnNode(Opcodes.ALOAD,tagLocal));existing.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/Map","remove","(Ljava/lang/Object;)Ljava/lang/Object;",true));existing.add(new TypeInsnNode(Opcodes.CHECKCAST,tracker));replace.put(i,existing);skip.add(dup);skip.add(constructor);
			}
			if(i.getOpcode()==Opcodes.RETURN){InsnList end=new InsnList();end.add(new VarInsnNode(Opcodes.ALOAD,map));end.add(new InsnNode(Opcodes.ARETURN));replace.put(i,end);}
		}
		// Keep every native label at its exact instruction boundary; all native branch/switch edges retain their destinations.
		for(var i:body.instructions){if(skip.contains(i)||i instanceof FrameNode||i instanceof LineNumberNode)continue;InsnList substitution=replace.get(i);if(substitution!=null){result.instructions.add(substitution);continue;}AbstractInsnNode copied=i.clone(labels);if(copied instanceof VarInsnNode variable&&variable.var>=2)variable.var++;if(copied instanceof IincInsnNode increment&&increment.var>=2)increment.var++;result.instructions.add(copied);}
		result.maxLocals=map+1;result.maxStack=6;return result;
	}
	/** Preserve a native extension's direct tag->tracker pointer API when constructor entries move maps. */
	private static boolean directTrackerGetter(MethodNode method,String owner,String primary,String source,String tracker){
		List<AbstractInsnNode>code=opcodes(method);if(code.size()!=6||!(code.get(0)instanceof VarInsnNode self&&self.getOpcode()==Opcodes.ALOAD&&self.var==0)
				||!(code.get(1)instanceof FieldInsnNode field&&field.getOpcode()==Opcodes.GETFIELD&&field.owner.equals(owner)&&field.name.equals(primary)&&field.desc.equals(MAP))
				||!(code.get(2)instanceof VarInsnNode tag&&tag.getOpcode()==Opcodes.ALOAD&&tag.var==1)
				||!(code.get(3)instanceof MethodInsnNode get&&get.owner.equals("java/util/Map")&&get.name.equals("get")&&get.desc.equals("(Ljava/lang/Object;)Ljava/lang/Object;"))
				||!(code.get(4)instanceof TypeInsnNode cast&&cast.getOpcode()==Opcodes.CHECKCAST&&cast.desc.equals(tracker))||code.get(5).getOpcode()!=Opcodes.ARETURN)return false;
		LabelNode fallback=new LabelNode();InsnList prefix=new InsnList();prefix.add(new VarInsnNode(Opcodes.ALOAD,0));prefix.add(new FieldInsnNode(Opcodes.GETFIELD,owner,source,MAP));prefix.add(new JumpInsnNode(Opcodes.IFNULL,fallback));prefix.add(new VarInsnNode(Opcodes.ALOAD,0));prefix.add(new FieldInsnNode(Opcodes.GETFIELD,owner,source,MAP));prefix.add(new VarInsnNode(Opcodes.ALOAD,1));prefix.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/Map","containsKey","(Ljava/lang/Object;)Z",true));prefix.add(new JumpInsnNode(Opcodes.IFEQ,fallback));prefix.add(new VarInsnNode(Opcodes.ALOAD,0));prefix.add(new FieldInsnNode(Opcodes.GETFIELD,owner,source,MAP));prefix.add(new VarInsnNode(Opcodes.ALOAD,1));prefix.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/Map","get","(Ljava/lang/Object;)Ljava/lang/Object;",true));prefix.add(new TypeInsnNode(Opcodes.CHECKCAST,tracker));prefix.add(new InsnNode(Opcodes.ARETURN));prefix.add(fallback);method.instructions.insert(prefix);return true;
	}
	private static MethodNode begin(ClassNode owner,String map,String ready,String tracker,MethodNode reset,String name,String key){MethodNode method=new MethodNode(Opcodes.ACC_PRIVATE,name,"()V",null,null);LabelNode end=new LabelNode(),loop=new LabelNode();
		method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new LdcInsnNode(key));method.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"begin","(Ljava/lang/Object;Ljava/lang/String;)Z",false));method.instructions.add(new FieldInsnNode(Opcodes.PUTFIELD,owner.name,ready,"Z"));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,owner.name,map,MAP));method.instructions.add(new JumpInsnNode(Opcodes.IFNULL,end));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,owner.name,map,MAP));method.instructions.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/Map","values","()Ljava/util/Collection;",true));method.instructions.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/Collection","iterator","()Ljava/util/Iterator;",true));method.instructions.add(new VarInsnNode(Opcodes.ASTORE,1));method.instructions.add(loop);method.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));method.instructions.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/Iterator","hasNext","()Z",true));method.instructions.add(new JumpInsnNode(Opcodes.IFEQ,end));method.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));method.instructions.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/Iterator","next","()Ljava/lang/Object;",true));method.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,tracker));method.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,owner.name,reset.name,reset.desc,false));method.instructions.add(new JumpInsnNode(Opcodes.GOTO,loop));method.instructions.add(end);method.instructions.add(new InsnNode(Opcodes.RETURN));method.maxLocals=2;method.maxStack=3;return method;}
	private static boolean forwarder(MethodNode live,String owner,String tag,String type,MethodNode source,String map,String ready,String primary){
		List<AbstractInsnNode>all=opcodes(live),code=all;InsnList preserved=new InsnList();
		int start=0;for(int i=2;i<all.size();i++)if(all.get(i)instanceof MethodInsnNode call&&call.getOpcode()==Opcodes.INVOKESTATIC&&call.desc.equals("(L"+tag+";)L"+type+";")){start=i-2;break;}
		if(start>0){if(!untrackedPrefix(all.subList(0,start),all.get(start),owner,tag,primary))return false;Map<LabelNode,LabelNode>labels=labels(live.instructions);LabelNode join=new LabelNode();for(var instruction:live.instructions)if(instruction instanceof LabelNode label&&next(label)==all.get(start))labels.put(label,join);
			for(var instruction:live.instructions){if(instruction==all.get(start))break;if(instruction instanceof LabelNode label&&next(label)==all.get(start))continue;if(instruction instanceof FrameNode||instruction instanceof LineNumberNode)continue;preserved.add(instruction.clone(labels));}preserved.add(join);code=all.subList(start,all.size());}
		MethodInsnNode mapper=null,delegate=null;for(var i:code)if(i instanceof MethodInsnNode call){if(call.getOpcode()==Opcodes.INVOKESTATIC&&call.desc.equals("(L"+tag+";)L"+type+";")){if(mapper!=null)return false;mapper=call;}else if(call.getOpcode()==Opcodes.INVOKEVIRTUAL&&call.owner.equals(owner)){if(delegate!=null)return false;delegate=call;}else return false;}else if(!(i instanceof VarInsnNode)&&!(i instanceof InsnNode))return false;if(mapper==null||delegate==null)return false;
		Type[]parameters=Type.getArgumentTypes(live.desc);Type output=Type.getReturnType(live.desc);if((live.access&Opcodes.ACC_STATIC)!=0||!live.tryCatchBlocks.isEmpty()||code.size()!=parameters.length+4||!(code.get(0)instanceof VarInsnNode self&&self.getOpcode()==Opcodes.ALOAD&&self.var==0)||!(code.get(1)instanceof VarInsnNode first&&first.getOpcode()==Opcodes.ALOAD&&first.var==1)||code.get(2)!=mapper||code.getLast().getOpcode()!=output.getOpcode(Opcodes.IRETURN)||code.get(code.size()-2)!=delegate)return false;
		int expectedSlot=1+parameters[0].getSize();for(int i=1;i<parameters.length;i++){if(!(code.get(i+2)instanceof VarInsnNode load&&load.var==expectedSlot&&load.getOpcode()==parameters[i].getOpcode(Opcodes.ILOAD)))return false;expectedSlot+=parameters[i].getSize();}
		StringBuilder expectedDescriptor=new StringBuilder("(L").append(type).append(';');for(int i=1;i<parameters.length;i++)expectedDescriptor.append(parameters[i].getDescriptor());expectedDescriptor.append(')').append(output.getDescriptor());if(!delegate.desc.equals(expectedDescriptor.toString()))return false;
		MethodNode body=new MethodNode(live.access,live.name,live.desc,live.signature,live.exceptions.toArray(String[]::new));int typeLocal=1;for(Type parameter:parameters)typeLocal+=parameter.getSize();LabelNode nativeOnly=new LabelNode();
		body.instructions.add(preserved);body.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));body.instructions.add(new MethodInsnNode(mapper.getOpcode(),mapper.owner,mapper.name,mapper.desc,mapper.itf));body.instructions.add(new VarInsnNode(Opcodes.ASTORE,typeLocal));body.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));body.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,owner,map,MAP));body.instructions.add(new JumpInsnNode(Opcodes.IFNULL,nativeOnly));body.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));body.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,owner,ready,"Z"));body.instructions.add(new JumpInsnNode(Opcodes.IFEQ,nativeOnly));body.instructions.add(new VarInsnNode(Opcodes.ALOAD,typeLocal));body.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"owns","(L"+type+";)Z",false));body.instructions.add(new JumpInsnNode(Opcodes.IFEQ,nativeOnly));body.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));loadArguments(body.instructions,parameters,1);body.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,owner,source.name,source.desc,false));body.instructions.add(new InsnNode(output.getOpcode(Opcodes.IRETURN)));body.instructions.add(nativeOnly);body.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));body.instructions.add(new VarInsnNode(Opcodes.ALOAD,typeLocal));int local=1+parameters[0].getSize();for(int i=1;i<parameters.length;i++){body.instructions.add(new VarInsnNode(parameters[i].getOpcode(Opcodes.ILOAD),local));local+=parameters[i].getSize();}body.instructions.add(new MethodInsnNode(delegate.getOpcode(),delegate.owner,delegate.name,delegate.desc,delegate.itf));body.instructions.add(new InsnNode(output.getOpcode(Opcodes.IRETURN)));body.maxLocals=typeLocal+1;body.maxStack=8;live.instructions=body.instructions;live.tryCatchBlocks.clear();live.localVariables=null;live.visibleLocalVariableAnnotations=null;live.invisibleLocalVariableAnnotations=null;live.maxLocals=body.maxLocals;live.maxStack=body.maxStack;return true;
	}
	/** The existing kernel guard is preserved only with its complete, side-effect-free false/continue CFG. */
	private static boolean untrackedPrefix(List<AbstractInsnNode>p,AbstractInsnNode join,String owner,String tag,String map){
		return p.size()==10&&p.get(0)instanceof VarInsnNode a&&a.getOpcode()==Opcodes.ALOAD&&a.var==1
			&&p.get(1)instanceof MethodInsnNode test&&test.getOpcode()==Opcodes.INVOKESTATIC&&test.owner.equals("net/forbric/kernel/runtime/KernelFluidTypes")&&test.name.equals("hasTagType")&&test.desc.equals("(L"+tag+";)Z")
			&&p.get(2)instanceof JumpInsnNode known&&known.getOpcode()==Opcodes.IFNE&&next(known.label)==join
			&&p.get(3)instanceof VarInsnNode self&&self.getOpcode()==Opcodes.ALOAD&&self.var==0
			&&p.get(4)instanceof FieldInsnNode field&&field.getOpcode()==Opcodes.GETFIELD&&field.owner.equals(owner)&&field.name.equals(map)&&field.desc.equals(MAP)
			&&p.get(5)instanceof VarInsnNode key&&key.getOpcode()==Opcodes.ALOAD&&key.var==1
			&&p.get(6)instanceof MethodInsnNode contains&&contains.getOpcode()==Opcodes.INVOKEINTERFACE&&contains.owner.equals("java/util/Map")&&contains.name.equals("containsKey")&&contains.desc.equals("(Ljava/lang/Object;)Z")
			&&p.get(7)instanceof JumpInsnNode found&&found.getOpcode()==Opcodes.IFNE&&next(found.label)==join
			&&p.get(8).getOpcode()==Opcodes.ICONST_0&&p.get(9).getOpcode()==Opcodes.IRETURN;
	}
	private static void instrument(ClassNode owner,NativeTagMetricTemplate.Template template,MethodNode lookup,MethodNode begin,String ready,String key){
		MethodNode update=template.current();int fluid=update.maxLocals++,raw=update.maxLocals++,tagTracker=update.maxLocals++;
		InsnList enter=new InsnList();enter.add(new VarInsnNode(Opcodes.ALOAD,0));enter.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,owner.name,begin.name,begin.desc,false));for(int local:new int[]{fluid,raw,tagTracker}){enter.add(new InsnNode(Opcodes.ACONST_NULL));enter.add(new VarInsnNode(Opcodes.ASTORE,local));}
		// Empty/below-surface cells join the common loop continuation before geometry locals are assigned.
		// Define their otherwise-dead slots so the null-tracker metric call remains verifier-safe at that join.
		for(var input:template.inputs())if(input.type().getSort()!=Type.OBJECT){enter.add(new InsnNode(input.type().equals(Type.DOUBLE_TYPE)?Opcodes.DCONST_0:input.type().equals(Type.FLOAT_TYPE)?Opcodes.FCONST_0:input.type().equals(Type.LONG_TYPE)?Opcodes.LCONST_0:Opcodes.ICONST_0));enter.add(new VarInsnNode(input.type().getOpcode(Opcodes.ISTORE),input.currentSlot()));}update.instructions.insert(enter);
		InsnList cell=new InsnList();for(int local:new int[]{fluid,raw,tagTracker}){cell.add(new InsnNode(Opcodes.ACONST_NULL));cell.add(new VarInsnNode(Opcodes.ASTORE,local));}update.instructions.insertBefore(template.cellStart(),cell);
		InsnList captureFluid=new InsnList();captureFluid.add(new InsnNode(Opcodes.DUP));captureFluid.add(new VarInsnNode(Opcodes.ASTORE,fluid));update.instructions.insert(template.fluidGetter(),captureFluid);InsnList captureFlow=new InsnList();captureFlow.add(new InsnNode(Opcodes.DUP));captureFlow.add(new VarInsnNode(Opcodes.ASTORE,raw));update.instructions.insert(template.flowGetter(),captureFlow);
		// Reuse the current type value directly after its store; no additional type or world getter.
		AbstractInsnNode stored=next(template.typeGetter());if(!(stored instanceof VarInsnNode typeStore&&typeStore.getOpcode()==Opcodes.ASTORE))throw new IllegalArgumentException();LabelNode skip=new LabelNode();InsnList select=new InsnList();select.add(new VarInsnNode(Opcodes.ALOAD,0));select.add(new FieldInsnNode(Opcodes.GETFIELD,owner.name,ready,"Z"));select.add(new JumpInsnNode(Opcodes.IFEQ,skip));select.add(new VarInsnNode(Opcodes.ALOAD,0));select.add(new VarInsnNode(Opcodes.ALOAD,fluid));select.add(new VarInsnNode(Opcodes.ALOAD,typeStore.var));select.add(new LdcInsnNode(key));select.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"sample","(Ljava/lang/Object;Ljava/lang/Object;L"+TYPE+";Ljava/lang/String;)Z",false));select.add(new JumpInsnNode(Opcodes.IFEQ,skip));select.add(new VarInsnNode(Opcodes.ALOAD,0));select.add(new VarInsnNode(Opcodes.ALOAD,fluid));select.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,owner.name,lookup.name,lookup.desc,false));select.add(new VarInsnNode(Opcodes.ASTORE,tagTracker));select.add(skip);update.instructions.insert(stored,select);
		LabelNode noMetric=new LabelNode();InsnList sample=new InsnList();sample.add(new VarInsnNode(Opcodes.ALOAD,tagTracker));sample.add(new JumpInsnNode(Opcodes.IFNULL,noMetric));sample.add(new VarInsnNode(Opcodes.ALOAD,0));sample.add(new VarInsnNode(Opcodes.ALOAD,raw));sample.add(new LdcInsnNode(key));sample.add(new MethodInsnNode(Opcodes.INVOKESTATIC,RUNTIME,"vector","(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)Z",false));sample.add(new JumpInsnNode(Opcodes.IFEQ,noMetric));for(var input:template.inputs())sample.add(new VarInsnNode(input.type().getOpcode(Opcodes.ILOAD),input.type().getSort()==Type.OBJECT?tagTracker:input.currentSlot()));sample.add(new VarInsnNode(Opcodes.ALOAD,raw));sample.add(new MethodInsnNode(Opcodes.INVOKESTATIC,owner.name,template.metric().name,template.metric().desc,false));sample.add(noMetric);update.instructions.insertBefore(template.cellEnd(),sample);
		for(var i:new ArrayList<>(Arrays.asList(update.instructions.toArray())))if(i instanceof FrameNode)update.instructions.remove(i);
	}
	private static MethodNode copy(MethodNode source,String name,int access,String owner,String oldMap,String newMap,Map<String,String>methods){MethodNode copy=new MethodNode(access,name,source.desc,null,source.exceptions.toArray(String[]::new));Map<LabelNode,LabelNode>labels=labels(source.instructions);for(var i:source.instructions){if(i instanceof FrameNode||i instanceof LineNumberNode)continue;var n=i.clone(labels);if(n instanceof FieldInsnNode f&&f.owner.equals(owner)&&f.name.equals(oldMap)&&f.desc.equals(MAP))f.name=newMap;if(n instanceof MethodInsnNode call&&call.owner.equals(owner)&&methods.containsKey(call.name+call.desc)){call.name=methods.get(call.name+call.desc);call.setOpcode(Opcodes.INVOKESPECIAL);}copy.instructions.add(n);}copy.maxLocals=source.maxLocals;copy.maxStack=source.maxStack;return copy;}
	private static MethodNode staticCopy(MethodNode source,String name,String receiver){MethodNode copy=copy(source,name,Opcodes.ACC_PRIVATE|Opcodes.ACC_STATIC,"","","",Map.of());copy.desc="(L"+receiver+";"+source.desc.substring(1);return copy;}
	private static MethodNode method(ClassNode owner,String name,String desc){return owner.methods.stream().filter(m->m.name.equals(name)&&m.desc.equals(desc)).findFirst().orElse(null);}
	private static MethodContract contract(String owner,MethodNode method){return new MethodContract(owner,method.name,method.desc,DefinedMethodContracts.fingerprint(method));}
	private static Map<LabelNode,LabelNode>labels(InsnList instructions){Map<LabelNode,LabelNode>labels=new IdentityHashMap<>();for(var i:instructions)if(i instanceof LabelNode label)labels.put(label,new LabelNode());return labels;}
	private static List<AbstractInsnNode>opcodes(MethodNode method){List<AbstractInsnNode>result=new ArrayList<>();for(var i:method.instructions)if(i.getOpcode()>=0)result.add(i);return result;}
	private static void loadArguments(InsnList instructions,Type[]arguments,int slot){for(Type argument:arguments){instructions.add(new VarInsnNode(argument.getOpcode(Opcodes.ILOAD),slot));slot+=argument.getSize();}}
	private static AbstractInsnNode previous(AbstractInsnNode i){for(var n=i.getPrevious();n!=null;n=n.getPrevious())if(n.getOpcode()>=0)return n;return null;}private static AbstractInsnNode next(AbstractInsnNode i){for(var n=i.getNext();n!=null;n=n.getNext())if(n.getOpcode()>=0)return n;return null;}
	private static boolean mentions(byte[]bytes,String value){byte[]needle=value.getBytes(java.nio.charset.StandardCharsets.UTF_8);outer:for(int i=0;i<=bytes.length-needle.length;i++){for(int j=0;j<needle.length;j++)if(bytes[i+j]!=needle[j])continue outer;return true;}return false;}
	private static ClassNode parse(byte[]bytes){ClassNode node=new ClassNode();new ClassReader(bytes).accept(node,ClassReader.EXPAND_FRAMES);return node;}
	private static final class Frames extends ClassWriter{
		final ClassNode owner;final Function<String,ClassNode>classes;Frames(ClassNode owner,Function<String,ClassNode>classes){super(COMPUTE_FRAMES|COMPUTE_MAXS);this.owner=owner;this.classes=classes;}
		@Override protected String getCommonSuperClass(String a,String b){if(a.equals(b))return a;if(assignable(a,b,new HashSet<>()))return a;if(assignable(b,a,new HashSet<>()))return b;ClassNode node=read(a);while(node!=null&&node.superName!=null){if(assignable(node.superName,b,new HashSet<>()))return node.superName;node=read(node.superName);}return"java/lang/Object";}
		boolean assignable(String target,String value,Set<String>seen){if(target.equals(value)||target.equals("java/lang/Object"))return true;if(!seen.add(value))return false;ClassNode node=read(value);if(node==null)return false;if(node.superName!=null&&assignable(target,node.superName,seen))return true;for(String iface:node.interfaces)if(assignable(target,iface,seen))return true;return false;}
		ClassNode read(String name){if(name.equals(owner.name))return owner;ClassNode node=classes.apply(name);if(node!=null)return node;try(var in=NativeTagTrackerSourceInjector.class.getClassLoader().getResourceAsStream(name+".class")){return in==null?null:parse(in.readAllBytes());}catch(java.io.IOException unknown){return null;}}
	}
}
