/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.tools;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import java.util.zip.ZipOutputStream;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.*;

/**
 * The leading-hook-block grammar on synthetic three-way inputs: one made-up game class whose
 * {@code describe(int)} each family patched. The base family only routes the method's last call through a member
 * it added; the other family does the same with its own member AND inserts one hook block after a shared vanilla
 * preamble. The composed body is written the way the builder writes it (COMPUTE_MAXS, frames as merged) and run,
 * so the JVM's verifier checks the frame the composition adds after the block's exit, on top of the base's own
 * frames, including a two-slot local.
 */
public class LeadingHookBlockTest {
	private static final String OWNER = "net/minecraft/LeadingHookProbe";
	private static final String NEO = AdditiveMethodMergerTest.NEO, FORGE = AdditiveMethodMergerTest.FORGE;
	private static final String DESCRIBE = "(I)Ljava/lang/String;", JOIN = "(Ljava/lang/String;J)Ljava/lang/String;";
	private static final String RECORDER = LeadingHookBlockTest.class.getName().replace('.', '/');
	private static final String PROBE_EVENT = "net/minecraftforge/event/ProbeAnswerEvent";
	/** The preamble every fixture shares: {@code long wide = value * 3L; String text = String.valueOf(value);}. */
	private static final int PREAMBLE = 8;

	static final List<String> OBSERVED = new ArrayList<>();
	static String answer;
	static boolean allow = true;

	@AfterEach
	void reset() {
		OBSERVED.clear();
		answer = null;
		allow = true;
	}

	// ---- the probe families' hooks and the class's own members, called from generated bytecode ----

	public static String answer(String text, long wide) { OBSERVED.add("other:answer " + text + " " + wide); return answer; }
	public static boolean allow(String text) { OBSERVED.add("other:allow " + text); return allow; }
	public static boolean allowValue(int value) { OBSERVED.add("other:allowValue " + value); return allow; }
	public static void notice(String text, long wide) { OBSERVED.add("other:notice " + text + " " + wide); }
	public static String routed(String text, long wide) { OBSERVED.add("base:routed " + text + " " + wide); return "base:" + text; }
	public static String otherRouted(String text, long wide) { OBSERVED.add("other:routed " + text + " " + wide); return "other:" + text; }
	public static String vanillaJoin(String text, long wide) { OBSERVED.add("vanilla " + text); return "vanilla:" + text; }

	@Test
	void anAnswerBlockReturnsTheOtherFamilysAnswerOrRunsTheBasesRoutedBody() throws Exception {
		MethodNode vanilla = vanilla("vanillaJoin"), base = vanilla("routed"), other = withBlock(vanilla("otherRouted"), answerBlock(5));
		byte[] beforeBase = holder(base), beforeOther = holder(other);
		AdditiveMethodMerger.Result result = merge(vanilla, base, other, UNCOMPENSATED);
		assertTrue(result.accepted(), result.reason());
		assertEquals("leading hook block after a shared vanilla preamble of 8 instruction(s), answer: restored "
				+ FORGE + ".answer" + JOIN, result.reason());
		assertArrayEquals(beforeBase, holder(base), "the base input is not mutated");
		assertArrayEquals(beforeOther, holder(other), "the other input is not mutated");
		// The answer passes through a local no base instruction uses.
		int answerSlot = executable(result.method()).stream().filter(i -> i.getOpcode() == Opcodes.ASTORE)
				.mapToInt(i -> ((VarInsnNode) i).var).max().orElseThrow();
		assertTrue(answerSlot >= base.maxLocals, "answer local " + answerSlot + " collides with the base's locals");
		// The other family's own routing stays lost, exactly as before the composition.
		assertFalse(calls(result.method()).contains(OWNER + ".otherRouted"));

		Object example = instance(result.method());
		assertEquals("base:7", describe(example, 7));
		assertEquals(List.of("other:answer 7 21", "base:routed 7 21"), OBSERVED);
		OBSERVED.clear();
		answer = "vetoed";
		assertEquals("vetoed", describe(example, 7));
		assertEquals(List.of("other:answer 7 21"), OBSERVED, "an answer from the other family returns before the base body");
	}

	@Test
	void aVetoBlockSkipsTheBaseBodyOnlyWhenTheOtherFamilyRefuses() throws Exception {
		MethodNode vanilla = vanilla("vanillaJoin");
		AdditiveMethodMerger.Result result = merge(vanilla, vanilla("routed"), withBlock(vanilla("otherRouted"), vetoBlock()), UNCOMPENSATED);
		assertTrue(result.accepted(), result.reason());
		assertTrue(result.reason().contains(", veto: restored " + FORGE + ".allow"), result.reason());
		Object example = instance(result.method());
		assertEquals("base:4", describe(example, 4));
		assertEquals(List.of("other:allow 4", "base:routed 4 12"), OBSERVED);
		OBSERVED.clear();
		allow = false;
		assertEquals("refused", describe(example, 4));
		assertEquals(List.of("other:allow 4"), OBSERVED);
	}

	@Test
	void anObserverBlockRunsAndTheBaseBodyContinues() throws Exception {
		MethodNode vanilla = vanilla("vanillaJoin");
		AdditiveMethodMerger.Result result = merge(vanilla, vanilla("routed"), withBlock(vanilla("otherRouted"), observerBlock()), UNCOMPENSATED);
		assertTrue(result.accepted(), result.reason());
		assertEquals("base:2", describe(instance(result.method()), 2));
		assertEquals(List.of("other:notice 2 6", "base:routed 2 6"), OBSERVED);
	}

	@Test
	void aBlockAtTheEntryNeedsNoPreambleAndStillRunsOnTheBasesFrames() throws Exception {
		MethodNode vanilla = vanilla("vanillaJoin");
		MethodNode other = vanilla("otherRouted");
		InsnList block = new InsnList();
		LabelNode resume = new LabelNode();
		block.add(new VarInsnNode(Opcodes.ILOAD, 1));
		block.add(new MethodInsnNode(Opcodes.INVOKESTATIC, FORGE, "allowValue", "(I)Z", false));
		block.add(new JumpInsnNode(Opcodes.IFNE, resume));
		block.add(new LdcInsnNode("refused at entry"));
		block.add(new InsnNode(Opcodes.ARETURN));
		block.add(resume);
		other.instructions.insert(block);
		AdditiveMethodMerger.Result result = merge(vanilla, vanilla("routed"), framed(other), UNCOMPENSATED);
		assertTrue(result.accepted(), result.reason());
		assertTrue(result.reason().startsWith("leading hook block after a shared vanilla preamble of 0 instruction(s), veto"), result.reason());
		Object example = instance(result.method());
		assertEquals("base:3", describe(example, 3));
		assertEquals(List.of("other:allowValue 3", "base:routed 3 9"), OBSERVED);
		OBSERVED.clear();
		allow = false;
		assertEquals("refused at entry", describe(example, 3));
		assertEquals(List.of("other:allowValue 3"), OBSERVED);
	}

	@Test
	void aLookAlikeCallOutsideTheOtherFamilyIsNotAHookBlock() {
		// The same block, calling a class that belongs to neither family: not a hook, so not this grammar.
		InsnList block = answerBlock(5);
		for (AbstractInsnNode instruction : block) if (instruction instanceof MethodInsnNode call) call.owner = "org/example/Probe";
		AdditiveMethodMerger.Result result = merge(vanilla("vanillaJoin"), vanilla("routed"), withBlock(vanilla("otherRouted"), block), UNCOMPENSATED);
		assertFalse(result.accepted(), result.reason());
		assertFalse(result.reason().startsWith("leading"), result.reason());
	}

	@Test
	void aBaseThatPostsSomethingOfItsOwnFamilyHereIsNotThisShape() {
		// Its own hook could be the counterpart of the other's; no order between them is decided by this grammar.
		MethodNode base = vanilla("routed");
		InsnList own = new InsnList();
		own.add(new VarInsnNode(Opcodes.ALOAD, 4));
		own.add(new VarInsnNode(Opcodes.LLOAD, 2));
		own.add(new MethodInsnNode(Opcodes.INVOKESTATIC, NEO, "notice", "(Ljava/lang/String;J)V", false));
		base.instructions.insert(executable(base).get(PREAMBLE + 2), own);
		AdditiveMethodMerger.Result result = merge(vanilla("vanillaJoin"), framed(base), withBlock(vanilla("otherRouted"), answerBlock(5)),
				UNCOMPENSATED);
		assertFalse(result.accepted(), result.reason());
		assertFalse(result.reason().startsWith("leading"), result.reason());
	}

	@Test
	void aBaseThatPostsItsOwnHookAtTheSameAnchorIsNotThisShapeEither() {
		// Both families hook right after the shared preamble, so no stage difference refuses it first: only the rule that
		// the base posts nothing of its own here keeps a renamed counterpart of the other's event from firing twice.
		MethodNode base = vanilla("routed");
		InsnList own = new InsnList();
		own.add(new VarInsnNode(Opcodes.ALOAD, 4));
		own.add(new VarInsnNode(Opcodes.LLOAD, 2));
		own.add(new MethodInsnNode(Opcodes.INVOKESTATIC, NEO, "notice", "(Ljava/lang/String;J)V", false));
		base.instructions.insert(executable(base).get(PREAMBLE - 1), own);
		AdditiveMethodMerger.Result result = merge(vanilla("vanillaJoin"), framed(base), withBlock(vanilla("otherRouted"), answerBlock(5)),
				UNCOMPENSATED);
		assertFalse(result.accepted(), result.reason());
		assertFalse(result.reason().startsWith("leading"), result.reason());
	}

	@Test
	void anArgumentComputedInsideTheBlockIsNotAPlainOperand() {
		InsnList block = answerBlock(5);
		block.insert(block.getFirst(), new MethodInsnNode(Opcodes.INVOKEVIRTUAL, "java/lang/String", "trim", "()Ljava/lang/String;", false));
		AdditiveMethodMerger.Result result = merge(vanilla("vanillaJoin"), vanilla("routed"), withBlock(vanilla("otherRouted"), block), UNCOMPENSATED);
		assertFalse(result.accepted(), result.reason());
		assertFalse(result.reason().startsWith("leading"), result.reason());
	}

	@Test
	void structuralViolationsAreRefusedWithTheirReason() {
		record Case(String reason, Consumer<MethodNode> base, Consumer<MethodNode> other) { }
		for (Case c : List.of(
				new Case("replaces vanilla code instead of preceding it", m -> { }, m -> {
					// Right after the block's continuation label: the other body no longer resumes at vanilla code.
					InsnList extra = new InsnList();
					extra.add(new InsnNode(Opcodes.ICONST_0));
					extra.add(new InsnNode(Opcodes.POP));
					m.instructions.insertBefore(executable(m).get(PREAMBLE + 8), extra);
				}),
				new Case("changes more of this method than", m -> { }, m -> {
					InsnList second = new InsnList();
					second.add(new VarInsnNode(Opcodes.ALOAD, 4));
					second.add(new VarInsnNode(Opcodes.LLOAD, 2));
					second.add(new MethodInsnNode(Opcodes.INVOKESTATIC, FORGE, "notice", "(Ljava/lang/String;J)V", false));
					m.instructions.insertBefore(executable(m).get(executable(m).size() - 5), second);
				}),
				new Case("a branch other than its own guard enters or ends", m -> { }, m -> {
					// A later check that jumps back to the block's continuation.
					LabelNode resume = ((JumpInsnNode) executable(m).get(PREAMBLE + 5)).label;
					InsnList loop = new InsnList();
					loop.add(new VarInsnNode(Opcodes.ILOAD, 1));
					loop.add(new JumpInsnNode(Opcodes.IFLT, resume));
					m.instructions.insertBefore(executable(m).get(executable(m).size() - 5), loop);
				}),
				new Case("uses the local", m -> { }, m -> {
					InsnList reuse = new InsnList();
					reuse.add(new InsnNode(Opcodes.ACONST_NULL));
					reuse.add(new VarInsnNode(Opcodes.ASTORE, 5));
					m.instructions.insertBefore(executable(m).get(executable(m).size() - 5), reuse);
				}),
				new Case("a handler covers the shared preamble", m -> {
					LabelNode start = new LabelNode(), end = new LabelNode(), handler = new LabelNode();
					m.instructions.insert(start);
					m.instructions.insert(executable(m).get(2), end);
					m.instructions.add(handler);
					m.instructions.add(new InsnNode(Opcodes.ATHROW));
					m.tryCatchBlocks.add(new TryCatchBlockNode(start, end, handler, null));
				}, m -> { }),
				new Case("a handler covers or enters", m -> { }, m -> {
					LabelNode start = new LabelNode(), end = new LabelNode(), handler = new LabelNode();
					m.instructions.insertBefore(executable(m).get(PREAMBLE), start);
					m.instructions.insert(executable(m).get(PREAMBLE + 2), end);
					m.instructions.add(handler);
					m.instructions.add(new InsnNode(Opcodes.ATHROW));
					m.tryCatchBlocks.add(new TryCatchBlockNode(start, end, handler, null));
				}))) {
			MethodNode base = vanilla("routed"), other = withBlockUnframed(vanilla("otherRouted"), answerBlock(5));
			c.base().accept(base);
			c.other().accept(other);
			AdditiveMethodMerger.Result result = merge(vanilla("vanillaJoin"), framed(base), framed(other), UNCOMPENSATED);
			assertFalse(result.accepted(), c.reason() + " / " + result.reason());
			assertTrue(result.reason().startsWith("leading hook block not composable: ") && result.reason().contains(c.reason()),
					c.reason() + " / " + result.reason());
		}
	}

	@Test
	void restoringNeedsAKnownUncompensatedEventOrAReview() {
		MethodNode vanilla = vanilla("vanillaJoin"), base = vanilla("routed"), other = withBlock(vanilla("otherRouted"), answerBlock(5));
		String hook = FORGE + ".answer" + JOIN;
		AdditiveMethodMerger.Result counterpart = merge(vanilla, base, other, context(true, false, Set.of(PROBE_EVENT), true));
		assertFalse(counterpart.accepted());
		assertEquals("leading hook block composes, but the base family declares a counterpart of " + PROBE_EVENT
				+ " the runtime may already forward: restoring " + hook, counterpart.reason());
		AdditiveMethodMerger.Result unread = merge(vanilla, base, other, context(true, false, null, false));
		assertFalse(unread.accepted());
		assertTrue(unread.reason().contains("what " + hook + " posts cannot be read"), unread.reason());
		AdditiveMethodMerger.Result silent = merge(vanilla, base, other, context(true, false, Set.of(), false));
		assertFalse(silent.accepted(), "a hook that constructs no event could be compensated by anything");
		AdditiveMethodMerger.Result reviewed = merge(vanilla, base, other, context(true, true, null, true));
		assertTrue(reviewed.accepted(), "a reviewed restoration needs no event reading: " + reviewed.reason());
		AdditiveMethodMerger.Result unlinked = merge(vanilla, base, other, context(false, false, Set.of(PROBE_EVENT), false));
		assertEquals("leading hook does not resolve: " + hook, unlinked.reason());
	}

	@Test
	void anInstanceMethodWithoutItsOwnerCannotBeGivenAFrame() {
		AdditiveMethodMerger.Result result = AdditiveMethodMerger.merge(vanilla("vanillaJoin"), vanilla("routed"),
				withBlock(vanilla("otherRouted"), answerBlock(5)), "net/neoforged/", "net/minecraftforge/", UNCOMPENSATED);
		assertFalse(result.accepted());
		assertTrue(result.reason().contains("the owner class is unknown"), result.reason());
	}

	@Test
	void theBuilderPassesTheOwnerRestoresTheBlockAndItsOutputVerifiesAndRuns(@TempDir Path directory) throws Exception {
		// Single-class game jars, real runtime jars: what the builder decides from what the families' jars contain,
		// with the production context reading the hook's event and finding no NeoForge-side counterpart for it.
		Path vanilla = jar(directory, "vanilla.jar", Map.of(OWNER, gameClass(vanilla("vanillaJoin"), "vanillaJoin")));
		Path neo = jar(directory, "neo.jar", Map.of(OWNER, gameClass(vanilla("routed"), "vanillaJoin", "routed")));
		Path forge = jar(directory, "forge.jar", Map.of(OWNER,
				gameClass(withBlock(vanilla("otherRouted"), answerBlock(5)), "vanillaJoin", "otherRouted")));
		Path forgeRuntime = jar(directory, "forge-runtime.jar", Map.of(FORGE, probes(), PROBE_EVENT, event()));
		Path neoRuntime = jar(directory, "neo-runtime.jar", Map.of(NEO, AdditiveMethodMergerTest.hookClass(NEO)));
		Path merged = directory.resolve("merged.jar"), report = directory.resolve("report.txt");
		new MergedBaseBuilder(Set.of()).run(vanilla, forge, neo, merged, report, forgeRuntime, neoRuntime);
		String text = Files.readString(report);
		assertTrue(text.contains(OWNER + "#describe" + DESCRIBE + " ACCEPTED leading hook block after a shared vanilla preamble"), text);
		assertFalse(text.contains("(forge hook lost)"), text);
		byte[] bytes;
		try (ZipFile zip = new ZipFile(merged.toFile())) {
			bytes = zip.getInputStream(zip.getEntry(OWNER + ".class")).readAllBytes();
		}
		Object game = instance(bytes);
		assertEquals("base:7", describe(game, 7));
		assertEquals(List.of("other:answer 7 21", "base:routed 7 21"), OBSERVED);
		OBSERVED.clear();
		answer = "vetoed";
		assertEquals("vetoed", describe(game, 7));
		assertEquals(List.of("other:answer 7 21"), OBSERVED);
	}

	private static Path jar(Path directory, String name, Map<String, byte[]> classes) throws Exception {
		Path path = directory.resolve(name);
		try (ZipOutputStream zip = new ZipOutputStream(Files.newOutputStream(path))) {
			for (Map.Entry<String, byte[]> entry : classes.entrySet()) {
				zip.putNextEntry(new ZipEntry(entry.getKey() + ".class"));
				zip.write(entry.getValue());
				zip.closeEntry();
			}
		}
		return path;
	}

	@Test
	void theProductionContextReadsEventsFromTheHookAndMatchesCounterpartsByNestedName() {
		MethodNode hook = new MethodNode(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC, "answer", JOIN, null, null);
		hook.instructions.add(new TypeInsnNode(Opcodes.NEW, PROBE_EVENT));
		hook.instructions.add(new InsnNode(Opcodes.POP));
		hook.instructions.add(new TypeInsnNode(Opcodes.NEW, "java/lang/Object"));
		hook.instructions.add(new InsnNode(Opcodes.POP));
		hook.instructions.add(new InsnNode(Opcodes.ACONST_NULL));
		hook.instructions.add(new InsnNode(Opcodes.ARETURN));
		ClassNode hooks = new ClassNode();
		hooks.visit(Opcodes.V17, Opcodes.ACC_PUBLIC, FORGE, null, "java/lang/Object", null);
		hooks.methods.add(hook);
		ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
		hooks.accept(writer);
		Map<String, byte[]> forgeRuntime = Map.of(FORGE, writer.toByteArray());
		Map<String, byte[]> neoRuntime = Map.of("net/neoforged/neoforge/event/tick/ServerTickEvent$Pre", new byte[0],
				"net/neoforged/neoforge/event/Unrelated", new byte[0]);
		AdditiveMethodMerger.Context production = AdditiveMethodMerger.context(List.of(forgeRuntime, neoRuntime), Set.of());

		MethodInsnNode call = new MethodInsnNode(Opcodes.INVOKESTATIC, FORGE, "answer", JOIN, false);
		assertEquals(Set.of(PROBE_EVENT), production.constructedEvents(call), "only the family's event classes count");
		assertNull(production.constructedEvents(new MethodInsnNode(Opcodes.INVOKESTATIC, FORGE, "absent", "()V", false)));
		assertFalse(production.declaresCounterpart("net/neoforged/", PROBE_EVENT));
		assertTrue(production.declaresCounterpart("net/neoforged/", "net/minecraftforge/event/TickEvent$ServerTickEvent$Pre"),
				"the same event nested under a different outer class is a counterpart");
		assertFalse(production.declaresCounterpart("net/neoforged/", "net/minecraftforge/event/TickEvent$ServerTickEvent$Post"));
		assertFalse(production.declaresCounterpart("net/minecraftforge/", "net/minecraftforge/event/TickEvent$ServerTickEvent$Pre"),
				"a family is asked about its own declarations only");
	}

	// ---- fixtures ----

	static final AdditiveMethodMerger.Context UNCOMPENSATED = context(true, false, Set.of(PROBE_EVENT), false);

	static AdditiveMethodMerger.Context context(boolean resolves, boolean reviewed, Set<String> events, boolean counterpart) {
		return new AdditiveMethodMerger.Context() {
			@Override public boolean resolvesStatic(String owner, String name, String descriptor) {
				return resolves && (owner.equals(NEO) || owner.equals(FORGE));
			}

			@Override public boolean reviewed(MethodInsnNode alongside, MethodInsnNode restored) { return reviewed; }

			@Override public Set<String> constructedEvents(MethodInsnNode restored) { return events; }

			@Override public boolean declaresCounterpart(String familyPackage, String event) { return counterpart; }
		};
	}

	private static AdditiveMethodMerger.Result merge(MethodNode vanilla, MethodNode base, MethodNode other,
			AdditiveMethodMerger.Context context) {
		return AdditiveMethodMerger.merge(OWNER, vanilla, base, other, "net/neoforged/", "net/minecraftforge/", context);
	}

	/**
	 * {@code String describe(int value)}: {@code long wide = value * 3L; String text = String.valueOf(value);
	 * if (text.isEmpty()) return "empty"; return this.<join>(text, wide);} -- with the frames javac would emit.
	 */
	static MethodNode vanilla(String join) {
		return framed(unframed(join));
	}

	private static MethodNode unframed(String join) {
		MethodNode method = new MethodNode(Opcodes.ASM9, Opcodes.ACC_PUBLIC, "describe", DESCRIBE, null, null);
		InsnList code = method.instructions;
		code.add(new VarInsnNode(Opcodes.ILOAD, 1));
		code.add(new InsnNode(Opcodes.I2L));
		code.add(new LdcInsnNode(3L));
		code.add(new InsnNode(Opcodes.LMUL));
		code.add(new VarInsnNode(Opcodes.LSTORE, 2));
		code.add(new VarInsnNode(Opcodes.ILOAD, 1));
		code.add(new MethodInsnNode(Opcodes.INVOKESTATIC, "java/lang/String", "valueOf", "(I)Ljava/lang/String;", false));
		code.add(new VarInsnNode(Opcodes.ASTORE, 4));
		LabelNode go = new LabelNode();
		code.add(new VarInsnNode(Opcodes.ALOAD, 4));
		code.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL, "java/lang/String", "isEmpty", "()Z", false));
		code.add(new JumpInsnNode(Opcodes.IFEQ, go));
		code.add(new LdcInsnNode("empty"));
		code.add(new InsnNode(Opcodes.ARETURN));
		code.add(go);
		code.add(new VarInsnNode(Opcodes.ALOAD, 0));
		code.add(new VarInsnNode(Opcodes.ALOAD, 4));
		code.add(new VarInsnNode(Opcodes.LLOAD, 2));
		code.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL, OWNER, join, JOIN, false));
		code.add(new InsnNode(Opcodes.ARETURN));
		return method;
	}

	/** {@code String answer = Probe.answer(text, wide); if (answer != null) return answer;} through {@code slot}. */
	static InsnList answerBlock(int slot) {
		InsnList block = new InsnList();
		LabelNode resume = new LabelNode();
		block.add(new VarInsnNode(Opcodes.ALOAD, 4));
		block.add(new VarInsnNode(Opcodes.LLOAD, 2));
		block.add(new MethodInsnNode(Opcodes.INVOKESTATIC, FORGE, "answer", JOIN, false));
		block.add(new VarInsnNode(Opcodes.ASTORE, slot));
		block.add(new VarInsnNode(Opcodes.ALOAD, slot));
		block.add(new JumpInsnNode(Opcodes.IFNULL, resume));
		block.add(new VarInsnNode(Opcodes.ALOAD, slot));
		block.add(new InsnNode(Opcodes.ARETURN));
		block.add(resume);
		return block;
	}

	/** {@code if (!Probe.allow(text)) return "refused";} */
	static InsnList vetoBlock() {
		InsnList block = new InsnList();
		LabelNode resume = new LabelNode();
		block.add(new VarInsnNode(Opcodes.ALOAD, 4));
		block.add(new MethodInsnNode(Opcodes.INVOKESTATIC, FORGE, "allow", "(Ljava/lang/String;)Z", false));
		block.add(new JumpInsnNode(Opcodes.IFNE, resume));
		block.add(new LdcInsnNode("refused"));
		block.add(new InsnNode(Opcodes.ARETURN));
		block.add(resume);
		return block;
	}

	/** {@code Probe.notice(text, wide);} */
	static InsnList observerBlock() {
		InsnList block = new InsnList();
		block.add(new VarInsnNode(Opcodes.ALOAD, 4));
		block.add(new VarInsnNode(Opcodes.LLOAD, 2));
		block.add(new MethodInsnNode(Opcodes.INVOKESTATIC, FORGE, "notice", "(Ljava/lang/String;J)V", false));
		return block;
	}

	private static MethodNode withBlock(MethodNode method, InsnList block) {
		return framed(withBlockUnframed(method, block));
	}

	/** The block right after the preamble, in a copy without frames so a case can change it before framing. */
	private static MethodNode withBlockUnframed(MethodNode method, InsnList block) {
		MethodNode copy = unframedCopy(method);
		copy.instructions.insert(executable(copy).get(PREAMBLE - 1), block);
		return copy;
	}

	private static MethodNode unframedCopy(MethodNode method) {
		MethodNode copy = new MethodNode(Opcodes.ASM9, method.access, method.name, method.desc, method.signature, null);
		method.accept(copy);
		for (AbstractInsnNode instruction : copy.instructions.toArray()) if (instruction instanceof FrameNode) copy.instructions.remove(instruction);
		return copy;
	}

	/** The method as a compiler would emit it: real compressed frames, read back from a class file. */
	static MethodNode framed(MethodNode method) {
		ClassNode holder = new ClassNode();
		holder.visit(Opcodes.V17, Opcodes.ACC_PUBLIC, OWNER, null, "java/lang/Object", null);
		holder.methods.add(unframedCopy(method));
		ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
		holder.accept(writer);
		ClassNode read = new ClassNode();
		new ClassReader(writer.toByteArray()).accept(read, 0);
		return read.methods.get(0);
	}

	private static byte[] holder(MethodNode method) {
		ClassNode holder = new ClassNode();
		holder.visit(Opcodes.V17, Opcodes.ACC_PUBLIC, OWNER, null, "java/lang/Object", null);
		MethodNode copy = new MethodNode(Opcodes.ASM9, method.access, method.name, method.desc, method.signature, null);
		method.accept(copy);
		holder.methods.add(copy);
		ClassWriter writer = new ClassWriter(0);
		holder.accept(writer);
		return writer.toByteArray();
	}

	/** Defines the game class with the composed method, written as the builder writes it, and makes one. */
	private static Object instance(MethodNode composed) throws Exception {
		return instance(gameClass(composed, "vanillaJoin", "routed", "otherRouted"));
	}

	private static Object instance(byte[] gameClass) throws Exception {
		Loader loader = new Loader();
		loader.define(PROBE_EVENT, event());
		loader.define(FORGE, probes());
		return loader.define(OWNER, gameClass).getConstructor().newInstance();
	}

	/**
	 * The game class: a constructor, {@code describe} and the named members, each forwarding to this test's recorder.
	 * Written with COMPUTE_MAXS only, like MergedBaseBuilder: the frames are the method's own, and the verifier
	 * judges them.
	 */
	private static byte[] gameClass(MethodNode describe, String... members) {
		ClassNode game = new ClassNode();
		game.visit(Opcodes.V17, Opcodes.ACC_PUBLIC, OWNER, null, "java/lang/Object", null);
		game.methods.add(constructor());
		game.methods.add(describe);
		for (String member : members) {
			MethodNode delegate = new MethodNode(Opcodes.ACC_PUBLIC, member, JOIN, null, null);
			delegate.instructions.add(new VarInsnNode(Opcodes.ALOAD, 1));
			delegate.instructions.add(new VarInsnNode(Opcodes.LLOAD, 2));
			delegate.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC, RECORDER, member, JOIN, false));
			delegate.instructions.add(new InsnNode(Opcodes.ARETURN));
			game.methods.add(delegate);
		}
		ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
		game.accept(writer);
		return writer.toByteArray();
	}

	private static MethodNode constructor() {
		MethodNode init = new MethodNode(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
		init.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));
		init.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false));
		init.instructions.add(new InsnNode(Opcodes.RETURN));
		return init;
	}

	/** The event the other family's answer hook constructs, so a runtime jar can say what the hook posts. */
	private static byte[] event() {
		ClassNode event = new ClassNode();
		event.visit(Opcodes.V17, Opcodes.ACC_PUBLIC, PROBE_EVENT, null, "java/lang/Object", null);
		event.methods.add(constructor());
		ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
		event.accept(writer);
		return writer.toByteArray();
	}

	private static String describe(Object example, int value) throws Exception {
		return (String) example.getClass().getMethod("describe", int.class).invoke(example, value);
	}

	/** The other family's hook owner: each hook forwards to this test's recorder of the same name. */
	private static byte[] probes() {
		ClassNode probe = new ClassNode();
		probe.visit(Opcodes.V17, Opcodes.ACC_PUBLIC, FORGE, null, "java/lang/Object", null);
		for (String[] hook : new String[][] { { "answer", JOIN }, { "allow", "(Ljava/lang/String;)Z" },
				{ "allowValue", "(I)Z" }, { "notice", "(Ljava/lang/String;J)V" } }) {
			MethodNode method = new MethodNode(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC, hook[0], hook[1], null, null);
			if (hook[0].equals("answer")) {
				method.instructions.add(new TypeInsnNode(Opcodes.NEW, PROBE_EVENT));
				method.instructions.add(new InsnNode(Opcodes.DUP));
				method.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL, PROBE_EVENT, "<init>", "()V", false));
				method.instructions.add(new InsnNode(Opcodes.POP));
			}
			int slot = 0;
			for (org.objectweb.asm.Type argument : org.objectweb.asm.Type.getArgumentTypes(hook[1])) {
				method.instructions.add(new VarInsnNode(argument.getOpcode(Opcodes.ILOAD), slot));
				slot += argument.getSize();
			}
			method.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC, RECORDER, hook[0], hook[1], false));
			method.instructions.add(new InsnNode(org.objectweb.asm.Type.getReturnType(hook[1]).getOpcode(Opcodes.IRETURN)));
			probe.methods.add(method);
		}
		ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
		probe.accept(writer);
		return writer.toByteArray();
	}

	private static final class Loader extends ClassLoader {
		Loader() { super(LeadingHookBlockTest.class.getClassLoader()); }

		Class<?> define(String name, byte[] bytes) { return defineClass(name.replace('/', '.'), bytes, 0, bytes.length); }
	}

	private static List<AbstractInsnNode> executable(MethodNode method) {
		return AdditiveMethodMergerTest.executable(method);
	}

	private static List<String> calls(MethodNode method) {
		List<String> out = new ArrayList<>();
		for (AbstractInsnNode instruction : method.instructions) {
			if (instruction instanceof MethodInsnNode call) out.add(call.owner + "." + call.name);
		}
		return out;
	}
}
