/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.tools;

import static org.junit.jupiter.api.Assertions.*;
import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.*;
import org.objectweb.asm.tree.*;

class ProviderContractExecutionTest {
    private static final String GAME="unrelated/game/Host",STRONG="unrelated/api/Resettable",CANONICAL="unrelated/nativeimpl/Canonical",PEER="unrelated/nativeimpl/Other";
    @Test void nominalViewsKeepCanonicalConcreteTypeAndOneCacheAcrossBothRefreshPaths()throws Exception{
        Fixture fixture=fixture(false,false);Class<?> host=fixture.type;Object object=host.getConstructor().newInstance();Object first=host.getMethod("nativeRead").invoke(object);
        assertSame(first,host.getMethod("otherRead").invoke(object));assertEquals(1,host.getField("computations").getInt(null));
        Object nativeProvider=field(host,object,"Ljava/util/function/Supplier;"),otherProvider=field(host,object,"L"+STRONG+";");assertEquals(CANONICAL.replace('/','.'),nativeProvider.getClass().getName());assertNotSame(nativeProvider,otherProvider);
        host.getMethod("otherClear").invoke(object);Object next=host.getMethod("nativeRead").invoke(object);assertNotSame(first,next);assertSame(next,host.getMethod("otherRead").invoke(object));assertEquals(2,host.getField("computations").getInt(null));
        host.getMethod("nativeClear").invoke(object);Object third=host.getMethod("otherRead").invoke(object);assertNotSame(next,third);assertSame(third,host.getMethod("nativeRead").invoke(object));assertEquals(3,host.getField("computations").getInt(null));
    }
    @Test void concurrentCallsThroughBothInterfacesUseCanonicalSynchronizationAndReturnOneValue()throws Exception{
        Fixture fixture=fixture(false,false);Class<?> host=fixture.type;Object object=host.getConstructor().newInstance();ExecutorService workers=Executors.newFixedThreadPool(12);CountDownLatch start=new CountDownLatch(1);
        try{List<Future<Object>> results=new ArrayList<>();for(int i=0;i<48;i++){String method=i%2==0?"nativeRead":"otherRead";results.add(workers.submit(()->{start.await();return host.getMethod(method).invoke(object);}));}start.countDown();Object first=results.get(0).get(5,TimeUnit.SECONDS);assertNotNull(first);for(Future<Object> result:results)assertSame(first,result.get(5,TimeUnit.SECONDS));assertEquals(1,host.getField("computations").getInt(null));}
        finally{workers.shutdownNow();}
    }
    @Test void externalPutfieldChangesBothLiveViewsAndBothResetPathsAcceptPlainSuppliers()throws Exception{
        Fixture fixture=fixture(false,false);Class<?> host=fixture.type;Object object=host.getConstructor().newInstance();Object initial=host.getMethod("nativeRead").invoke(object);
        Object original=field(host,object,"Ljava/util/function/Supplier;"),view=field(host,object,"L"+STRONG+";");
        java.util.function.Supplier<Object> plain=()->List.of("replacement");Class<?> writer=host.getClassLoader().loadClass("unrelated.mod.Writer");
        writer.getMethod("install",host,java.util.function.Supplier.class).invoke(null,object,plain);
        assertSame(plain,field(host,object,"Ljava/util/function/Supplier;"));assertSame(view,field(host,object,"L"+STRONG+";"),"the stronger view's identity is stable");
        assertEquals(List.of("replacement"),host.getMethod("nativeRead").invoke(object));assertEquals(List.of("replacement"),host.getMethod("otherRead").invoke(object));
        host.getMethod("nativeClear").invoke(object);host.getMethod("otherClear").invoke(object);assertEquals(List.of("replacement"),host.getMethod("otherRead").invoke(object));assertEquals(1,host.getField("computations").getInt(null));
        writer.getMethod("install",host,java.util.function.Supplier.class).invoke(null,object,original);host.getMethod("otherClear").invoke(object);Object renewed=host.getMethod("nativeRead").invoke(object);assertNotSame(initial,renewed);assertSame(renewed,host.getMethod("otherRead").invoke(object));assertEquals(2,host.getField("computations").getInt(null));
    }
    @Test void replacementImplementingTheStrongerPublishedInterfaceRetainsItsOwnResetCapability()throws Exception{
        Fixture fixture=fixture(false,false);Class<?> host=fixture.type;Object object=host.getConstructor().newInstance();java.util.concurrent.atomic.AtomicInteger produced=new java.util.concurrent.atomic.AtomicInteger();
        Object replacement=host.getClassLoader().loadClass(PEER.replace('/','.')).getMethod("make",java.util.function.Supplier.class).invoke(null,(java.util.function.Supplier<Object>)()->"changed-"+produced.incrementAndGet());
        Class<?> writer=host.getClassLoader().loadClass("unrelated.mod.Writer");writer.getMethod("install",host,java.util.function.Supplier.class).invoke(null,object,replacement);
        assertEquals("changed-1",host.getMethod("nativeRead").invoke(object));assertEquals("changed-1",host.getMethod("otherRead").invoke(object));
        host.getMethod("nativeClear").invoke(object);assertEquals("changed-2",host.getMethod("otherRead").invoke(object));host.getMethod("otherClear").invoke(object);assertEquals("changed-3",host.getMethod("nativeRead").invoke(object));
    }
    @Test void nullableComputationCannotEraseTheTwoOriginalNullContracts(){assertThrows(IllegalStateException.class,()->fixture(true,false));}
    @Test void sameProviderAbiWithOpaqueGetterBehaviorCannotBeShared(){assertThrows(IllegalStateException.class,()->fixture(false,true));}
    private static Fixture fixture(boolean nullable,boolean opaque)throws Exception{
        ClassNode contract=node(STRONG);contract.access=Opcodes.ACC_PUBLIC|Opcodes.ACC_INTERFACE|Opcodes.ACC_ABSTRACT;contract.interfaces.add("java/util/function/Supplier");contract.methods.add(new MethodNode(Opcodes.ACC_PUBLIC|Opcodes.ACC_ABSTRACT,"clear","()V",null,null));
        ClassNode nativeProvider=provider(CANONICAL,"java/util/function/Supplier",false),peer=provider(PEER,STRONG,opaque);
        ClassNode nativeGame=host("Ljava/util/function/Supplier;",CANONICAL,nullable),otherGame=host("L"+STRONG+";",PEER,nullable),merged=clone(nativeGame);merged.fields.add(new FieldNode(Opcodes.ACC_PRIVATE,"cache","L"+STRONG+";",null,null));merged.methods.add(read("otherRead","L"+STRONG+";",STRONG));merged.methods.add(clear("otherClear","L"+STRONG+";",STRONG,true));
        Map<String,byte[]> original=new LinkedHashMap<>();for(ClassNode node:List.of(contract,nativeProvider,peer,nativeGame))original.put(node.name,bytes(node));ContractGraph graph=new ContractGraph(List.of(original));Map<String,ClassNode> carriers=new LinkedHashMap<>();assertEquals(1,FieldContractReconciler.reconcile(merged,otherGame,nativeGame,graph,carriers));
        for(FieldNode field:merged.fields)if(field.desc.equals("Ljava/util/function/Supplier;"))field.access=(field.access&~(Opcodes.ACC_PRIVATE|Opcodes.ACC_FINAL))|Opcodes.ACC_PUBLIC;
        ClassNode writer=node("unrelated/mod/Writer");MethodNode install=new MethodNode(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"install","(L"+GAME+";Ljava/util/function/Supplier;)V",null,null);install.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));install.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));install.instructions.add(new FieldInsnNode(Opcodes.PUTFIELD,GAME,"cache","Ljava/util/function/Supplier;"));install.instructions.add(new InsnNode(Opcodes.RETURN));writer.methods.add(install);original.put(writer.name,bytes(writer));original.put(peer.name,bytes(peer));
        original.put(GAME,generatedBytes(merged));for(ClassNode carrier:carriers.values())original.put(carrier.name,generatedBytes(carrier));ClassLoader loader=new ClassLoader(ProviderContractExecutionTest.class.getClassLoader()){@Override protected Class<?> findClass(String name)throws ClassNotFoundException{byte[] data=original.get(name.replace('.','/'));if(data==null)return super.findClass(name);return defineClass(name,data,0,data.length);}};return new Fixture(loader.loadClass(GAME.replace('/','.')));
    }
    private static ClassNode provider(String name,String contract,boolean opaque){
        ClassNode node=node(name);node.access|=Opcodes.ACC_FINAL;node.interfaces.add(contract);node.fields.add(new FieldNode(Opcodes.ACC_PRIVATE|Opcodes.ACC_FINAL,"factory","Ljava/util/function/Supplier;",null,null));node.fields.add(new FieldNode(Opcodes.ACC_PRIVATE|Opcodes.ACC_VOLATILE,"value","Ljava/lang/Object;",null,null));
        MethodNode constructor=new MethodNode(Opcodes.ACC_PUBLIC,"<init>","(Ljava/util/function/Supplier;)V",null,null);constructor.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));constructor.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,"java/lang/Object","<init>","()V",false));constructor.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));constructor.instructions.add(new VarInsnNode(Opcodes.ALOAD,1));constructor.instructions.add(new FieldInsnNode(Opcodes.PUTFIELD,name,"factory","Ljava/util/function/Supplier;"));constructor.instructions.add(new InsnNode(Opcodes.RETURN));node.methods.add(constructor);
        String result=contract.equals("java/util/function/Supplier")?"Ljava/util/function/Supplier;":"L"+contract+";";MethodNode make=new MethodNode(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"make","(Ljava/util/function/Supplier;)"+result,null,null);make.instructions.add(new TypeInsnNode(Opcodes.NEW,name));make.instructions.add(new InsnNode(Opcodes.DUP));make.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));make.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,name,"<init>",constructor.desc,false));make.instructions.add(new InsnNode(Opcodes.ARETURN));node.methods.add(make);
        MethodNode get=new MethodNode(Opcodes.ACC_PUBLIC|Opcodes.ACC_SYNCHRONIZED,"get","()Ljava/lang/Object;",null,null);LabelNode present=new LabelNode();get.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));get.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,name,"value","Ljava/lang/Object;"));get.instructions.add(new JumpInsnNode(Opcodes.IFNONNULL,present));get.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));get.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));get.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,name,"factory","Ljava/util/function/Supplier;"));get.instructions.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,"java/util/function/Supplier","get","()Ljava/lang/Object;",true));get.instructions.add(new FieldInsnNode(Opcodes.PUTFIELD,name,"value","Ljava/lang/Object;"));get.instructions.add(present);get.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));get.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,name,"value","Ljava/lang/Object;"));get.instructions.add(new InsnNode(Opcodes.ARETURN));if(opaque){get.instructions.clear();get.instructions.add(new InsnNode(Opcodes.ACONST_NULL));get.instructions.add(new InsnNode(Opcodes.ARETURN));}node.methods.add(get);
        MethodNode clear=new MethodNode(Opcodes.ACC_PUBLIC|Opcodes.ACC_SYNCHRONIZED,"clear","()V",null,null);clear.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));clear.instructions.add(new InsnNode(Opcodes.ACONST_NULL));clear.instructions.add(new FieldInsnNode(Opcodes.PUTFIELD,name,"value","Ljava/lang/Object;"));clear.instructions.add(new InsnNode(Opcodes.RETURN));node.methods.add(clear);return node;
    }
    private static ClassNode host(String field,String factory,boolean nullable){
        ClassNode node=node(GAME);node.fields.add(new FieldNode(Opcodes.ACC_PRIVATE,"cache",field,null,null));node.fields.add(new FieldNode(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"computations","I",null,null));MethodNode constructor=new MethodNode(Opcodes.ACC_PUBLIC,"<init>","()V",null,null);constructor.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));constructor.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,"java/lang/Object","<init>","()V",false));constructor.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));Handle metafactory=new Handle(Opcodes.H_INVOKESTATIC,"java/lang/invoke/LambdaMetafactory","metafactory","(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;",false);constructor.instructions.add(new InvokeDynamicInsnNode("get","()Ljava/util/function/Supplier;",metafactory,org.objectweb.asm.Type.getMethodType("()Ljava/lang/Object;"),new Handle(Opcodes.H_INVOKESTATIC,GAME,"compute","()Ljava/lang/Object;",false),org.objectweb.asm.Type.getMethodType("()Ljava/lang/Object;")));constructor.instructions.add(new MethodInsnNode(Opcodes.INVOKESTATIC,factory,"make","(Ljava/util/function/Supplier;)"+field,false));constructor.instructions.add(new FieldInsnNode(Opcodes.PUTFIELD,GAME,"cache",field));constructor.instructions.add(new InsnNode(Opcodes.RETURN));node.methods.add(constructor);
        MethodNode compute=new MethodNode(Opcodes.ACC_PRIVATE|Opcodes.ACC_STATIC,"compute","()Ljava/lang/Object;",null,null);compute.instructions.add(new FieldInsnNode(Opcodes.GETSTATIC,GAME,"computations","I"));compute.instructions.add(new InsnNode(Opcodes.ICONST_1));compute.instructions.add(new InsnNode(Opcodes.IADD));compute.instructions.add(new FieldInsnNode(Opcodes.PUTSTATIC,GAME,"computations","I"));if(nullable)compute.instructions.add(new InsnNode(Opcodes.ACONST_NULL));else{compute.instructions.add(new TypeInsnNode(Opcodes.NEW,"java/lang/Object"));compute.instructions.add(new InsnNode(Opcodes.DUP));compute.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL,"java/lang/Object","<init>","()V",false));}compute.instructions.add(new InsnNode(Opcodes.ARETURN));node.methods.add(compute);
        if(field.equals("Ljava/util/function/Supplier;")){node.methods.add(read("nativeRead",field,"java/util/function/Supplier"));node.methods.add(clear("nativeClear",field,CANONICAL,false));}else{node.methods.add(read("otherRead",field,STRONG));node.methods.add(clear("otherClear",field,STRONG,true));}return node;
    }
    private static MethodNode read(String name,String field,String owner){MethodNode method=new MethodNode(Opcodes.ACC_PUBLIC,name,"()Ljava/lang/Object;",null,null);method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,GAME,"cache",field));method.instructions.add(new MethodInsnNode(Opcodes.INVOKEINTERFACE,owner,"get","()Ljava/lang/Object;",true));method.instructions.add(new InsnNode(Opcodes.ARETURN));return method;}
    private static MethodNode clear(String name,String field,String owner,boolean itf){MethodNode method=new MethodNode(Opcodes.ACC_PUBLIC,name,"()V",null,null);method.instructions.add(new VarInsnNode(Opcodes.ALOAD,0));method.instructions.add(new FieldInsnNode(Opcodes.GETFIELD,GAME,"cache",field));if(!itf)method.instructions.add(new TypeInsnNode(Opcodes.CHECKCAST,owner));method.instructions.add(new MethodInsnNode(itf?Opcodes.INVOKEINTERFACE:Opcodes.INVOKEVIRTUAL,owner,"clear","()V",itf));method.instructions.add(new InsnNode(Opcodes.RETURN));return method;}
    private static Object field(Class<?> owner,Object instance,String descriptor)throws Exception{for(Field field:owner.getDeclaredFields())if(org.objectweb.asm.Type.getDescriptor(field.getType()).equals(descriptor)){field.setAccessible(true);return field.get(instance);}throw new AssertionError(descriptor);}
    private static ClassNode node(String name){ClassNode node=new ClassNode();node.version=Opcodes.V17;node.access=Opcodes.ACC_PUBLIC;node.name=name;node.superName="java/lang/Object";return node;}
    private static ClassNode clone(ClassNode source){ClassNode clone=new ClassNode();source.accept(clone);return clone;}
    private static byte[] generatedBytes(ClassNode node){ClassWriter writer=new ClassWriter(ClassWriter.COMPUTE_MAXS);node.accept(writer);return writer.toByteArray();}
    private static byte[] bytes(ClassNode node){ClassWriter writer=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);node.accept(writer);return writer.toByteArray();}
    private record Fixture(Class<?> type){}
}
