/* Copyright 2026 The Forbric Project. Licensed under the Apache License, Version 2.0. */
package net.forbric.kernel.boot;

import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.ToIntFunction;
import org.objectweb.asm.Type;
import net.forbric.kernel.boot.DefinedMethodContracts.MethodContract;
import net.forbric.kernel.util.ForbricLog;

/** Final same-loader input, source-body, native dispatch and physical-view witnesses. No game getter is replayed. */
public final class KernelCrossHostPredicateContracts {
    public record SpecialType(FieldShape holder,String projection,String descriptor){}
    public record FieldShape(String owner,String name,String descriptor,int flags){}
    public record Schema(String actor,String interaction,String tracker,String collectorKey,FieldShape primaryMap,FieldShape eyes,
                         FieldShape world,MethodContract worldGetter,MethodContract interactionGetter,MethodContract query,
                         List<MethodContract>actorGuards,List<MethodContract>definitions,MethodContract airQuestion,
                         String ownedQuestion,String ownedDescriptor,Map<MethodContract,Integer>flags,List<SpecialType>excluded){
        public Schema{actorGuards=List.copyOf(actorGuards);definitions=List.copyOf(definitions);flags=Map.copyOf(flags);excluded=List.copyOf(excluded);}
    }
    public record Source(MethodContract helper,List<MethodContract>guest,Map<MethodContract,Integer>flags){public Source{guest=List.copyOf(guest);flags=Map.copyOf(flags);}}
    private static final Map<String,Schema>schemas=new ConcurrentHashMap<>();
    private static final Map<String,Source>sources=new ConcurrentHashMap<>();
    private static final Map<String,MethodContract>hosts=new ConcurrentHashMap<>();
    private static final Set<String>diagnostics=ConcurrentHashMap.newKeySet();
    private KernelCrossHostPredicateContracts(){}
    public static void register(String key,Schema schema){Schema old=schemas.putIfAbsent(key,schema);if(old!=null&&!old.equals(schema))throw new IllegalStateException("ambiguous cross-host predicate schema");}
    public static void source(String key,Source source){Source old=sources.putIfAbsent(key,source);if(old!=null&&!old.equals(source))throw new IllegalStateException("ambiguous final source predicate");}
    public static void host(String key,MethodContract host){MethodContract old=hosts.putIfAbsent(key,host);if(old!=null&&!old.equals(host))throw new IllegalStateException("ambiguous final predicate host");}
    public static Schema schema(String key){return schemas.get(key);}
    public static boolean validates(Object actor,Object world,Object interaction,String key,Class<?> caller,ToIntFunction<Object>owned){
        Schema schema=schemas.get(key);Source source=sources.get(key);MethodContract host=hosts.get(key);
        if(schema==null||source==null||host==null||actor==null||world==null||interaction==null)return decline(actor,key,"source/host/input witness is unavailable",false);
        ClassLoader loader=actor.getClass().getClassLoader();try{
            if(world.getClass().getClassLoader()!=loader||interaction.getClass().getClassLoader()!=loader||caller.getClassLoader()!=loader||!caller.getName().equals(host.owner()))return decline(actor,key,"cross-loader or different caller context",false);
            if(!safeStatic(loader,host)||!DefinedMethodContracts.observed(loader,host)||!DefinedMethodContracts.observed(loader,source.helper()))return decline(actor,key,"final host/source helper changed or missing",false);
            for(var witness:schema.flags().entrySet())if(!shape(loader,witness.getKey(),witness.getValue()))return decline(actor,key,"native predicate dependency flags changed",false);
            for(var witness:source.flags().entrySet())if(!shape(loader,witness.getKey(),witness.getValue()))return decline(actor,key,"original source/helper flags changed",false);
            for(MethodContract guest:source.guest())if(!DefinedMethodContracts.observed(loader,guest))return decline(actor,key,"final original guest callback/helper changed or missing",false);
            if(!dispatch(actor,schema.worldGetter())||!dispatch(actor,schema.interactionGetter())||!dispatch(interaction,schema.query()))return decline(actor,key,"native concrete/changed world, interaction or query dispatch retained",true);
            for(MethodContract method:schema.actorGuards())if(!dispatch(actor,method))return decline(actor,key,"native concrete/changed actor predicate retained: "+method+" actual="+actualDispatch(actor,method),true);
            for(MethodContract method:schema.definitions()){Class<?> declaration=Class.forName(method.owner(),false,loader);if(declaration.getClassLoader()!=loader||!DefinedMethodContracts.observed(loader,method))return decline(actor,key,"final predicate dependency changed or missing",false);}
            Field worldField=field(schema.world(),loader);if(worldField.get(actor)!=world)return decline(actor,key,"captured source world differs from current default world",true);
            var physical=KernelTagSourceContracts.schema(schema.collectorKey());if(physical==null||!KernelTagSourceContracts.validates(interaction,schema.collectorKey()))return decline(actor,key,"physical source tag view witness is unavailable",false);
            Class<?> owner=Class.forName(physical.owner().replace('/','.'),false,loader);Field ready=owner.getDeclaredField(physical.readyField());ready.setAccessible(true);Field sourceMap=owner.getDeclaredField(physical.mapField());sourceMap.setAccessible(true);if(!ready.getBoolean(interaction)||sourceMap.get(interaction)==null)return decline(actor,key,"physical source view is not ready",false);
            Map<?,?> primary=(Map<?,?>)field(schema.primaryMap(),loader).get(interaction);Class<?> tracker=Class.forName(schema.tracker().replace('/','.'),false,loader);Field eyes=field(schema.eyes(),loader);
            for(var entry:primary.entrySet()){Object value=entry.getValue();if(value==null||value.getClass()!=tracker)return decline(actor,key,"native concrete tracker retained",true);if(!eyes.getBoolean(value))continue;Object type=entry.getKey();int ownedStatus=owned.applyAsInt(type);if(ownedStatus==0)return decline(actor,key,"native concrete fluid type retained",true);if(ownedStatus<0)return decline(actor,key,"owned type default changed or missing",false);for(SpecialType special:schema.excluded()){Object holder=field(special.holder(),loader).get(null);Object excluded=pureProjection(holder,special.projection(),special.descriptor(),loader);if(excluded==null)return decline(actor,key,"native special type projection changed or missing: "+projectionIdentity(holder,special),false);if(type==excluded)return decline(actor,key,"native special fluid type retained",true);}
                if(!DefinedMethodContracts.validates(type,schema.airQuestion()))return decline(actor,key,"native type default changed or missing",true);}
            return true;
        }catch(ReflectiveOperationException|RuntimeException|LinkageError unavailable){return decline(actor,key,"predicate field/definition witness is unavailable: "+unavailable.getClass().getSimpleName()+" "+unavailable.getMessage(),false);}
    }
    private static Object pureProjection(Object receiver,String name,String descriptor,ClassLoader loader)throws ReflectiveOperationException{return projection(receiver,name,descriptor,loader,new HashSet<>(),0);}
    /** Already-bound memoization may be read through a closed pure success path. No getter/binder is invoked. */
    private static Object projection(Object receiver,String name,String descriptor,ClassLoader loader,Set<String>active,int depth)throws ReflectiveOperationException{
        if(receiver==null||receiver.getClass().getClassLoader()!=loader||depth>8)return null;Method actual=receiver.getClass().getMethod(name);if(!Type.getMethodDescriptor(actual).equals(descriptor))return null;String id=actual.getDeclaringClass().getName()+"#"+name+descriptor+"@"+System.identityHashCode(receiver);if(!active.add(id))return null;
        var method=projectionMethod(actual,loader);if(method==null)return null;var code=opcodes(method);int from=0;org.objectweb.asm.tree.MethodInsnNode binder=null;
        if(code.size()>4&&aload(code.get(0))&&code.get(1).getOpcode()>=org.objectweb.asm.Opcodes.ICONST_0&&code.get(1).getOpcode()<=org.objectweb.asm.Opcodes.ICONST_1&&code.get(2)instanceof org.objectweb.asm.tree.MethodInsnNode call&&call.getOpcode()==org.objectweb.asm.Opcodes.INVOKEVIRTUAL&&call.desc.equals("(Z)V")){binder=call;from=3;}
        if(code.size()==3&&aload(code.get(0))&&code.get(1)instanceof org.objectweb.asm.tree.MethodInsnNode delegate&&(delegate.getOpcode()==org.objectweb.asm.Opcodes.INVOKEVIRTUAL||delegate.getOpcode()==org.objectweb.asm.Opcodes.INVOKEINTERFACE)&&Type.getArgumentTypes(delegate.desc).length==0&&code.get(2).getOpcode()==org.objectweb.asm.Opcodes.ARETURN)return projectionDelegate(receiver,delegate,loader,active,depth+1);
        if(code.size()<from+3||!aload(code.get(from))||!(code.get(from+1)instanceof org.objectweb.asm.tree.FieldInsnNode field&&field.getOpcode()==org.objectweb.asm.Opcodes.GETFIELD))return null;Field reflected=projectionField(field,loader);Object value=reflected.get(receiver);if(binder!=null&&!boundNoop(receiver,binder,field,loader))return null;
        int at=from+2;if(code.get(at)instanceof org.objectweb.asm.tree.JumpInsnNode bound&&bound.getOpcode()==org.objectweb.asm.Opcodes.IFNONNULL){if(value==null)return null;var load=nextOpcode(bound.label);if(!aload(load))return null;var same=nextOpcode(load);if(!(same instanceof org.objectweb.asm.tree.FieldInsnNode repeated&&sameField(field,repeated)))return null;at=code.indexOf(same)+1;}
        if(at>=code.size())return null;var terminal=code.get(at);if(terminal.getOpcode()==org.objectweb.asm.Opcodes.ARETURN)return value;
        if(terminal instanceof org.objectweb.asm.tree.MethodInsnNode delegate&&(delegate.getOpcode()==org.objectweb.asm.Opcodes.INVOKEINTERFACE||delegate.getOpcode()==org.objectweb.asm.Opcodes.INVOKEVIRTUAL)&&Type.getArgumentTypes(delegate.desc).length==0&&at+1<code.size()&&code.get(at+1).getOpcode()==org.objectweb.asm.Opcodes.ARETURN&&value!=null&&Class.forName(delegate.owner.replace('/','.'),false,loader).isInstance(value))return projectionDelegate(value,delegate,loader,active,depth+1);return null;
    }
    private static Object projectionDelegate(Object receiver,org.objectweb.asm.tree.MethodInsnNode call,ClassLoader loader,Set<String>active,int depth)throws ReflectiveOperationException{
        Class<?>owner=Class.forName(call.owner.replace('/','.'),false,loader);if(owner.getClassLoader()!=loader||!owner.isInstance(receiver))return null;Method symbolic=null;for(Class<?>type=owner;type!=null&&symbolic==null;type=type.getSuperclass())for(Method member:type.getDeclaredMethods())if(member.getName().equals(call.name)&&Type.getMethodDescriptor(member).equals(call.desc))symbolic=member;
        if(symbolic==null)for(Method member:owner.getMethods())if(member.getName().equals(call.name)&&Type.getMethodDescriptor(member).equals(call.desc))symbolic=member;if(symbolic==null||!Modifier.isPublic(symbolic.getModifiers())||Modifier.isStatic(symbolic.getModifiers()))return null;return projection(receiver,call.name,call.desc,loader,active,depth);
    }
    private static org.objectweb.asm.tree.MethodNode projectionMethod(Method actual,ClassLoader loader)throws ReflectiveOperationException{
        if(actual.getDeclaringClass().getClassLoader()!=loader||(actual.getModifiers()&(Modifier.STATIC|Modifier.ABSTRACT|Modifier.NATIVE|Modifier.SYNCHRONIZED))!=0)return null;String owner=actual.getDeclaringClass().getName();var current=net.forbric.kernel.mixin.NativeGameReferences.current(owner.replace('.','/'));if(current==null)return null;for(var method:current.methods)if(method.name.equals(actual.getName())&&method.desc.equals(Type.getMethodDescriptor(actual))){if(!method.tryCatchBlocks.isEmpty()||!shape(loader,new MethodContract(owner,method.name,method.desc,DefinedMethodContracts.fingerprint(method)),method.access))return null;return method;}return null;
    }
    private static boolean boundNoop(Object receiver,org.objectweb.asm.tree.MethodInsnNode call,org.objectweb.asm.tree.FieldInsnNode expected,ClassLoader loader)throws ReflectiveOperationException{
        Class<?>owner=Class.forName(call.owner.replace('/','.'),false,loader);Method binder=null;for(Class<?>type=owner;type!=null&&binder==null;type=type.getSuperclass())for(Method member:type.getDeclaredMethods())if(member.getName().equals(call.name)&&Type.getMethodDescriptor(member).equals(call.desc))binder=member;
        if(binder==null||!binder.getDeclaringClass().isInstance(receiver)||(binder.getModifiers()&(Modifier.PRIVATE|Modifier.FINAL))==0)return false;var method=projectionMethod(binder,loader);if(method==null)return false;var code=opcodes(method);return code.size()>=4&&aload(code.get(0))&&code.get(1)instanceof org.objectweb.asm.tree.FieldInsnNode f&&sameField(expected,f)&&code.get(2)instanceof org.objectweb.asm.tree.JumpInsnNode branch&&branch.getOpcode()==org.objectweb.asm.Opcodes.IFNULL&&code.get(3).getOpcode()==org.objectweb.asm.Opcodes.RETURN&&projectionField(f,loader).get(receiver)!=null;
    }
    private static Field projectionField(org.objectweb.asm.tree.FieldInsnNode field,ClassLoader loader)throws ReflectiveOperationException{Class<?>owner=Class.forName(field.owner.replace('/','.'),false,loader);if(owner.getClassLoader()!=loader)throw new IllegalArgumentException("different projection field loader");Field value=owner.getDeclaredField(field.name);if(!Type.getDescriptor(value.getType()).equals(field.desc)||Modifier.isStatic(value.getModifiers())||Modifier.isVolatile(value.getModifiers()))throw new IllegalArgumentException("changed projection field");var definition=net.forbric.kernel.mixin.NativeGameReferences.current(field.owner);if(definition==null)throw new IllegalArgumentException("unknown projection field");var declared=definition.fields.stream().filter(f->f.name.equals(field.name)&&f.desc.equals(field.desc)).findFirst().orElseThrow(()->new IllegalArgumentException("missing projection field"));int mask=Modifier.PUBLIC|Modifier.PRIVATE|Modifier.PROTECTED|Modifier.STATIC|Modifier.FINAL|Modifier.VOLATILE|Modifier.TRANSIENT;if((declared.access&mask)!=(value.getModifiers()&mask))throw new IllegalArgumentException("changed projection field flags");value.setAccessible(true);return value;}
    private static boolean sameField(org.objectweb.asm.tree.FieldInsnNode a,org.objectweb.asm.tree.FieldInsnNode b){return a.getOpcode()==b.getOpcode()&&a.owner.equals(b.owner)&&a.name.equals(b.name)&&a.desc.equals(b.desc);}
    private static boolean aload(org.objectweb.asm.tree.AbstractInsnNode node){return node instanceof org.objectweb.asm.tree.VarInsnNode self&&self.getOpcode()==org.objectweb.asm.Opcodes.ALOAD&&self.var==0;}
    private static org.objectweb.asm.tree.AbstractInsnNode nextOpcode(org.objectweb.asm.tree.AbstractInsnNode node){node=node.getNext();while(node!=null&&node.getOpcode()<0)node=node.getNext();return node;}
    private static List<org.objectweb.asm.tree.AbstractInsnNode>opcodes(org.objectweb.asm.tree.MethodNode method){List<org.objectweb.asm.tree.AbstractInsnNode>code=new ArrayList<>();for(var node:method.instructions)if(node.getOpcode()>=0)code.add(node);return code;}
    private static String projectionIdentity(Object holder,SpecialType special){if(holder==null)return "null";try{Method method=holder.getClass().getMethod(special.projection());return holder.getClass().getName()+" -> "+method.getDeclaringClass().getName()+"#"+method.getName()+Type.getMethodDescriptor(method)+" flags="+method.getModifiers();}catch(ReflectiveOperationException missing){return holder.getClass().getName()+" missing "+special.projection()+special.descriptor();}}
    private static String actualDispatch(Object receiver,MethodContract contract){for(Method method:receiver.getClass().getMethods())if(method.getName().equals(contract.name())&&Type.getMethodDescriptor(method).equals(contract.descriptor()))return method.getDeclaringClass().getName()+"#"+method.getName()+contract.descriptor()+" flags="+method.getModifiers();return "unresolved";}
    private static boolean dispatch(Object receiver,MethodContract contract){return DefinedMethodContracts.validates(receiver,contract)||DefinedMethodContracts.validatesTransparentDispatch(receiver,contract)||DefinedMethodContracts.validatesDefaultDispatch(receiver,contract);}
    private static Method method(ClassLoader loader,MethodContract contract)throws ReflectiveOperationException{Class<?>owner=Class.forName(contract.owner(),false,loader);if(owner.getClassLoader()!=loader)throw new IllegalArgumentException("different method loader");for(Method method:owner.getDeclaredMethods())if(method.getName().equals(contract.name())&&Type.getMethodDescriptor(method).equals(contract.descriptor()))return method;throw new NoSuchMethodException(contract.name());}
    private static boolean safeStatic(ClassLoader loader,MethodContract contract)throws ReflectiveOperationException{int flags=method(loader,contract).getModifiers();return Modifier.isStatic(flags)&&(flags&(Modifier.SYNCHRONIZED|Modifier.NATIVE|Modifier.ABSTRACT))==0;}
    private static boolean shape(ClassLoader loader,MethodContract contract,int expected)throws ReflectiveOperationException{int mask=Modifier.PUBLIC|Modifier.PRIVATE|Modifier.PROTECTED|Modifier.STATIC|Modifier.FINAL|Modifier.SYNCHRONIZED|Modifier.NATIVE|Modifier.ABSTRACT;int flags=method(loader,contract).getModifiers();return (flags&mask)==(expected&mask)&&(flags&(Modifier.SYNCHRONIZED|Modifier.NATIVE|Modifier.ABSTRACT))==0&&DefinedMethodContracts.observed(loader,contract);}
    private static Field field(FieldShape shape,ClassLoader loader)throws ReflectiveOperationException{Class<?> owner=Class.forName(shape.owner().replace('/','.'),false,loader);if(owner.getClassLoader()!=loader)throw new IllegalArgumentException("different field loader");Field field=owner.getDeclaredField(shape.name());int mask=Modifier.PUBLIC|Modifier.PRIVATE|Modifier.PROTECTED|Modifier.STATIC|Modifier.FINAL|Modifier.VOLATILE;if(!Type.getDescriptor(field.getType()).equals(shape.descriptor())||(field.getModifiers()&mask)!=(shape.flags()&mask))throw new IllegalArgumentException("changed field shape");field.setAccessible(true);return field;}
    public static boolean decline(Object receiver,String key,String why,boolean nativePriority){String id=key+":"+(receiver==null?"null":receiver.getClass().getName()+"@"+System.identityHashCode(receiver.getClass().getClassLoader()))+":"+why;if(diagnostics.add(id)){String message="[Forbric/Mixin] original cross-host predicate callback was not executed; native predicate island retained: "+why+" (source="+key+")";if(nativePriority)ForbricLog.info(message);else ForbricLog.warn(message);}return false;}
    public static void resetForTests(){schemas.clear();sources.clear();hosts.clear();diagnostics.clear();}
}
